### ISSUE TITLE
跑/examples/redis_pool.php实例出现段错误

### ISSUE THREAD

**Issue by kcloze** [swoole/swoole-src#1003]
```
(gdb) 
#0  0x0000000000000000 in ?? ()
#1  0x00007fc68888a835 in swReactorThread_onRead (reactor=<optimized out>, event=<optimized out>) at /data/src/swoole-src/src/network/ReactorThread.c:855
#2  0x00007fc6888816cb in swReactorEpoll_wait (reactor=0x55b63ac97c88, timeo=<optimized out>) at /data/src/swoole-src/src/reactor/ReactorEpoll.c:258
#3  0x00007fc68888da63 in swReactorProcess_loop (pool=<optimized out>, worker=worker@entry=0x7fff058179e0) at /data/src/swoole-src/src/network/ReactorProcess.c:379
#4  0x00007fc68888e416 in swReactorProcess_start (serv=serv@entry=0x55b63ac0fe60) at /data/src/swoole-src/src/network/ReactorProcess.c:112
#5  0x00007fc688885618 in swServer_start (serv=serv@entry=0x55b63ac0fe60) at /data/src/swoole-src/src/network/Server.c:705
#6  0x00007fc68885ca4d in zim_swoole_http_server_start (execute_data=0x7fc689213160, return_value=0x7fc689213150) at /data/src/swoole-src/swoole_http_server.c:1477
#7  0x000055b63a02385a in dtrace_execute_internal ()
#8  0x000055b63a0b87c0 in ?? ()
#9  0x000055b63a073ccb in execute_ex ()
#10 0x000055b63a0236f1 in dtrace_execute_ex ()
#11 0x000055b63a0c7df7 in zend_execute ()
#12 0x000055b63a0338f3 in zend_execute_scripts ()
#13 0x000055b639fd3b20 in php_execute_script ()
#14 0x000055b63a0c9ab7 in ?? ()
#15 0x000055b639eb8154 in main ()

```

PHP Version: PHP 7.0.11-2+deb.sury.org~xenial+1 (cli) ( NTS )
swoole:最新2.0.1分支代码
os: ubuntu 16.4

**Comment by kcloze** [comment]
可能跟协程无关,搞成最简单的居然也报错:
```

$server = new Swoole\Http\Server('0.0.0.0', 9501, SWOOLE_BASE);

$server->on('Request', function ($request, $response) {
    var_dump(time());
    
});

$server->start();
```

**Comment by kcloze** [comment]
可能跟ubuntu系统或PHP编译版本有关，PHP是通过apt安装的，换了两台机器，照样会出现

**Comment by kcloze** [comment]
[Uploading core…](core文件)

**Comment by kcloze** [comment]
最后回到1.9的版本也是如此,应该是php版本的问题了
