### ISSUE TITLE
在 Coroutine::create 创建的协程内调用工具类的方法 core dump

### ISSUE THREAD

**Issue by cbdon** [swoole/swoole-src#1127]
````php
// 以下调用会core dump
$html = Parser::autoConvertCharset($this->html);
````

````php
// 以下调用没问题
$html = $this->html;
$html = Parser::autoConvertCharset($html);
````

````gdb
[New LWP 6107]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php run.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000007bcce4 in ZEND_FETCH_OBJ_R_SPEC_UNUSED_CONST_HANDLER () at /data/packages/php-7.1.2/Zend/zend_vm_execute.h:28554
28554                   if (UNEXPECTED(zobj->handlers->read_property == NULL)) {
(gdb) bt
#0  0x00000000007bcce4 in ZEND_FETCH_OBJ_R_SPEC_UNUSED_CONST_HANDLER () at /data/packages/php-7.1.2/Zend/zend_vm_execute.h:28554
#1  0x00000000007ba3ab in execute_ex (ex=<optimized out>) at /data/packages/php-7.1.2/Zend/zend_vm_execute.h:429
#2  0x00007fdb653bb67f in sw_coro_resume (sw_current_context=0x7fdb65a84e80, retval=retval@entry=0x7ffe60cc5b00, coro_retval=coro_retval@entry=0x0) at /data/repositories/swoole/swoole-src/swoole_coroutine.c:471
#3  0x00007fdb653d368b in http_client_coro_onReceive (cli=<optimized out>, data=0x7fdb65aca020 " \344{", length=<optimized out>) at /data/repositories/swoole/swoole-src/swoole_http_client_coro.c:463
#4  0x00007fdb654166a7 in swClient_onStreamRead (reactor=0x170, event=0x7ffe60cc5bc0) at /data/repositories/swoole/swoole-src/src/network/Client.c:902
#5  0x00007fdb6540ff7c in swReactorEpoll_wait (reactor=0x25dc2c0, timeo=0x10b1c40 <executor_globals>) at /data/repositories/swoole/swoole-src/src/reactor/ReactorEpoll.c:260
#6  0x00007fdb653bc47f in php_swoole_event_wait () at /data/repositories/swoole/swoole-src/swoole_event.c:191
#7  0x00000000007646cb in zend_call_function (fci=fci@entry=0x7ffe60cc5d10, fci_cache=<optimized out>, fci_cache@entry=0x0) at /data/packages/php-7.1.2/Zend/zend_execute_API.c:842
#8  0x0000000000764b25 in _call_user_function_ex (object=object@entry=0x0, function_name=<optimized out>, retval_ptr=retval_ptr@entry=0x7ffe60cc5d70, param_count=<optimized out>, params=<optimized out>,
    no_separation=no_separation@entry=1) at /data/packages/php-7.1.2/Zend/zend_execute_API.c:672
#9  0x000000000068d0e7 in user_shutdown_function_call (zv=<optimized out>) at /data/packages/php-7.1.2/ext/standard/basic_functions.c:4974
#10 0x0000000000784a5c in zend_hash_apply (ht=0x7fdb65a9e930, apply_func=apply_func@entry=0x68d030 <user_shutdown_function_call>) at /data/packages/php-7.1.2/Zend/zend_hash.c:1508
#11 0x000000000068fe46 in php_call_shutdown_functions () at /data/packages/php-7.1.2/ext/standard/basic_functions.c:5058
#12 0x0000000000713065 in php_request_shutdown (dummy=<optimized out>) at /data/packages/php-7.1.2/main/main.c:1819
#13 0x0000000000816b87 in do_cli (argc=368, argv=0x10b1c40 <executor_globals>) at /data/packages/php-7.1.2/sapi/cli/php_cli.c:1160
#14 0x000000000042e88c in main (argc=368, argv=0x10b1c40 <executor_globals>) at /data/packages/php-7.1.2/sapi/cli/php_cli.c:1381
(gdb)
````

**Comment by zhaolei** [comment]
就想问一下你的2.0.7版本在哪下的

**Comment by cbdon** [comment]
是github上clone的，版本号 cdf7b96c2df866afe8cb5e4501a01e428e4d5ee2，也就是最新的代码

**Comment by xyzhu1120** [comment]
@cbdon 可以发一下简单复现的case吗？

**Comment by matyhtf** [comment]
[Uploading spider.tar.gz…](代码)

**Comment by matyhtf** [comment]
[spider.tar.gz](https://github.com/swoole/swoole-src/files/832888/spider.tar.gz)

**Comment by xyzhu1120** [comment]
@cbdon 框架跑起来缺依赖，我自己写了一个简单的脚本尝试，没有复现core，怎么需要改一下脚本？

```

<?php
use \Swoole\Coroutine\Http\Client as HttpClient;

class Parser {
    static public function autoConvert($text) {
        return $text;
    }
}

abstract class A {
    public $html;
    public function convert(){
        $html = Parser::autoConvert($this->html);
        echo $html;
    }
}

Class B extends A{
    public function run() {
        $cli = new HttpClient('www.baidu.com', 80);
        $cli->setHeaders([
            'Host' => 'www.baidu.com',
            "User-Agent" => 'Chrome/49.0.2587.3',
            'Accept' => 'text/html,application/xhtml+xml,application/xml',
            'Accept-Encoding' => 'gzip',
        ]);
        $cli->set(['timeout' => 1]);
        $cli->get('/');
        $this->html = $cli->body;
        $cli->close();

        $this->convert();
    }
}

$b = new B();
Swoole\Coroutine::create([$b, 'run']);

```

**Comment by cbdon** [comment]
@xyzhu1120 以下代码会产生core dump，暂时不确定是不是同一个原因

````php
<?php

for ($i = 0; $i < 3; $i++)
{
    $a = new A();
    \Swoole\Coroutine::create([$a, 'method1']);
}

class A
{
    public function method1()
    {
        try
        {
            $client = new \Swoole\Coroutine\Http\Client('www.qq.com', 80);
            $client->get('/');
            $client->close();

            throw new \Exception();
        }
        catch (\Exception $e)
        {
            $this->method2();
        }
    }

    public function method2()
    {
    }
}

**Comment by xyzhu1120** [comment]
@cbdon 第一次循环的$a在第二次循环的时候会被释放掉，导致后面this就core了，可以用closure来规避，问题我们继续跟进，关于你的一个问题，你可以确认一下，是不是也是这个问题，是不是存在对象被释放的问题

**Comment by matyhtf** [comment]
新版本已修复。
