### ISSUE TITLE
swoole_http_client 不定期出现 signal=11 

### ISSUE THREAD

**Issue by bobzhangyong** [swoole/swoole-src#1167]
使用swoole内置的http client 访问外部 url 的时候（已经开启https 功能），不定期 出现 signal=11

swoole 版本 1.8.7
php 版本 5.5.30 

gdb 如下

```
#0  php_http_parser_execute (parser=0x4fc8f08, settings=<value optimized out>, data=<value optimized out>, len=554) at /root/swoole-src-1.8.7-stable/thirdparty/php_http_parser.c:1441
#1  0x00007fa40c53bde9 in http_client_onReceive (cli=<value optimized out>, data=0x4f5c510 "\360n\364\004", length=554) at /root/swoole-src-1.8.7-stable/swoole_http_client.c:485
#2  0x00007fa40c555232 in swClient_onStreamRead (reactor=<value optimized out>, event=0x7ffd4a8a24f0) at /root/swoole-src-1.8.7-stable/src/network/Client.c:679
#3  0x00007fa40c54f001 in swReactorEpoll_wait (reactor=0x1d0d2f0, timeo=<value optimized out>) at /root/swoole-src-1.8.7-stable/src/reactor/ReactorEpoll.c:258
#4  0x00007fa40c55df3f in swWorker_loop (factory=<value optimized out>, worker_id=<value optimized out>) at /root/swoole-src-1.8.7-stable/src/network/Worker.c:496
#5  0x00007fa40c55af70 in swManager_spawn_worker (factory=0x1cc8070, worker_id=18) at /root/swoole-src-1.8.7-stable/src/network/Manager.c:679
#6  0x00007fa40c55b0e1 in swManager_loop_sync (factory=0x1cc8070) at /root/swoole-src-1.8.7-stable/src/network/Manager.c:539
#7  0x00007fa40c55c038 in swManager_start (factory=0x1cc8070) at /root/swoole-src-1.8.7-stable/src/network/Manager.c:183
#8  0x00007fa40c54c202 in swFactoryProcess_start (factory=0x1cc8070) at /root/swoole-src-1.8.7-stable/src/factory/FactoryProcess.c:86
#9  0x00007fa40c551cfe in swServer_start (serv=0x1cc7c40) at /root/swoole-src-1.8.7-stable/src/network/Server.c:645
#10 0x00007fa40c535ba9 in zim_swoole_http_server_start (ht=<value optimized out>, return_value=0x1ce0cc8, return_value_ptr=<value optimized out>, this_ptr=0x1cdde88, return_value_used=<value optimized out>) at /root/swoole-src-1.8.7-stable/swoole_http_server.c:1379
#11 0x00000000008935db in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /root/zoudawei/php-5.5.30/Zend/zend_vm_execute.h:550
#12 0x0000000000884e40 in execute_ex (execute_data=0x7fa417c6d348) at /root/zoudawei/php-5.5.30/Zend/zend_vm_execute.h:363
#13 0x0000000000810699 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/zoudawei/php-5.5.30/Zend/zend.c:1327
#14 0x00000000007b1e7a in php_execute_script (primary_file=0x7ffd4a8a5e60) at /root/zoudawei/php-5.5.30/main/main.c:2525
#15 0x00000000008c2c5c in do_cli (argc=4, argv=0x1935af0) at /root/zoudawei/php-5.5.30/sapi/cli/php_cli.c:994
#16 0x00000000008c33f8 in main (argc=4, argv=0x1935af0) at /root/zoudawei/php-5.5.30/sapi/cli/php_cli.c:1378
```

**Comment by matyhtf** [comment]
新版本已修复此问题。请升级至1.9.8
