### ISSUE TITLE
[Swoole 1.9.6] swoole_mysql 无法使用 DNS 别名连接的问题（含 swoole_async_dns_lookup 结果错误）

### ISSUE THREAD

**Issue by movoin** [swoole/swoole-src#1175]
#### 描述

我使用 Docker Compose 来开发，但在连接 MySQL 的时候遇到了问题。

下面是直接从 Wiki 中扒下来的代码：

```php
<?php

$db = new swoole_mysql;
$server = [
    'host' => 'mysql',
    'user' => 'bucket',
    'password' => '123456',
    'database' => 'logbucket',
    'chatset' => 'utf8',
];

$db->connect($server, function ($db, $r) {
    if ($r === false) {
        var_dump($db->connect_errno, $db->connect_error);
        die;
    }
    $sql = 'show tables';
    $db->query($sql, function(swoole_mysql $db, $r) {
        global $s;
        if ($r === false)
        {
            var_dump($db->error, $db->errno);
        }
        elseif ($r === true )
        {
            var_dump($db->affected_rows, $db->insert_id);
        }
        var_dump($r);
        $db->close();
    });
});
```

运行报错如下：

```
PHP Fatal error:  Uncaught swoole_mysql_exception: connect to mysql server[mysql:3306] failed. in /app/ApiBucket-Database/test.php:31
```

使用 PDO 连接却没有问题。

```php
<?php
try {
    $pdo = new PDO('mysql:dbname=logbucket;host=mysql;port=3306', 'bucket', '123456');
} catch(PDOException $pe) {
    die($pe->getMessage());
}
```

-------

```
ping mysql
PING mysql (172.18.0.2) 56(84) bytes of data.
64 bytes from logbucket_mysql_1.logbucket_default (172.18.0.2): icmp_seq=1 ttl=64 time=0.186 ms
64 bytes from logbucket_mysql_1.logbucket_default (172.18.0.2): icmp_seq=2 ttl=64 time=0.073 ms
64 bytes from logbucket_mysql_1.logbucket_default (172.18.0.2): icmp_seq=3 ttl=64 time=0.069 ms
```

```php
$server = [
    'host' => '172.18.0.2',
    'user' => 'bucket',
    'password' => '123456',
    'database' => 'logbucket',
    'chatset' => 'utf8',
];
```

尝试用 IP 连接 MySQL，可以正常连接。

于是乎就想用 swoole_async_dns_lookup 来得到 IP, 结果还是连不上，于是又测试一下，结果 IP 竟然是错的。

```php
<?php
swoole_async_dns_lookup('mysql', function ($host, $ip) {
    echo 'swoole_async_dns_lookup > ', $ip, PHP_EOL;
});

echo 'gethostbyname > ', gethostbyname('mysql'), PHP_EOL;
```

```
gethostbyname > 172.18.0.2
swoole_async_dns_lookup > 172.18.0.0
```

#### 环境说明

- PHP 7.0.16
- Swoole 1.9.6
- CentOS 6.5
- Docker 17.03.1-ce

**Comment by kimkit** [comment]
same with #1164 ?

**Comment by movoin** [comment]
@kimkit 这个我就无从确定了

**Comment by kimkit** [comment]
@movoin please try again using the latest code.

**Comment by matyhtf** [comment]
已修复。请使用最新的 `1.9` 分支代码

**Comment by movoin** [comment]
已经按要求使用 1.9.8, 但问题依然存在，而此次，我并未使用 Docker Compose 而是在同一个容器中安装了 MySQL, PDO 正常连接。

```
$db = new swoole_mysql;
$server = [
    'host' => 'localhost',
    'user' => 'logbucket_user',
    'password' => 'logbucket_pwd',
    'database' => 'logbucket',
    'chatset' => 'utf8',
];

$db->connect($server, function ($db, $r) {
    if ($r === false) {
        var_dump($db->connect_errno, $db->connect_error);
        die;
    }
    $sql = 'show tables';
    $db->query($sql, function(swoole_mysql $db, $r) {
        global $s;
        if ($r === false)
        {
            var_dump($db->error, $db->errno);
        }
        elseif ($r === true )
        {
            var_dump($db->affected_rows, $db->insert_id);
        }
        var_dump($r);
        $db->close();
    });
});
```

报错信息：

```
PHP Fatal error:  Uncaught swoole_mysql_exception: connect to mysql server[localhost:3306] failed. in /app/ApiBucket-Database/test.php:31
Stack trace:
#0 /app/ApiBucket-Database/test.php(31): swoole_mysql->connect(Array, Object(Closure))
#1 {main}
  thrown in /app/ApiBucket-Database/test.php on line 31

Fatal error: Uncaught swoole_mysql_exception: connect to mysql server[localhost:3306] failed. in /app/ApiBucket-Database/test.php:31
Stack trace:
#0 /app/ApiBucket-Database/test.php(31): swoole_mysql->connect(Array, Object(Closure))
#1 {main}
  thrown in /app/ApiBucket-Database/test.php on line 31
```

**Comment by movoin** [comment]
而使用 127.0.0.1 可以连接，是不是只能用 IP? 但这不科学啊～

**Comment by movoin** [comment]
@matyhtf 是要从 Git 拉 1.9 分支？刚看了 1.9.8 中并没有 #1164

**Comment by matyhtf** [comment]
对

**Comment by xlight** [comment]
不同docker container 之间使用localhost连接？你这非常不科学啊
Tianfeng <notifications@github.com>于2017年4月13日 周四下午3:43写道：

**Comment by movoin** [comment]
@xlight 已经按要求使用 1.9.8, 但问题依然存在，而此次，我并未使用 Docker Compose 而是在同一个容器中安装了 MySQL, PDO 正常连接。

你是否应该认真看一眼再评论？

**Comment by matyhtf** [comment]
用 最新的 1.9 分支代码

**Comment by twose** [comment]
@pantaovay 非IP地址都会触发DNS查询, localhost处理为127.0.0.1没有任何问题
