### ISSUE TITLE
1.9.9：swoole_http_request->$files错误

### ISSUE THREAD

**Issue by goodnightAndy** [swoole/swoole-src#1210]
测试代码：
$serv = new swoole_http_server('127.0.0.1', 9503, SWOOLE_BASE);
$serv->on('Request', function (swoole_http_request $req, swoole_http_response $resp)
{
    var_dump($req->files);
    $resp->end('111');
});
$serv->start();
postman模拟：
![image](https://cloud.githubusercontent.com/assets/7625091/26091766/c9d59e50-3a3f-11e7-8cf6-911a21fd9918.png)
测试结果（v1.8.10）：
![image](https://cloud.githubusercontent.com/assets/7625091/26091801/00c47436-3a40-11e7-98ad-9c603de224c5.png)
测试结果（v1.9.9）：
![image](https://cloud.githubusercontent.com/assets/7625091/26091774/dd719f18-3a3f-11e7-8a76-2afb5c5968bc.png)

**Comment by matyhtf** [comment]
我这里无法重现你的问题。

**Comment by motecshine** [comment]
bt 栈 打印出来 看样子是  同一个* zval free 了两次

**Comment by goodnightAndy** [comment]
```
#0  _zval_ptr_dtor (zval_ptr=0x333a32343a333020) at /root/php-5.6.20/Zend/zend_execute_API.c:424
#1  0x000000000082626b in zend_hash_destroy (ht=0x7fd1a199cfa0)
    at /root/php-5.6.20/Zend/zend_hash.c:548
#2  0x0000000000817e93 in _zval_dtor_func (zvalue=0x7fd1a199d558)
    at /root/php-5.6.20/Zend/zend_variables.c:45
#3  0x0000000000809960 in _zval_dtor (zval_ptr=<value optimized out>)
    at /root/php-5.6.20/Zend/zend_variables.h:35
#4  i_zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/php-5.6.20/Zend/zend_execute.h:79
#5  _zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/php-5.6.20/Zend/zend_execute_API.c:424
#6  0x000000000082626b in zend_hash_destroy (ht=0x7fd1a199d500)
    at /root/php-5.6.20/Zend/zend_hash.c:548
#7  0x0000000000817e93 in _zval_dtor_func (zvalue=0x7fd1a199d2f0)
    at /root/php-5.6.20/Zend/zend_variables.c:45
#8  0x0000000000809960 in _zval_dtor (zval_ptr=<value optimized out>)
    at /root/php-5.6.20/Zend/zend_variables.h:35
#9  i_zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/php-5.6.20/Zend/zend_execute.h:79
#10 _zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/php-5.6.20/Zend/zend_execute_API.c:424
#11 0x000000000082626b in zend_hash_destroy (ht=0x7fd1a1999ec8)
    at /root/php-5.6.20/Zend/zend_hash.c:548
#12 0x000000000083f90c in zend_object_std_dtor (object=0x7fd1a1999cf0)
    at /root/php-5.6.20/Zend/zend_objects.c:44
#13 0x000000000083f999 in zend_objects_free_object_storage (object=0x7fd1a1999cf0)
    at /root/php-5.6.20/Zend/zend_objects.c:137
#14 0x0000000000845758 in zend_objects_store_del_ref_by_handle_ex (handle=6, 
    handlers=<value optimized out>) at /root/php-5.6.20/Zend/zend_objects_API.c:226
#15 0x0000000000845773 in zend_objects_store_del_ref (zobject=0x7fd1a1999b20)
    at /root/php-5.6.20/Zend/zend_objects_API.c:178
#16 0x0000000000809960 in _zval_dtor (zval_ptr=<value optimized out>)
    at /root/php-5.6.20/Zend/zend_variables.h:35
#17 i_zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/php-5.6.20/Zend/zend_execute.h:79
#18 _zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/php-5.6.20/Zend/zend_execute_API.c:424
#19 0x00007fd19531105d in zim_swoole_http_client_on (ht=<value optimized out>, 
    return_value=0x1139400, return_value_ptr=<value optimized out>, this_ptr=0x7ffe7c737590, 
    return_value_used=<value optimized out>)
    at /datas/vmware/swoole-src-1.8.10-stable/swoole_http_client.c:1261
#20 0x00007ffe7c737580 in ?? ()
```

**Comment by Corzcode** [comment]
这边测试5.6.20是会这样的 用php7没问题
