### ISSUE TITLE
最新1.9.10版本使用swoole_unserialize会报错

### ISSUE THREAD

**Issue by zzjin** [swoole/swoole-src#1216]
在代码里面尝试swoole_serialize和swoole_unserialize来在process之间通信,报错.

1. php: 7.0.19
1. swoole: 1.9.10
2. ubuntu 14.04

coredump:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  swoole_unserialize_arr (buffer=0x0, zvalue=zvalue@entry=0x7fb1ede13160, nNumOfElements=<optimized out>) at /home/swoole-src-1.9.10/swoole_serialize.c:455
455	        SBucketType type = *((SBucketType*) buffer);
(gdb) bt
#0  swoole_unserialize_arr (buffer=0x0, zvalue=zvalue@entry=0x7fb1ede13160, nNumOfElements=<optimized out>) at /home/swoole-src-1.9.10/swoole_serialize.c:455
#1  0x00007fb1ed3b443e in php_swoole_unserialize (buffer=<optimized out>, len=<optimized out>, return_value=return_value@entry=0x7fb1ede13160, object_args=<optimized out>) at /home/swoole-src-1.9.10/swoole_serialize.c:1205
#2  0x00007fb1ed3b4596 in zim_swoole_serialize_unpack (execute_data=<optimized out>, return_value=0x7fb1ede13160) at /home/swoole-src-1.9.10/swoole_serialize.c:1245
#3  0x000000000082109b in ZEND_DO_FCALL_SPEC_HANDLER () at /home/php-7.0.19/Zend/zend_vm_execute.h:842
#4  0x00000000007e2f5b in execute_ex (ex=<optimized out>) at /home/php-7.0.19/Zend/zend_vm_execute.h:414
#5  0x0000000000797982 in zend_call_function (fci=fci@entry=0x7fff1215c350, fci_cache=0x7fb1e67b8b48, fci_cache@entry=0x0) at /home/php-7.0.19/Zend/zend_execute_API.c:867
#6  0x0000000000797ec8 in call_user_function_ex (function_table=<optimized out>, object=object@entry=0x0, function_name=<optimized out>, retval_ptr=retval_ptr@entry=0x7fff1215c3c0, param_count=param_count@entry=1,
    params=params@entry=0x7fff1215c3d0, no_separation=no_separation@entry=0, symbol_table=symbol_table@entry=0x0) at /home/php-7.0.19/Zend/zend_execute_API.c:675
#7  0x00007fb1ed3aa90c in sw_call_user_function_ex (ymbol_table=0x0, no_separation=0, params=<synthetic pointer>, param_count=1, retval_ptr_ptr=<synthetic pointer>, function_name=<optimized out>, object_pp=0x0,
    function_table=<optimized out>) at /home/swoole-src-1.9.10/php7_wrapper.h:253
#8  php_swoole_event_onRead (reactor=<optimized out>, event=0x7fff1215c590) at /home/swoole-src-1.9.10/swoole_event.c:59
#9  0x00007fb1ed3d6abf in swReactorEpoll_wait (reactor=0x264a3a0, timeo=<optimized out>) at /home/swoole-src-1.9.10/src/reactor/ReactorEpoll.c:260
#10 0x00007fb1ed3aaaff in php_swoole_event_wait () at /home/swoole-src-1.9.10/swoole_event.c:191
#11 0x0000000000797a04 in zend_call_function (fci=fci@entry=0x7fff1215c700, fci_cache=0x7fff1215c630, fci_cache@entry=0x0) at /home/php-7.0.19/Zend/zend_execute_API.c:887
#12 0x0000000000797ec8 in call_user_function_ex (function_table=<optimized out>, object=object@entry=0x0, function_name=<optimized out>, retval_ptr=retval_ptr@entry=0x7fff1215c790, param_count=<optimized out>, params=<optimized out>,
    no_separation=no_separation@entry=1, symbol_table=symbol_table@entry=0x0) at /home/php-7.0.19/Zend/zend_execute_API.c:675
#13 0x0000000000797ef9 in call_user_function (function_table=<optimized out>, object=object@entry=0x0, function_name=<optimized out>, retval_ptr=retval_ptr@entry=0x7fff1215c790, param_count=<optimized out>, params=<optimized out>)
    at /home/php-7.0.19/Zend/zend_execute_API.c:657
#14 0x00000000006acad8 in user_shutdown_function_call (zv=<optimized out>) at /home/php-7.0.19/ext/standard/basic_functions.c:4921
#15 0x00000000007b717b in zend_hash_apply (ht=0x7fb1ede55d90, apply_func=apply_func@entry=0x6aca10 <user_shutdown_function_call>) at /home/php-7.0.19/Zend/zend_hash.c:1538
#16 0x00000000006afbe6 in php_call_shutdown_functions () at /home/php-7.0.19/ext/standard/basic_functions.c:5005
#17 0x00000000007483f5 in php_request_shutdown (dummy=dummy@entry=0x0) at /home/php-7.0.19/main/main.c:1773
#18 0x000000000082d85a in do_cli (argc=3, argv=0x24552a0) at /home/php-7.0.19/sapi/cli/php_cli.c:1144
#19 0x000000000043c470 in main (argc=3, argv=0x24552a0) at /home/php-7.0.19/sapi/cli/php_cli.c:1347
```

应该是在unpack特定的array的时候出现的问题,具体是哪个array,还需要进一步的调试
@GXhua

**Comment by GXhua** [comment]
fixed
