### ISSUE TITLE
swoole 1.9.4 WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by findsomething** [swoole/swoole-src#1254]
## 问题
结合phalcon 全局捕捉 exception 时有概率出现该错误

## gdb php core
```
#0  0x000055d1b883c101 in _emalloc ()
#1  0x000055d1b8891748 in zend_objects_new ()
#2  0x000055d1b887b3c5 in ?? ()
#3  0x000055d1b885ff4b in _object_and_properties_init ()
#4  0x000055d1b88e07ca in ?? ()
#5  0x000055d1b8899cbb in execute_ex ()
#6  0x000055d1b884e1f9 in dtrace_execute_ex ()
#7  0x000055d1b88d73b0 in ?? ()
#8  0x000055d1b8899cbb in execute_ex ()
#9  0x000055d1b884e1f9 in dtrace_execute_ex ()
#10 0x000055d1b88d73b0 in ?? ()
#11 0x000055d1b8899cbb in execute_ex ()
#12 0x000055d1b884e1f9 in dtrace_execute_ex ()
#13 0x000055d1b88d73b0 in ?? ()
#14 0x000055d1b8899cbb in execute_ex ()
#15 0x000055d1b884e1f9 in dtrace_execute_ex ()
#16 0x000055d1b88d73b0 in ?? ()
#17 0x000055d1b8899cbb in execute_ex ()
#18 0x000055d1b884e1f9 in dtrace_execute_ex ()
#19 0x000055d1b88d73b0 in ?? ()
#20 0x000055d1b8899cbb in execute_ex ()
#21 0x000055d1b884e1f9 in dtrace_execute_ex ()
#22 0x000055d1b88d73b0 in ?? ()
#23 0x000055d1b8899cbb in execute_ex ()
#24 0x000055d1b884e1f9 in dtrace_execute_ex ()
#25 0x000055d1b884fb33 in zend_call_function ()
#26 0x00007f95c0436fcd in ?? () from /usr/lib/php/20151012/phalcon.so
#27 0x000055d1b884e2fb in dtrace_execute_internal ()
#28 0x000055d1b88d67d7 in ?? ()
#29 0x000055d1b8899cbb in execute_ex ()
#30 0x000055d1b884e1f9 in dtrace_execute_ex ()
#31 0x000055d1b884fb33 in zend_call_function ()
#32 0x00007f95c012dbfe in ?? () from /usr/lib/php/20151012/phalcon.so
#33 0x00007f95c043575d in ?? () from /usr/lib/php/20151012/phalcon.so
#34 0x000055d1b884e2fb in dtrace_execute_internal ()
#35 0x000055d1b88d76e4 in ?? ()
#36 0x000055d1b8899cbb in execute_ex ()
#37 0x000055d1b884e1f9 in dtrace_execute_ex ()
#38 0x000055d1b88d73b0 in ?? ()
#39 0x000055d1b8899cbb in execute_ex ()
#40 0x000055d1b884e1f9 in dtrace_execute_ex ()
#41 0x000055d1b884fb33 in zend_call_function ()
#42 0x000055d1b8850058 in call_user_function_ex ()
#43 0x00007f95bd214abd in sw_call_user_function_ex (ymbol_table=0x0, no_separation=0, 
    params=<synthetic pointer>, param_count=2, retval_ptr_ptr=<synthetic pointer>, 
    function_name=<optimized out>, object_pp=0x0, function_table=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /tmp/swoole-src-1.9.4/php7_wrapper.h:236
#44 http_onReceive (serv=<optimized out>, req=<optimized out>) at /tmp/swoole-src-1.9.4/swoole_http_server.c:1033
#45 0x00007f95bd23f6a9 in swWorker_onTask (factory=factory@entry=0x55d1b9432800, task=task@entry=0x7ffe989cc7d0)
    at /tmp/swoole-src-1.9.4/src/network/Worker.c:203
#46 0x00007f95bd23faa9 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7ffe989ce860)
    at /tmp/swoole-src-1.9.4/src/network/Worker.c:560
#47 0x00007f95bd2301ff in swReactorEpoll_wait (reactor=0x55d1b9476220, timeo=<optimized out>)
    at /tmp/swoole-src-1.9.4/src/reactor/ReactorEpoll.c:258
#48 0x00007f95bd24073f in swWorker_loop (factory=factory@entry=0x55d1b9432800, worker_id=worker_id@entry=9)
    at /tmp/swoole-src-1.9.4/src/network/Worker.c:518
#49 0x00007f95bd23d77f in swManager_spawn_worker (factory=0x55d1b9432800, worker_id=9)
    at /tmp/swoole-src-1.9.4/src/network/Manager.c:644
#50 0x00007f95bd23dd0f in swManager_start (factory=factory@entry=0x55d1b9432800)
    at /tmp/swoole-src-1.9.4/src/network/Manager.c:133
#51 0x00007f95bd22cc12 in swFactoryProcess_start (factory=0x55d1b9432800)
    at /tmp/swoole-src-1.9.4/src/factory/FactoryProcess.c:86
#52 0x00007f95bd234013 in swServer_start (serv=serv@entry=0x55d1b94323d0)
    at /tmp/swoole-src-1.9.4/src/network/Server.c:696
#53 0x00007f95bd210dba in zim_swoole_http_server_start (execute_data=0x7f95ca413810, return_value=0x7f95ca413800)
    at /tmp/swoole-src-1.9.4/swoole_http_server.c:1440
#54 0x000055d1b884e2fb in dtrace_execute_internal ()
#55 0x000055d1b88d76e4 in ?? ()
#56 0x000055d1b8899cbb in execute_ex ()
#57 0x000055d1b884e1f9 in dtrace_execute_ex ()
#58 0x000055d1b88d73b0 in ?? ()
#59 0x000055d1b8899cbb in execute_ex ()
#60 0x000055d1b884e1f9 in dtrace_execute_ex ()
#61 0x000055d1b88d73b0 in ?? ()
#62 0x000055d1b8899cbb in execute_ex ()
#63 0x000055d1b884e1f9 in dtrace_execute_ex ()
#64 0x000055d1b884fb33 in zend_call_function ()
#65 0x000055d1b87a48bd in zif_call_user_func_array ()
#66 0x000055d1b884e2fb in dtrace_execute_internal ()
#67 0x000055d1b88d76e4 in ?? ()
#68 0x000055d1b8899cbb in execute_ex ()
#69 0x000055d1b884e1f9 in dtrace_execute_ex ()
#70 0x000055d1b88d73b0 in ?? ()
#71 0x000055d1b8899cbb in execute_ex ()
#72 0x000055d1b884e1f9 in dtrace_execute_ex ()
#73 0x000055d1b88e308f in zend_execute ()
#74 0x000055d1b885d834 in zend_execute_scripts ()
#75 0x000055d1b8801528 in php_execute_script ()
#76 0x000055d1b88e4c69 in ?? ()
#77 0x000055d1b86f0a90 in main ()
```

## 环境
php --ri swoole 

```
swoole

swoole support => enabled
Version => 1.9.4
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608
```

php -v
```
PHP 7.0.7-4+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

uname -a
```
Linux local-5 4.2.0-37-generic #43~14.04.1-Ubuntu SMP Wed May 18 17:25:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by matyhtf** [comment]
请尝试使用高版本的 1.9.x
