### ISSUE TITLE
swoole_http_client 导致 worker 段错误退出

### ISSUE THREAD

**Issue by mangowong** [swoole/swoole-src#1357]
1、业务中使用 异步 http client访问外部接口，高并发时外部接口响应较慢，从而而产生较多的http client对象实例，导致worker段错误。

以下代码可模拟此场景，重现本问题。
```php
$serv = new Swoole\Http\Server("127.0.0.1", 9503);
$serv->set([
    'worker_num' => 1,
]);
$serv->on('Request', function ($request, $response) {
    $i = 0;
    $arr = [];
    while (true) {
        $client = new \swoole_http_client('127.0.0.1', 9501); //注释此行代码后问题消失 
        $client2 = new swoole_redis();
        $client3 = new SplStack();
        $client4 = new swoole_mysql();
        $arr[] = $client;
        $arr[] = $client2;
        $arr[] = $client3;
        $arr[] = $client4;
        $i++;
        if ($i > 1000000) {
            break;
        }
    }
    $response->end('hello');
});

$serv->start();
```

重现脚本 bt信息
```
#0  zend_mm_alloc_pages (heap=heap@entry=0x7fb592200040, pages_count=pages_count@entry=1) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_alloc.c:857
#1  0x0000000000443574 in zend_mm_alloc_small_slow (heap=0x7fb592200040, bin_num=13) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_alloc.c:1202
#2  0x0000000000889808 in zend_objects_new (ce=ce@entry=0x1851ce0) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_objects.c:171
#3  0x00000000008560a1 in _object_and_properties_init (arg=arg@entry=0x7fb592213280, class_type=class_type@entry=0x1851ce0, properties=properties@entry=0x0) at /root/ln
#4  0x0000000000856167 in _object_init_ex (arg=arg@entry=0x7fb592213280, class_type=class_type@entry=0x1851ce0) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_API.c:1310
#5  0x00000000008e6dbf in ZEND_NEW_SPEC_CONST_HANDLER () at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:3217
#6  0x000000000089875b in execute_ex (ex=<optimized out>) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:429
#7  0x0000000000844641 in zend_call_function (fci=fci@entry=0x7ffe5e405800, fci_cache=0x7fb592202780) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_execute_API.c:855
#8  0x00007fb58b9f650d in sw_call_user_function_fast (params=<synthetic pointer>, param_count=2, retval_ptr_ptr=<synthetic pointer>, fci_cache=<optimized out>, function
#9  http_onReceive (serv=<optimized out>, req=0x7ffe5e405a10) at /root/swoole-src/swoole_http_server.c:1130
#10 0x00007fb58ba267db in swWorker_onTask (factory=factory@entry=0x186df40, task=task@entry=0x7ffe5e405a10) at /root/swoole-src/src/network/Worker.c:188
#11 0x00007fb58ba268c1 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7ffe5e407a80) at /root/swoole-src/src/network/Worker.c:670
#12 0x00007fb58ba158cc in swReactorEpoll_wait (reactor=0x18a2150, timeo=<optimized out>) at /root/swoole-src/src/reactor/ReactorEpoll.c:250
#13 0x00007fb58ba26da3 in swWorker_loop (factory=factory@entry=0x186df40, worker_id=worker_id@entry=0) at /root/swoole-src/src/network/Worker.c:628
#14 0x00007fb58ba2436c in swManager_spawn_worker (factory=0x186df40, worker_id=0) at /root/swoole-src/src/network/Manager.c:437
#15 0x00007fb58ba249dc in swManager_start (factory=factory@entry=0x186df40) at /root/swoole-src/src/network/Manager.c:145
#16 0x00007fb58ba12352 in swFactoryProcess_start (factory=0x186df40) at /root/swoole-src/src/factory/FactoryProcess.c:86
#17 0x00007fb58ba19c03 in swServer_start (serv=serv@entry=0x186db10) at /root/swoole-src/src/network/Server.c:692
#18 0x00007fb58b9f27f5 in zim_swoole_http_server_start (execute_data=0x7fb592213100, return_value=0x7ffe5e407ca0) at /root/swoole-src/swoole_http_server.c:1578
#19 0x00000000008e99b6 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:970
#20 0x000000000089875b in execute_ex (ex=<optimized out>) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:429
#21 0x00000000008eb704 in zend_execute (op_array=0x7fb592281000, op_array@entry=0x7fb5922883c0, return_value=return_value@entry=0x7fb592213030) at /root/lnmp1.3-full/sr
#22 0x0000000000853a14 in zend_execute_scripts (type=type@entry=8, retval=0x7fb592213030, retval@entry=0x0, file_count=file_count@entry=3) at /root/lnmp1.3-full/src/php
#23 0x00000000007f4b40 in php_execute_script (primary_file=primary_file@entry=0x7ffe5e40a0c0) at /root/lnmp1.3-full/src/php-7.1.9/main/main.c:2552
#24 0x00000000008ed89f in do_cli (argc=2, argv=0x165ef40) at /root/lnmp1.3-full/src/php-7.1.9/sapi/cli/php_cli.c:993
#25 0x00000000004489f0 in main (argc=2, argv=0x165ef40) at /root/lnmp1.3-full/src/php-7.1.9/sapi/cli/php_cli.c:1381
```
业务 bt 信息
```
#0  __memset_sse2 () at ../sysdeps/x86_64/memset.S:873
#1  0x00007fc8fd7d3f86 in swoole_set_property (object=<optimized out>, property_id=property_id@entry=0, ptr=<optimized out>) at /root/swoole-src/swoole.c:692
#2  0x00007fc8fd7fcb3c in zim_swoole_http_client___construct (execute_data=0x7fc904014a70, return_value=0x7ffef727e8f0) at /root/swoole-src/swoole_http_client.c:1409
#3  0x00000000008e99b6 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:970
#4  0x000000000089875b in execute_ex (ex=<optimized out>) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:429
#5  0x0000000000844641 in zend_call_function (fci=fci@entry=0x7ffef727eaa0, fci_cache=0x7fc8fca1d550) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_execute_API.c:855
#6  0x00007fc8fd7f650d in sw_call_user_function_fast (params=<synthetic pointer>, param_count=2, retval_ptr_ptr=<synthetic pointer>, fci_cache=<optimized out>,
    function_name=<optimized out>) at /root/swoole-src/php7_wrapper.h:301
#7  http_onReceive (serv=<optimized out>, req=0x7ffef727ecb0) at /root/swoole-src/swoole_http_server.c:1130
#8  0x00007fc8fd8267db in swWorker_onTask (factory=factory@entry=0x249c560, task=task@entry=0x7ffef727ecb0) at /root/swoole-src/src/network/Worker.c:188
#9  0x00007fc8fd8268c1 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7ffef7280d20) at /root/swoole-src/src/network/Worker.c:670
#10 0x00007fc8fd8158cc in swReactorEpoll_wait (reactor=0x24a24e0, timeo=<optimized out>) at /root/swoole-src/src/reactor/ReactorEpoll.c:250
#11 0x00007fc8fd826da3 in swWorker_loop (factory=factory@entry=0x249c560, worker_id=worker_id@entry=0) at /root/swoole-src/src/network/Worker.c:628
#12 0x00007fc8fd82436c in swManager_spawn_worker (factory=0x249c560, worker_id=0) at /root/swoole-src/src/network/Manager.c:437
#13 0x00007fc8fd8249dc in swManager_start (factory=factory@entry=0x249c560) at /root/swoole-src/src/network/Manager.c:145
#14 0x00007fc8fd812352 in swFactoryProcess_start (factory=0x249c560) at /root/swoole-src/src/factory/FactoryProcess.c:86
#15 0x00007fc8fd819c03 in swServer_start (serv=serv@entry=0x249c130) at /root/swoole-src/src/network/Server.c:692
#16 0x00007fc8fd7f27f5 in zim_swoole_http_server_start (execute_data=0x7fc904014700, return_value=0x7ffef7280f40) at /root/swoole-src/swoole_http_server.c:1578
#17 0x00000000008e99b6 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:970
#18 0x000000000089875b in execute_ex (ex=<optimized out>) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:429
#19 0x0000000000844641 in zend_call_function (fci=fci@entry=0x7ffef72810d0, fci_cache=fci_cache@entry=0x7ffef72810a0)
    at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_execute_API.c:855
#20 0x0000000000752fdd in zif_call_user_func_array (execute_data=0x7fc9040141c0, return_value=0x7fc9040141b0)
    at /root/lnmp1.3-full/src/php-7.1.9/ext/standard/basic_functions.c:4860
#21 0x00000000008e8acd in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:876
#22 0x000000000089875b in execute_ex (ex=<optimized out>) at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:429
#23 0x00000000008eb704 in zend_execute (op_array=0x7fc904081000, op_array@entry=0x7fc90412bb60, return_value=return_value@entry=0x7fc9040140d0)
    at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend_vm_execute.h:474
#24 0x0000000000853a14 in zend_execute_scripts (type=type@entry=8, retval=0x7fc9040140d0, retval@entry=0x0, file_count=file_count@entry=3)
    at /root/lnmp1.3-full/src/php-7.1.9/Zend/zend.c:1480
#25 0x00000000007f4b40 in php_execute_script (primary_file=primary_file@entry=0x7ffef7283560) at /root/lnmp1.3-full/src/php-7.1.9/main/main.c:2552
#26 0x00000000008ed89f in do_cli (argc=4, argv=0x2434f40) at /root/lnmp1.3-full/src/php-7.1.9/sapi/cli/php_cli.c:993
#27 0x00000000004489f0 in main (argc=4, argv=0x2434f40) at /root/lnmp1.3-full/src/php-7.1.9/sapi/cli/php_cli.c:1381
```

2. 期望结果
```
 程序内存溢出错误
```

3、实际运行结果
```
 程序段错误
```

4. swoole 版本
```
swoole support => enabled
Version => 1.9.19
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```
5、环境信息
```
GCC : gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
内核：3.10.0-327.el7.x86_64
php : PHP 7.1.9 
openss ： OpenSSL 1.0.2k-fips
```

**Comment by matyhtf** [comment]
感谢反馈，已修复。
