### ISSUE TITLE
FUTEX_WAIT  Resource temporarily unavailable

### ISSUE THREAD

**Issue by zhang-bin** [swoole/swoole-src#1455]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

是线上游戏的聊天服务，人数比较多，可能无限复现

2. What did you expect to see?

玩家正常发送数据

3. What did you see instead?

strace pid之后出现了

stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
write(5, "[2018-01-18 16:32:59 ^15061.250]"..., 118) = 118
futex(0x7f3e2afad1c0, FUTEX_WAKE, 1)    = 1
nanosleep({0, 1000}, NULL)              = 0
futex(0x7f3e2afad1c0, FUTEX_WAIT, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f3e2afad1c0, FUTEX_WAIT, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f3e2afad1c0, FUTEX_WAIT, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)

4. What version of Swoole are you using (`php --ri swoole`)?

1.9.21

5. What is your machine environment used (including version of kernel & php & gcc) ? 
uname -a:   Linux eater_ios_chat 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.1.11
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

6. If you are using ssl, what is your openssl version?
没用

**Comment by zhang-bin** [comment]
补充下，task_max_request 设置了10000

**Comment by matyhtf** [comment]
1. strace 跟踪的是哪个进程？Worker 还是 Task ？
2. 使用 gdb -p 跟踪，并打印调用栈 （bt指令）

**Comment by zhang-bin** [comment]
strace跟踪的是task进程，gdb的话等下次再次出现的时候，我跟踪下

**Comment by zhang-bin** [comment]
这是gdb -p执行的输出

#0  0x00007f44c934342d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f44c933edcb in _L_lock_812 () from /lib64/libpthread.so.0
#2  0x00007f44c933ec98 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f44b9f430f7 in swFactoryProcess_finish (factory=<optimized out>, resp=<optimized out>) at /mysoft/swoole-src-1.9.21/src/factory/FactoryProcess.c:205
#4  0x00007f44b9f47fb2 in swServer_tcp_send (serv=serv@entry=0x55aa9d3e59b0, fd=<optimized out>, data=<optimized out>, length=length@entry=385)
    at /mysoft/swoole-src-1.9.21/src/network/Server.c:964
#5  0x00007f44b9f0c568 in zim_swoole_server_send (execute_data=0x7f44c8614ea0, return_value=0x7fff5b3ef9b0) at /mysoft/swoole-src-1.9.21/swoole_server.c:2293
#6  0x000055aa9bee127c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER ()
#7  0x000055aa9be8f3cb in execute_ex ()
#8  0x000055aa9be37c21 in zend_call_function ()
#9  0x000055aa9bd318af in reflection_method_invoke ()
#10 0x000055aa9bee0dc8 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER ()
#11 0x000055aa9be8f3cb in execute_ex ()
#12 0x000055aa9be37c21 in zend_call_function ()
#13 0x00007f44b9f0a159 in sw_call_user_function_fast (params=0x7fff5b3efda0, param_count=4, retval_ptr_ptr=<synthetic pointer>, fci_cache=<optimized out>, function_name=<optimized out>)
    at /mysoft/swoole-src-1.9.21/php7_wrapper.h:301
#14 php_swoole_onTask (serv=0x55aa9d3e59b0, req=<optimized out>) at /mysoft/swoole-src-1.9.21/swoole_server.c:862
#15 0x00007f44b9f4efb6 in swProcessPool_worker_loop (pool=0x7f44b7fad230, worker=0x7f44b7fd2ed0) at /mysoft/swoole-src-1.9.21/src/network/ProcessPool.c:356
#16 0x00007f44b9f4fa78 in swProcessPool_spawn (worker=0x7f44b7fd2ed0) at /mysoft/swoole-src-1.9.21/src/network/ProcessPool.c:248
#17 0x00007f44b9f4fba1 in swProcessPool_start (pool=0x7f44b7fad230) at /mysoft/swoole-src-1.9.21/src/network/ProcessPool.c:111
#18 0x00007f44b9f54eb5 in swManager_start (factory=factory@entry=0x55aa9d3e5de0) at /mysoft/swoole-src-1.9.21/src/network/Manager.c:137
#19 0x00007f44b9f42f52 in swFactoryProcess_start (factory=0x55aa9d3e5de0) at /mysoft/swoole-src-1.9.21/src/factory/FactoryProcess.c:86
#20 0x00007f44b9f4a523 in swServer_start (serv=serv@entry=0x55aa9d3e59b0) at /mysoft/swoole-src-1.9.21/src/network/Server.c:692
#21 0x00007f44b9f0c346 in zim_swoole_server_start (execute_data=<optimized out>, return_value=0x7fff5b3f2180) at /mysoft/swoole-src-1.9.21/swoole_server.c:2181
#22 0x000055aa9bee127c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER ()
#23 0x000055aa9be8f3cb in execute_ex ()
#24 0x000055aa9bee3084 in zend_execute ()
#25 0x000055aa9be479f3 in zend_execute_scripts ()
#26 0x000055aa9bde4d78 in php_execute_script ()
#27 0x000055aa9bee5328 in do_cli ()
#28 0x000055aa9bc79a0f in main ()
