### ISSUE TITLE
Swoole + RabbitMQ

### ISSUE THREAD

**Issue by rvaliev** [swoole/swoole-src#1516]
Is there any option/guide how to implement Swoole with RabbitMQ? Thanks

**Comment by huangzhhui** [comment]
https://github.com/swoole/php-amqplib

**Comment by vbezruchkin** [comment]
Thanks @huangzhhui

**Comment by rvaliev** [comment]
@vbezruchkin, @huangzhhui  have you got it working well? Because I've tried t using the code examples from https://github.com/swoole/php-amqplib/tree/master/demo. But got an error during amqp_publisher.php execution.

Here is the code:
**swoole_socket_server.php**
```
 $server = new \swoole_websocket_server("0.0.0.0", 5673, SWOOLE_BASE);

        $server->on('open', function (\swoole_websocket_server $server, $request) {
            echo "server: handshake success with fd{$request->fd}\n";
        });

        $server->on('message', function (\swoole_websocket_server $server, $frame) {
            echo "receive from {$frame->fd}:{$frame->data},opcode:{$frame->opcode},fin:{$frame->finish}\n";
            $server->push($frame->fd, "This message is from swoole websocket server.");
        });

        $server->on('close', function ($ser, $fd) {
            echo "client {$fd} closed\n";
        });

        $server->start();
```

**amqp_consumer_swoole.php**
```
go(function () {
    $exchange = 'router';
    $queue = 'queue2';
    $consumerTag = 'consumer';
    
    $connection = new AMQPSwooleConnection('127.0.0.1', 5673, 'guest', 'guest', '/');
    $channel = $connection->channel();
    
    $channel->queue_declare($queue, false, true, false, false);
    $channel->exchange_declare($exchange, 'direct', false, true, false);

    $channel->queue_bind($queue, $exchange);

    /**
     * @param \PhpAmqpLib\Message\AMQPMessage $message
     */
    function process_message($message)
    {
        echo "\n--------\n";
        echo $message->body;
        echo "\n--------\n";

        $message->delivery_info['channel']->basic_ack($message->delivery_info['delivery_tag']);

        // Send a message with the string "quit" to cancel the consumer.
        if ($message->body === 'quit')
        {
            $message->delivery_info['channel']->basic_cancel($message->delivery_info['consumer_tag']);
        }
    }

    $channel->basic_consume($queue, $consumerTag, false, false, false, false, 'process_message');

    while (count($channel->callbacks))
    {
        $channel->wait();
    }
});
```

**amqp_publisher.php**
```
$exchange = 'router';
$queue = 'queue2';

$connection = new AMQPStreamConnection('127.0.0.1', 5673, 'guest', 'guest', '/');
$channel = $connection->channel();
$channel->queue_declare($queue, false, true, false, false);

$channel->exchange_declare($exchange, 'direct', false, true, false);
$channel->queue_bind($queue, $exchange);

$messageBody = "Hoi there";
$message = new AMQPMessage($messageBody, array('content_type' => 'text/plain', 'delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT));
$channel->basic_publish($message, $exchange);

$channel->close();
$connection->close();

```

So after swoole_socket_server.php and amqp_consumer_swoole.php are running in terminal I'm trying to execute amqp_publisher.php by:
`php amqp_publisher.php`

But got this error:
```
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPTimeoutException: The connection timed out after 3 sec while awaiting incoming data in /home/vagrant/Sites/Test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:136
Stack trace:
#0 /home/vagrant/Sites/Test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(152): PhpAmqpLib\Wire\AMQPReader->wait()
#1 /home/vagrant/Sites/Test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#2 /home/vagrant/Sites/Test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(522): PhpAmqpLib\Wire\AMQPReader->read(7)
#3 /home/vagrant/Sites/Test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(570): PhpAmqpLib\Connection\AbstractConnection->wait_frame(3)
#4 /home/vagrant/Sites/Test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(225): PhpAmqpLib\Connection\AbstractConnection->wait_channel(0, 3)
#5 /home/vagrant/Sites/Test/vendor/php-amqplib/php-amqpl in /home/vagrant/Sites/Test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php on line 136

```

**Comment by matyhtf** [comment]
Duplicate question. See issue #1517
