### ISSUE TITLE
zim_swoole_redis_coro_hSetNx core 

### ISSUE THREAD

**Issue by hello2t** [swoole/swoole-src#1592]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
coroutine redis hSetNx 

2. What did you expect to see?
done well 

3. What did you see instead?
core dump

4. What version of Swoole are you using (`php --ri swoole`)?
swoole  2.1.3 tag

5. What is your machine environment used (including version of kernel & php & gcc) ? 
php7.1.1 
gcc version 4.4.6 20110731 (Red Hat 4.4.6-4) (GCC)

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/services/php7.1.1/bin/php http_server.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f692f673ede in zim_swoole_redis_coro_hSetNx (execute_data=0x7f6924a726f0, return_value=0x7f6924a726b0)
    at /usr/local/services/swoole-src-2.1.3/swoole_redis_coro.c:1746
1746	/usr/local/services/swoole-src-2.1.3/swoole_redis_coro.c: No such file or directory.
(gdb) bt
#0  0x00007f692f673ede in zim_swoole_redis_coro_hSetNx (execute_data=0x7f6924a726f0, return_value=0x7f6924a726b0)
    at /usr/local/services/swoole-src-2.1.3/swoole_redis_coro.c:1746
#1  0x00000000008700b5 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER (execute_data=0x7f6924a72630) at /usr/local/services/php-7.1.1/Zend/zend_vm_execute.h:1097
#2  0x000000000084f0e8 in execute_ex (ex=<optimized out>) at /usr/local/services/php-7.1.1/Zend/zend_vm_execute.h:432
#3  0x00007f692f62f0b7 in sw_coro_resume (sw_current_context=<optimized out>, retval=0x7f6926700860, coro_retval=<optimized out>)
    at /usr/local/services/swoole-src-2.1.3/swoole_coroutine.c:506
#4  0x00007f692f669e0b in swoole_redis_coro_resume (data=0x7f6926700860) at /usr/local/services/swoole-src-2.1.3/swoole_redis_coro.c:4059
#5  0x00007f692f3f067a in __redisRunCallback (reply=0x18e4a40, cb=0x7fff771c8260, ac=0x18cadb0) at async.c:269
#6  redisProcessCallbacks (ac=0x18cadb0) at async.c:469
#7  0x00007f692f68ec77 in swoole_redis_coro_onRead (reactor=<optimized out>, event=<optimized out>) at /usr/local/services/swoole-src-2.1.3/swoole_redis_coro.c:4396
#8  0x00007f692f6a3aef in swReactorEpoll_wait (reactor=0x17566d0, timeo=<optimized out>) at /usr/local/services/swoole-src-2.1.3/src/reactor/ReactorEpoll.c:255
#9  0x00007f692f6b6229 in swWorker_loop (factory=<optimized out>, worker_id=<optimized out>) at /usr/local/services/swoole-src-2.1.3/src/network/Worker.c:782
#10 0x00007f692f6b32f3 in swManager_spawn_worker (factory=0x1755890, worker_id=4) at /usr/local/services/swoole-src-2.1.3/src/network/Manager.c:507
#11 0x00007f692f6b3932 in swManager_loop (factory=0x1755890) at /usr/local/services/swoole-src-2.1.3/src/network/Manager.c:386
#12 swManager_start (factory=0x1755890) at /usr/local/services/swoole-src-2.1.3/src/network/Manager.c:178
#13 0x00007f692f6a04c1 in swFactoryProcess_start (factory=0x1755890) at /usr/local/services/swoole-src-2.1.3/src/factory/FactoryProcess.c:86
#14 0x00007f692f6a7baf in swServer_start (serv=0x1755400) at /usr/local/services/swoole-src-2.1.3/src/network/Server.c:755
#15 0x00007f692f643d84 in zim_swoole_http_server_start (execute_data=0x7f6939a131a0, return_value=0x7fff771c8530)
    at /usr/local/services/swoole-src-2.1.3/swoole_http_server.c:1669
#16 0x00000000008705b0 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (execute_data=0x7f6939a13030) at /usr/local/services/php-7.1.1/Zend/zend_vm_execute.h:970
#17 0x000000000084f0e8 in execute_ex (ex=<optimized out>) at /usr/local/services/php-7.1.1/Zend/zend_vm_execute.h:432
#18 0x000000000089ab20 in zend_execute (op_array=0x7f6939a81000, return_value=<optimized out>) at /usr/local/services/php-7.1.1/Zend/zend_vm_execute.h:474
#19 0x00000000007f3b23 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/local/services/php-7.1.1/Zend/zend.c:1474
#20 0x0000000000794370 in php_execute_script (primary_file=0x7fff771cba10) at /usr/local/services/php-7.1.1/main/main.c:2537
#21 0x000000000089de7a in do_cli (argc=2, argv=0x1601c00) at /usr/local/services/php-7.1.1/sapi/cli/php_cli.c:993
#22 0x000000000089e67a in main (argc=2, argv=0x1601c00) at /usr/local/services/php-7.1.1/sapi/cli/php_cli.c:1381
```

**Comment by shiguangqi** [comment]
fixed
