### ISSUE TITLE
websockt使用ssl不稳定，运行几天主进程就会挂掉

### ISSUE THREAD

**Issue by egocheer** [swoole/swoole-src#1608]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
使用swoole_websocket_server监听9999端口。
```
	$this->server = new swoole_websocket_server($host, $port, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
			$this->server->set(array(
				'ssl_cert_file' => config('ssl_cert_file'),
				'ssl_key_file'  => config('ssl_key_file'),
				'log_file'      => '/var/log/swooleWebsocket.log',
			));
```

2. What did you expect to see?
程序正常运行不挂掉

3. What did you see instead?
运行一段时间就会自己挂掉

4. What version of Swoole are you using (`php --ri swoole`)?

swoole support => enabled
Version => 1.8.7
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
php：
PHP 7.0.7 (cli) (built: Jul  1 2016 19:08:42) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

操作系统
CentOS release 6.7

内核版本
Linux bj-web01 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

gcc
使用内建 specs。
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 

6. If you are using ssl, what is your openssl version?
OpenSSL 1.0.1e-fips 11 Feb 2013

core dump 信息
Program terminated with signal 11, Segmentation fault.

```
(gdb) bt
#0  0x00000031f582d9a9 in ?? () from /usr/lib64/libssl.so.10
#1  0x00000031f582da9f in ssl3_setup_write_buffer () from /usr/lib64/libssl.so.10
#2  0x00000031f582dc10 in ssl3_setup_buffers () from /usr/lib64/libssl.so.10
#3  0x00000031f582ff8b in ssl23_get_client_hello () from /usr/lib64/libssl.so.10
#4  0x00000031f5830433 in ssl23_accept () from /usr/lib64/libssl.so.10
#5  0x00007f420ea6dca2 in swSSL_accept (conn=0x7f4200d883e8) at /home/zhengshaohong/swoole-src-1.8.7-stable/src/protocol/SSL.c:317
#6  0x00007f420ea64aed in swReactorThread_verify_ssl_state (reactor=0x7f420dfe9cb8, event=<value optimized out>) at /home/zhengshaohong/swoole-src-1.8.7-stable/src/network/ReactorThread.c:81
#7  swReactorThread_onRead (reactor=0x7f420dfe9cb8, event=<value optimized out>) at /home/zhengshaohong/swoole-src-1.8.7-stable/src/network/ReactorThread.c:784
#8  0x00007f420ea5a561 in swReactorEpoll_wait (reactor=0x7f420dfe9cb8, timeo=<value optimized out>) at /home/zhengshaohong/swoole-src-1.8.7-stable/src/reactor/ReactorEpoll.c:258
#9  0x00007f420ea63b30 in swReactorThread_loop_stream (param=<value optimized out>) at /home/zhengshaohong/swoole-src-1.8.7-stable/src/network/ReactorThread.c:1147
#10 0x0000003dc4607a51 in start_thread () from /lib64/libpthread.so.0
#11 0x0000003dc42e896d in clone () from /lib64/libc.so.6
```

**Comment by twose** [comment]
你用的版本也太老了吧...
