### ISSUE TITLE
WebSocket Server 使用连接迭代器导致段错误

### ISSUE THREAD

**Issue by Git-XiaoQin** [swoole/swoole-src#1674]
```bash
[New LWP 2634]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php Websocket.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f072b26a2a4 in zim_swoole_connection_iterator_count (execute_data=0x7f072b880240, return_value=0x561719d84e00)
    at /home/xiaoqin/php-7.2.6/ext/swoole/swoole_server.c:4137
4137	        RETURN_LONG(i->serv->stats->connection_num);
(gdb) bt
#0  0x00007f072b26a2a4 in zim_swoole_connection_iterator_count (execute_data=0x7f072b880240, return_value=0x561719d84e00)
    at /home/xiaoqin/php-7.2.6/ext/swoole/swoole_server.c:4137
#1  0x0000561717f301b2 in zend_call_function (fci=fci@entry=0x561719d84d20, fci_cache=0x561719d84c00, fci_cache@entry=0x0)
    at /home/xiaoqin/php-7.2.6/Zend/zend_execute_API.c:833
#2  0x0000561717f5f336 in zend_call_method (object=object@entry=0x7f072b8801c0, obj_ce=obj_ce@entry=0x0,
    fn_proxy=fn_proxy@entry=0x0, function_name=function_name@entry=0x5617185ba07f "count",
    function_name_len=function_name_len@entry=5, retval_ptr=retval_ptr@entry=0x561719d84e00, param_count=0, arg1=0x0,
    arg2=0x0) at /home/xiaoqin/php-7.2.6/Zend/zend_interfaces.c:60
#3  0x0000561717fc5992 in ZEND_COUNT_SPEC_VAR_UNUSED_HANDLER () at /home/xiaoqin/php-7.2.6/Zend/zend_vm_execute.h:21766
#4  0x0000561717febff8 in execute_ex (ex=0x7f072b880240) at /home/xiaoqin/php-7.2.6/Zend/zend_vm_execute.h:61165
#5  0x00007f072b277d57 in sw_coro_create () from /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
#6  0x00007f072b2772cc in fn_coro_create(void*) () from /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
#7  0x00007f072b2e0fab in CoRoutineFunc(stCoRoutine_t*, void*) ()
   from /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
#8  0x0000000000000000 in ?? ()
```

**Comment by Git-XiaoQin** [comment]
重新git pull 已解决！

**Comment by matyhtf** [comment]
beta 版本还有问题，今天会发一下 4.0.0-rc1 版本
