### ISSUE TITLE
协程socket的recv()方法设置timeout出现段错误

### ISSUE THREAD

**Issue by keilestone** [swoole/swoole-src#1694]
gdb
```
#0  0x0000555d1b394dfb in zend_update_property ()
#1  0x0000555d1b3950a8 in zend_update_property_long ()
#2  0x00007fcd875589e1 in socket_onTimeout (timer=<optimized out>, tnode=<optimized out>) at /tmp/pear/temp/swoole/swoole_socket_coro.c:461
#3  0x00007fcd875b1631 in swTimer_select (timer=timer@entry=0x7fcd87880d20 <SwooleG>) at /tmp/pear/temp/swoole/src/network/Timer.c:214
#4  0x00007fcd8759a2e0 in swReactor_onTimeout_and_Finish (reactor=reactor@entry=0x555d1bc39f80) at /tmp/pear/temp/swoole/src/reactor/ReactorBase.c:156
#5  0x00007fcd8759a319 in swReactor_onTimeout (reactor=0x555d1bc39f80) at /tmp/pear/temp/swoole/src/reactor/ReactorBase.c:208
#6  0x00007fcd8759c320 in swReactorEpoll_wait (reactor=0x555d1bc39f80, timeo=<optimized out>) at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:240
#7  0x00007fcd875570e2 in php_swoole_event_wait () at /tmp/pear/temp/swoole/swoole_event.c:254
#8  0x0000555d1b37b4cf in zend_call_function ()
#9  0x0000555d1b37b979 in call_user_function_ex ()
#10 0x0000555d1b37b9ad in call_user_function ()
#11 0x0000555d1b2c6e40 in ?? ()
#12 0x0000555d1b39c81c in zend_hash_apply ()
#13 0x0000555d1b2ca2e6 in php_call_shutdown_functions ()
#14 0x0000555d1b328935 in php_request_shutdown ()
#15 0x0000555d1b4208b9 in ?? ()
#16 0x0000555d1b20c7b4 in main ()
```

swoole版本
```
swoole

swoole support => enabled
Version => 2.2.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
debug => enabled
```
php版本
```
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by keilestone** [comment]
valgrind
```
START:
ACCEPT:==225252== Invalid read of size 8
==225252==    at 0x374DFB: zend_update_property (in /usr/bin/php7.0)
==225252==    by 0x3750A7: zend_update_property_long (in /usr/bin/php7.0)
==225252==    by 0x10C009E0: socket_onTimeout (swoole_socket_coro.c:461)
==225252==    by 0x10C59630: swTimer_select (Timer.c:214)
==225252==    by 0x10C422DF: swReactor_onTimeout_and_Finish (ReactorBase.c:156)
==225252==    by 0x10C42318: swReactor_onTimeout (ReactorBase.c:208)
==225252==    by 0x10C4431F: swReactorEpoll_wait (ReactorEpoll.c:240)
==225252==    by 0x10BFF0E1: php_swoole_event_wait (swoole_event.c:254)
==225252==    by 0x35B4CE: zend_call_function (in /usr/bin/php7.0)
==225252==    by 0x35B978: call_user_function_ex (in /usr/bin/php7.0)
==225252==    by 0x35B9AC: call_user_function (in /usr/bin/php7.0)
==225252==    by 0x2A6E3F: ??? (in /usr/bin/php7.0)
==225252==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
==225252== 
==225252== 
==225252== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==225252==  Access not within mapped region at address 0x18
==225252==    at 0x374DFB: zend_update_property (in /usr/bin/php7.0)
==225252==    by 0x3750A7: zend_update_property_long (in /usr/bin/php7.0)
==225252==    by 0x10C009E0: socket_onTimeout (swoole_socket_coro.c:461)
==225252==    by 0x10C59630: swTimer_select (Timer.c:214)
==225252==    by 0x10C422DF: swReactor_onTimeout_and_Finish (ReactorBase.c:156)
==225252==    by 0x10C42318: swReactor_onTimeout (ReactorBase.c:208)
==225252==    by 0x10C4431F: swReactorEpoll_wait (ReactorEpoll.c:240)
==225252==    by 0x10BFF0E1: php_swoole_event_wait (swoole_event.c:254)
==225252==    by 0x35B4CE: zend_call_function (in /usr/bin/php7.0)
==225252==    by 0x35B978: call_user_function_ex (in /usr/bin/php7.0)
==225252==    by 0x35B9AC: call_user_function (in /usr/bin/php7.0)
==225252==    by 0x2A6E3F: ??? (in /usr/bin/php7.0)
==225252==  If you believe this happened as a result of a stack
==225252==  overflow in your program's main thread (unlikely but
==225252==  possible), you can try to increase the size of the
==225252==  main thread stack using the --main-stacksize= flag.
==225252==  The main thread stack size used in this run was 8388608.
==225252== 
==225252== HEAP SUMMARY:
==225252==     in use at exit: 5,207,994 bytes in 21,888 blocks
==225252==   total heap usage: 30,601 allocs, 8,713 frees, 6,461,599 bytes allocated
==225252== 
==225252== LEAK SUMMARY:
==225252==    definitely lost: 32 bytes in 1 blocks
==225252==    indirectly lost: 2,048 bytes in 1 blocks
==225252==      possibly lost: 1,669,966 bytes in 16,793 blocks
==225252==    still reachable: 3,535,948 bytes in 5,093 blocks
==225252==         suppressed: 0 bytes in 0 blocks
==225252== Rerun with --leak-check=full to see details of leaked memory
==225252== 
==225252== For counts of detected and suppressed errors, rerun with: -v
==225252== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by twose** [comment]
@keilestone 跟踪信息很全, 但是能提供简短的PHP复现代码吗

**Comment by keilestone** [comment]
@matyhtf 峰哥 这个测试依旧是报的段错误，重新编译安装 `2.x-lts`以及php版本换成7.2都是这个问题。
gcc版本
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
```
uname
```
Linux xxx 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by matyhtf** [comment]
好的，感谢你的反馈。请问你本地使用官方的单元测试脚本 `recv_timeout.phpt` 是否会出现 core ？另外，是否可以提供一个可稳定重现的 demo

**Comment by keilestone** [comment]
测试的core
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f4ed699c706 in swReactorEpoll_wait (reactor=0x561c5acd35a0, timeo=<optimized out>) at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:284
#2  0x00007f4ed69570e2 in php_swoole_event_wait () at /tmp/pear/temp/swoole/swoole_event.c:254
#3  0x0000561c58baff8d in ?? ()
#4  0x0000561c58ba123b in execute_ex ()
#5  0x0000561c58bf5867 in zend_execute ()
#6  0x0000561c58b60a03 in zend_execute_scripts ()
#7  0x0000561c58affb60 in php_execute_script ()
#8  0x0000561c58bf7527 in ?? ()
#9  0x0000561c589e27b4 in main ()
```
demo
服务器
```
<?php
$socket = new Co\Socket(AF_INET, SOCK_STREAM, 0);
$socket->bind('127.0.0.1', 9501);
$socket->listen(128);

go(function () use ($socket) {
    $client = $socket->accept();
    echo "Accept: \n";
    while(true) {
        if ($client === false) {
            var_dump($socket->errCode);
        } else {
            $data = $client->recv(1);
            var_dump($data);
            $client->send('nihao');
        }
    }
});
```
客户端
```
<?php
$socket = new Co\Socket(AF_INET, SOCK_STREAM, 0);
go(function () use ($socket) {
    $retval = $socket->connect('localhost', 9501);
    while (true)
    {
        $socket->send("hello");
        $data = $socket->recv();
        echo $data;
        co::sleep(1.0);
    }
    var_dump($retval, $socket->errCode);
});
```
上面代码报段错误。
客户端设置recv超时时间是正常的，但是服务器端不能设置。。。
下面代码是正常运行的
客户端
```
<?php
$socket = new Co\Socket(AF_INET, SOCK_STREAM, 0);
go(function () use ($socket) {
    $retval = $socket->connect('localhost', 9501);
    while (true)
    {
        $socket->send("hello");
        $data = $socket->recv(0.2);
        echo $data;
        co::sleep(1);
    }
    var_dump($retval, $socket->errCode);
});
```
服务器端
```
<?php
$socket = new Co\Socket(AF_INET, SOCK_STREAM, 0);
$socket->bind('127.0.0.1', 9501);
$socket->listen(128);

go(function () use ($socket) {
    $client = $socket->accept();
    echo "Accept: \n";
    while(true) {
        if ($client === false) {
            var_dump($socket->errCode);
        } else {
            $data = $client->recv();
            var_dump($data);
            co::sleep(3.0);
            $client->send('nihao');
        }
    }
});
```

**Comment by twose** [comment]
@keilestone Fixed in #1704
