### ISSUE TITLE
coroutine中使用swoole lock，\Swoole\Coroutine::sleep后出现问题。

### ISSUE THREAD

**Issue by 8923052** [swoole/swoole-src#1856]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
重现：ab -kc 100 -n 1000 http://127.0.0.1:9501/
代码如下：
```
<?php
$http = new swoole_http_server("0.0.0.0", 9501);
$http->set(array (
		'worker_num' => 1,
		'dispatch_mode' => 1 
));

$lock = new \swoole_lock(\swoole_lock::MUTEX);
$http->on("request", function ($request, $response) use ($lock) {
	go(function () use ($lock) {
		$coroutine_id = \Swoole\Coroutine::getuid();
		//echo date('Y-m-d H:i:s') . " croutine_id:{$coroutine_id} - 获取锁" . PHP_EOL;
		$res = $lock->trylock();
		//echo date('Y-m-d H:i:s') . " croutine_id:{$coroutine_id} - 获取锁:{$res}" . PHP_EOL;
		\Swoole\Coroutine::sleep(0.1);
		if($res){
			$res = $lock->unlock();
			//echo date('Y-m-d H:i:s') . " croutine_id:{$coroutine_id} - 释放锁:{$res}" . PHP_EOL;
		}
	});
	$response->header("Content-Type", "text/plain");
	$response->end('123');
});

$http->start();
```

2. What did you expect to see?

3. What did you see instead?
```
*** Error in `php': free(): invalid pointer: 0x00007f4145c31800 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7f414c371bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7f414c377fc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7f414c37880e]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so(swHashMap_add_int+0x23c)[0x7f4146e94d7c]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so(+0xd1526)[0x7f4146eb5526]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so(+0x4500d)[0x7f4146e2900d]
php(execute_ex+0x829c)[0x5639fcb71efc]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so(_ZN6swoole7Context12context_funcEPv+0xb)[0x7f4146e9a43b]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so(make_fcontext+0x21)[0x7f4146ec20e1]
======= Memory map: ========
5639fc4c4000-5639fd36a000 r-xp 00000000 08:03 36915683                   /usr/local/php/bin/php
5639fd56a000-5639fd628000 r--p 00ea6000 08:03 36915683                   /usr/local/php/bin/php
5639fd628000-5639fd658000 rw-p 00f64000 08:03 36915683                   /usr/local/php/bin/php
5639fd658000-5639fd67e000 rw-p 00000000 00:00 0 
5639fe5cb000-5639fe877000 rw-p 00000000 00:00 0                          [heap]
5639fe877000-5639fe898000 rw-p 00000000 00:00 0                          [heap]
7f412c000000-7f412c021000 rw-p 00000000 00:00 0 
7f412c021000-7f4130000000 ---p 00000000 00:00 0 
7f4131e00000-7f4143e00000 rw-p 00000000 00:00 0 
7f4143f7d000-7f414417e000 rw-s 00000000 00:04 69235                      /dev/zero (deleted)
7f414417e000-7f41453ff000 rw-s 00000000 00:04 69234                      /dev/zero (deleted)
7f41453ff000-7f4145c00000 r--s 00000000 00:04 69233                      /dev/zero (deleted)
7f4145c00000-7f4145e00000 rw-p 00000000 00:00 0 
7f4145f88000-7f4146189000 rw-s 00000000 00:04 69231                      /dev/zero (deleted)
7f4146189000-7f41461ed000 r-xp 00000000 08:03 102258742                  /usr/lib/x86_64-linux-gnu/libsodium.so.18.1.1
7f41461ed000-7f41463ed000 ---p 00064000 08:03 102258742                  /usr/lib/x86_64-linux-gnu/libsodium.so.18.1.1
7f41463ed000-7f41463ee000 r--p 00064000 08:03 102258742                  /usr/lib/x86_64-linux-gnu/libsodium.so.18.1.1
7f41463ee000-7f41463ef000 rw-p 00065000 08:03 102258742                  /usr/lib/x86_64-linux-gnu/libsodium.so.18.1.1
7f41463ef000-7f41463fe000 r-xp 00000000 08:03 102405806                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/sodium.so
7f41463fe000-7f41465fd000 ---p 0000f000 08:03 102405806                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/sodium.so
7f41465fd000-7f41465ff000 r--p 0000e000 08:03 102405806                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/sodium.so
7f41465ff000-7f4146600000 rw-p 00010000 08:03 102405806                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/sodium.so
7f4146600000-7f4146800000 rw-p 00000000 00:00 0 
7f4146977000-7f4146983000 r-xp 00000000 08:03 102103176                  /usr/lib/x86_64-linux-gnu/libhiredis.so.0.13
7f4146983000-7f4146b83000 ---p 0000c000 08:03 102103176                  /usr/lib/x86_64-linux-gnu/libhiredis.so.0.13
7f4146b83000-7f4146b84000 r--p 0000c000 08:03 102103176                  /usr/lib/x86_64-linux-gnu/libhiredis.so.0.13
7f4146b84000-7f4146b85000 rw-p 0000d000 08:03 102103176                  /usr/lib/x86_64-linux-gnu/libhiredis.so.0.13
7f4146b85000-7f4146be0000 r-xp 00000000 08:03 102258886                  /usr/local/lib/libjemalloc.so.2
7f4146be0000-7f4146de0000 ---p 0005b000 08:03 102258886                  /usr/local/lib/libjemalloc.so.2
7f4146de0000-7f4146de2000 r--p 0005b000 08:03 102258886                  /usr/local/lib/libjemalloc.so.2
7f4146de2000-7f4146de3000 rw-p 0005d000 08:03 102258886                  /usr/local/lib/libjemalloc.so.2
7f4146de3000-7f4146de4000 rw-p 00000000 00:00 0 
7f4146de4000-7f4146eed000 r-xp 00000000 08:03 102405807                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f4146eed000-7f41470ec000 ---p 00109000 08:03 102405807                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f41470ec000-7f41470f8000 r--p 00108000 08:03 102405807                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f41470f8000-7f414750b000 rw-p 00114000 08:03 102405807                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f414750b000-7f414758b000 rw-p 00000000 00:00 0 
7f414758b000-7f41475f6000 r-xp 00000000 08:03 102405804                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/redis.so
7f41475f6000-7f41477f6000 ---p 0006b000 08:03 102405804                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/redis.so
7f41477f6000-7f41477fb000 r--p 0006b000 08:03 102405804                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/redis.so
7f41477fb000-7f41477ff000 rw-p 00070000 08:03 102405804                  /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/redis.so
7f41477ff000-7f4147800000 rw-p 00000000 00:00 0 
7f4147800000-7f4147a00000 rw-p 00000000 00:00 0 
7f4147b5c000-7f4147bdd000 rw-p 00000000 00:00 0 
7f4147bdd000-7f4147be4000 r-xp 00000000 08:03 102103152                  /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f4147be4000-7f4147de4000 ---p 00007000 08:03 102103152                  /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f4147de4000-7f4147de5000 r--p 00007000 08:03 102103152                  /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f4147de5000-7f4147de6000 rw-p 00008000 08:03 102103152                  /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f4147de6000-7f4147df7000 r-xp 00000000 08:03 102258748                  /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.3
7f4147df7000-7f4147ff7000 ---p 00011000 08:03 102258748                  /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.3
7f4147ff7000-7f4147ff8000 r--p 00011000 08:03 102258748                  /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.3
7f4147ff8000-7f4147ff9000 rw-p 00012000 08:03 102258748                  /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.3
7f4147ff9000-7f414802b000 r-xp 00000000 08:03 102102917                  /lib/x86_64-linux-gnu/libidn.so.11.6.16
7f414802b000-7f414822b000 ---p 00032000 08:03 102102917                  /lib/x86_64-linux-gnu/libidn.so.11.6.16
7f414822b000-7f414822c000 r--p 00032000 08:03 102102917                  /lib/x86_64-linux-gnu/libidn.so.11.6.16
7f414822c000-7f414822d000 rw-p 00033000 08:03 102102917                  /lib/x86_64-linux-gnu/libidn.so.11.6.16
7f414822d000-7f4148287000 r-xp 00000000 08:03 102258721                  /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.2.0
7f4148287000-7f4148486000 ---p 0005a000 08:03 102258721                  /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.2.0
7f4148486000-7f4148490000 r--p 00059000 08:03 102258721                  /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.2.0
7f4148490000-7f4148492000 rw-p 00063000 08:03 102258721                  /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.2.0
7f4148492000-7f41484ac000 r-xp 00000000 08:03 102258740                  /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f41484ac000-7f41486ab000 ---p 0001a000 08:03 102258740                  /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f41486ab000-7f41486ac000 r--p 00019000 08:03 102258740                  /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f41486ac000-7f41486ad000 rw-p 0001a000 08:03 102258740                  /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f41486ad000-7f41486b0000 r-xp 00000000 08:03 102102919                  /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f41486b0000-7f41488af000 ---p 00003000 08:03 102102919                  /lib/x86_64-linux-gnu/libkeyutils.so.1.5[2018-08-01 17:01:57 $155.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=6
```
**gdb调试信息**
```
gdb php core.157 
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...done.
[New LWP 157]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php http.php'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f414c33542a in __GI_abort () at abort.c:89
#2  0x00007f414c371c00 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f414c466d98 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f414c377fc6 in malloc_printerr (action=3, str=0x7f414c46394a "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
#4  0x00007f414c37880e in _int_free (av=0x7f414c69ab00 <main_arena>, p=0x7f4145c317f0, have_lock=0) at malloc.c:3905
#5  0x00007f4146e94d7c in swHashMap_add_int () from /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
#6  0x00007f4146eb5526 in swTimer_add () from /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
#7  0x00007f4146e2900d in zim_swoole_coroutine_util_sleep () from /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
#8  0x00005639fcb71efc in execute_ex ()
#9  0x00007f4146e9a43b in swoole::Context::context_func (arg=0x5639fe878d20) at /usr/src/swoole/src/coroutine/context.cc:66
#10 0x00007f4146ec20e1 in make_fcontext () from /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
#11 0x0000000000000000 in ?? ()
```

4. What version of Swoole are you using (`php --ri swoole`)?
```
php --ri swoole

swoole

swoole support => enabled
Version => 4.0.3
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
sockets => enabled
openssl => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
jemalloc => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ? 

```
uname -a
Linux localhost.localdomain 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 GNU/Linux
```

```
php -v
PHP 7.2.8 (cli) (built: Aug  1 2018 03:14:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

6. If you are using ssl, what is your openssl version?
```
openssl version
OpenSSL 1.1.0f  25 May 2017
```

**Comment by 8923052** [comment]
没有xdebug，很奇怪，换了一个环境，确实没出现问题，两个环境的差异是用的jemalloc版本不同，上述问题环境，jemalloc版本为4.5.0，先close，能稳定复现再提issue
