### ISSUE TITLE
server stop inside task worker cause segment fault

### ISSUE THREAD

**Issue by liues1992** [swoole/swoole-src#1873]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

A demo shows the error
```
<?php

$serv = new \swoole_server('127.0.0.1', 8082);
$serv->set(['task_worker_num'=>1, 'worker_num'=>1]);
$serv->on("Receive", function ($s, $fd, $from_id, $data) {
    echo "onReceve\n";
    $s->task('anything');
});
$serv->on("Task", function ($s) {
    echo "onTask\n";
    $s->stop(); // !!SEGMENT FAULT here!!!
});
$serv->on("Finish", function () {
    echo "onFinish\n";
});
$serv->start();

```
save it to /tmp/tmp.php
run `php /tmp/tmp.php`
run in other terminal: `telnet 127.0.0.1 8082`
type in anything and return

2. What did you expect to see?

No segment fault, exit normally.

3. What did you see instead?

- segment fault caused coredump
- in stdout: `WARNING	swManager_check_exit_status: worker#1 abnormal exit, status=0, signal=11`
- stack trace:
```
#0  0x000000000084cd79 in zim_swoole_server_stop (execute_data=<optimized out>, return_value=0x7f2e0ea150c0) at /build/php-bin/php-7.0.29/ext/swoole/swoole_server.c:3542
#1  0x00000000009cc982 in ZEND_DO_FCALL_SPEC_HANDLER () at /build/php-bin/php-7.0.29/Zend/zend_vm_execute.h:842
#2  0x000000000098824b in execute_ex (ex=<optimized out>) at /build/php-bin/php-7.0.29/Zend/zend_vm_execute.h:414
#3  0x000000000093b461 in zend_call_function (fci=fci@entry=0x7ffcd5db89f0, fci_cache=0x7f2e0ea6dbe0, fci_cache@entry=0x0) at /build/php-bin/php-7.0.29/Zend/zend_execute_API.c:867
#4  0x000000000093b888 in call_user_function_ex (function_table=<optimized out>, object=object@entry=0x0, function_name=<optimized out>, retval_ptr=retval_ptr@entry=0x7ffcd5db8a90,
    param_count=<optimized out>, params=params@entry=0x7ffcd5db8aa0, no_separation=0, symbol_table=0x0) at /build/php-bin/php-7.0.29/Zend/zend_execute_API.c:675
#5  0x0000000000856d72 in sw_call_user_function_ex (ymbol_table=0x0, no_separation=0, params=0x7ffcd5db8a70, param_count=<optimized out>, retval_ptr_ptr=<synthetic pointer>,
    function_name=<optimized out>, object_pp=0x0, function_table=<optimized out>) at /build/php-bin/php-7.0.29/ext/swoole/php7_wrapper.h:273
#6  php_swoole_onInterval (timer=<optimized out>, tnode=0x2fdc460) at /build/php-bin/php-7.0.29/ext/swoole/swoole_timer.c:229
#7  0x00000000008a1641 in swTimer_select (timer=0x189c180 <SwooleG>) at /build/php-bin/php-7.0.29/ext/swoole/src/network/Timer.c:213
#8  0x0000000000897b55 in swProcessPool_worker_loop (pool=0x7f2e0c7ff230, worker=0x7f2e0c80f010) at /build/php-bin/php-7.0.29/ext/swoole/src/network/ProcessPool.c:440
#9  0x0000000000898a28 in swProcessPool_spawn (worker=0x7f2e0c80f010) at /build/php-bin/php-7.0.29/ext/swoole/src/network/ProcessPool.c:314
#10 0x0000000000898b51 in swProcessPool_start (pool=0x7f2e0c7ff230) at /build/php-bin/php-7.0.29/ext/swoole/src/network/ProcessPool.c:143
#11 0x000000000089ec06 in swManager_start (factory=0x2ee5738) at /build/php-bin/php-7.0.29/ext/swoole/src/network/Manager.c:138
#12 0x000000000088aa3a in swFactoryProcess_start (factory=0x2ee5738) at /build/php-bin/php-7.0.29/ext/swoole/src/factory/FactoryProcess.c:86
#13 0x0000000000892e0b in swServer_start (serv=0x2ee52c0) at /build/php-bin/php-7.0.29/ext/swoole/src/network/Server.c:747
#14 0x000000000086527c in zim_swoole_http_server_start (execute_data=0x7f2e0ea14e40, return_value=0x7f2e0ea14e30) at /build/php-bin/php-7.0.29/ext/swoole/swoole_http_server.c:1631
#15 0x00000000009cc982 in ZEND_DO_FCALL_SPEC_HANDLER () at /build/php-bin/php-7.0.29/Zend/zend_vm_execute.h:842
#16 0x000000000098824b in execute_ex (ex=<optimized out>) at /build/php-bin/php-7.0.29/Zend/zend_vm_execute.h:414
#17 0x00000000009dc037 in zend_execute (op_array=0x7f2e0ea9e000, op_array@entry=0x7f2e0c5d0a40, return_value=return_value@entry=0x7f2e0ea14ad0)
    at /build/php-bin/php-7.0.29/Zend/zend_vm_execute.h:458
#18 0x000000000094a5e4 in zend_execute_scripts (type=type@entry=8, retval=0x7f2e0ea14ad0, retval@entry=0x0, file_count=file_count@entry=3) at /build/php-bin/php-7.0.29/Zend/zend.c:1445
#19 0x00000000008ec3e0 in php_execute_script (primary_file=0x7ffcd5dbd460) at /build/php-bin/php-7.0.29/main/main.c:2516
#20 0x00000000009ddc4a in do_cli (argc=0, argv=0x1148aa2) at /build/php-bin/php-7.0.29/sapi/cli/php_cli.c:977
#21 0x000000000049aa67 in main (argc=0, argv=0x1148aa2) at /build/php-bin/php-7.0.29/sapi/cli/php_cli.c:1347

```

4. What version of Swoole are you using (`php --ri swoole`)?

1.10.5

5. What is your machine environment used (including version of kernel & php & gcc) ? 

kernel: Linux 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

php: PHP 7.0.29

gcc: gcc (Debian 4.9.2-10+deb8u1) 4.9.2

6. If you are using ssl, what is your openssl version?
no

**Comment by twose** [comment]
Thank you for your contribution.
