### ISSUE TITLE
Coroutine\Http\Client send request crash

### ISSUE THREAD

**Issue by s890510** [swoole/swoole-src#2053]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

透過POST方式上傳一個檔案到Server端 (檔案大小：185KB)，並透過Server轉送到第三方儲存
```php
$http = new swoole_http_server('0.0.0.0', 1124);

$http->on("request", function ($request, $response) {
    $dateTime = new DateTime('now', new DateTimeZone('GMT'));

    print_r($request->files['Test']);

    $fp = fopen($request->files['Test']['tmp_name'], "r");
    $data = fread($fp, $request->files['Test']['size']);
    fclose($fp);

    $urlData = parse_url('');

    $header = array(
        'Content-Type' => $request->files['Test']['type'],
        'Content-Length' => $size
    );

    $header['Authorization'] = "";

    $client = new Swoole\Coroutine\Http\Client(
        $urlData['host'],
        (isset($urlData['port'])) ? $urlData['port'] : (($urlData['scheme'] == 'http') ? 80 : 443),
        ($urlData['scheme'] == 'http') ? false : true
    );

    $client->set(['timeout' => 1.0]);
    $client->setHeaders($header);
    $client->setMethod('PUT');

    $client->setData($data);

    $client->execute((isset($urlData['path']) ? $urlData['path'] : "/").(isset($urlData['query']) ? '?'.$urlData['query'] : ''));

    $statusCode = $client->statusCode;

    $client->close();

    $response->status(200);
    $response->end();
});

$http->start();
```
透過埋Log發現是掛在$client->execute這行
在v4.2.1是正常的

2. What did you expect to see?
成功送出...

3. What did you see instead?

```shell
> [2018-10-22 10:23:55 $12305.0]  WARNING swManager_check_exit_status: worker#1 abnormal exit, status=0, signal=11
	A bug occurred in Swoole-v4.2.3, please report it.
	The Swoole developers probably don't know about it,
	and unless you report it, chances are it won't be fixed.
	You can read How to report a bug doc before submitting any bug reports:
	https://github.com/swoole/swoole-src/issues/2000
	Please do not send bug reports in the mailing list or personal letters.
	The issue page is also suitable to submit feature requests.
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole-v4.2.3

5. What is your machine environment used (including version of kernel & php & gcc) ?
ubuntu-16.04
  php-v7.2.11
  gcc-v5.4.0

**Comment by twose** [comment]
此处的确存在BUG, 由于Github处于半宕机状态, 请先使用v4.2.1, 或尝试master版本, 新版本修复已在计划中.

**Comment by twose** [comment]
@s890510 能否尝试一下master版本是否会出现这个BUG, 已经做了一定的修复梳理

**Comment by s890510** [comment]
@twose 剛剛試了一下還是不行
Request有發送成功 (檔案有順利新增)，所以看起來是處理response時出現問題

```
[2018-10-25 08:05:18 *12147.2]  TRACE   swReactorEpoll_add(:140): add event[reactor_id=0, fd=26, events=1024]
[2018-10-25 08:05:18 *12147.2]  TRACE   swTimer_add(:165): id=9, exec_msec=1037, msec=1000, round=17
[2018-10-25 08:05:18 *12147.2]  TRACE   save_php_stack(:92): coro_yield coro id 2
[2018-10-25 08:05:18 *12147.2]  TRACE   swReactorEpoll_del(:155): remove event[reactor_id=0|fd=26]
[2018-10-25 08:05:18 *12147.2]  TRACE   resume_php_stack(:82): sw_coro_resume coro id 2
[2018-10-25 08:05:18 *12147.2]  TRACE   internal_coro_resume(:126): cid=2
[2018-10-25 08:05:18 *12147.2]  DEBUG   swConnection_recv(:188): recv -1/8192 bytes, errno=11
[2018-10-25 08:05:18 *12147.2]  TRACE   swReactorEpoll_add(:140): add event[reactor_id=0, fd=26, events=1024]
[2018-10-25 08:05:18 *12147.2]  TRACE   swTimer_add(:165): id=10, exec_msec=1039, msec=1000, round=18
[2018-10-25 08:05:18 *12147.2]  TRACE   save_php_stack(:92): coro_yield coro id 2
[2018-10-25 08:05:18 *12147.2]  TRACE   swReactorEpoll_del(:155): remove event[reactor_id=0|fd=26]
[2018-10-25 08:05:18 *12150.5]  TRACE   Context(:32): alloc stack: size=2097152, ptr=0x55a28e0d8540.
[2018-10-25 08:05:18 *12150.5]  TRACE   sw_coro_func(:229): Create coro id: 28, coro total count: 1, heap size: 1220560
[2018-10-25 08:05:18 *12150.5]  TRACE   sw_coro_close(:361): coro_close coro id 28
[2018-10-25 08:05:18 *12150.5]  TRACE   sw_coro_close(:393): close coro and 0 remained. usage size: 1212368. malloc size: 2097152
[2018-10-25 08:05:18 *12150.5]  TRACE   ~Context(:54): free stack: ptr=0x55a28e0d8540
[2018-10-25 08:05:18 $12142.0]  WARNING swManager_check_exit_status: worker#2 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.4-alpha, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
```

**Comment by s890510** [comment]
@twose 
腳本有點困難，如果需要我可以依照目前的結構生看看...
Valgrind我的環境無法正常執行....所以僅提供GDB內容

```
(gdb) bt
#0  coroutine_resume (co=0x0) at /home/evan/swoole-src/src/coroutine/base.cc:168
#1  0x00007f4d773bbecf in socket_onWrite (reactor=0x55d1183639d0, event=<optimized out>) at /home/evan/swoole-src/src/coroutine/socket.cc:584
#2  0x00007f4d773c70f7 in swReactorEpoll_wait (reactor=0x55d1183639d0, timeo=<optimized out>) at /home/evan/swoole-src/src/reactor/epoll.c:268
#3  0x00007f4d773dbf16 in swWorker_loop (factory=factory@entry=0x55d118322ff0, worker_id=worker_id@entry=0) at /home/evan/swoole-src/src/network/worker.c:794
#4  0x00007f4d773d8b3f in swManager_spawn_worker (factory=0x55d118322ff0, worker_id=0) at /home/evan/swoole-src/src/network/manager.c:508
#5  0x00007f4d773d929e in swManager_start (factory=factory@entry=0x55d118322ff0) at /home/evan/swoole-src/src/network/manager.c:144
#6  0x00007f4d773c341d in swFactoryProcess_start (factory=0x55d118322ff0) at /home/evan/swoole-src/src/factory/process.c:86
#7  0x00007f4d773cbade in swServer_start (serv=serv@entry=0x55d118322b60) at /home/evan/swoole-src/src/network/server.c:762
#8  0x00007f4d7732d7d3 in zim_swoole_server_start (execute_data=0x7f4d8081c320, return_value=0x7fff749cfbc0) at /home/evan/swoole-src/swoole_server.c:2881
#9  0x000055d117c6b436 in execute_ex ()
#10 0x000055d117c6c6fe in zend_execute ()
#11 0x000055d117bbacc3 in zend_execute_scripts ()
#12 0x000055d117b55ef0 in php_execute_script ()
#13 0x000055d117c6ead9 in ?? ()
#14 0x000055d117a0aecc in ?? ()
#15 0x00007f4d83409830 in __libc_start_main (main=0x55d117a0aa50, argc=2, argv=0x7fff749d35b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fff749d35a8) at ../csu/libc-start.c:291
#16 0x000055d117a0afe9 in _start ()
```

**Comment by matyhtf** [comment]
@s890510 请在 http server 中将出现问题的 Http请求报文发给我们。

```php
<?php
$http = new swoole_http_server('0.0.0.0', 1124);

$http->on("request", function ($request, $response) {
	$dateTime = new DateTime('now', new DateTimeZone('GMT'));
        file_put_contents(__DIR__.'/http_data', $request->getData());
```

**Comment by s890510** [comment]
@twose @matyhtf 
我會從目前的code整理出一份腳本發到mail
（不過我也無法確定是否是coro的部分有使用錯誤,因為有採用call user function ）

另外，編譯的部分是採用make clean; rm .gitignore; got clean -f -d; got checkout -f;phpize;.....
