### ISSUE TITLE
swoole 4.2.6 channel  run tests  core dumped

### ISSUE THREAD

**Issue by mangowong** [swoole/swoole-src#2094]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

  run tests in  tests/swoole_coroutine_channel/blocking_timeout.phpt

2. What did you expect to see?

 run tests pass 

3. What did you see instead?

```shell
--TEST--
swoole_coroutine_channel: blocking and timeout
--SKIPIF--
--FILE--
*** glibc detected *** /usr/local/php-7.1.16/bin/php: double free or corruption (out): 0x0000000002842a60 ***
======= Backtrace: =========
/lib64/libc.so.6[0x36a4a75f4e]
/lib64/libc.so.6[0x36a4a78ca0]
/usr/local/php-7.1.16/lib/php/extensions/no-debug-non-zts-20160303/swoole.so(+0x43857)[0x7f33257eb857]
/usr/local/php-7.1.16/lib/php/extensions/no-debug-non-zts-20160303/swoole.so(+0x703eb)[0x7f33258183eb]
/usr/local/php-7.1.16/lib/php/extensions/no-debug-non-zts-20160303/swoole.so(swTimer_select+0x169)[0x7f332580a4d9]
/usr/local/php-7.1.16/lib/php/extensions/no-debug-non-zts-20160303/swoole.so(+0x700b8)[0x7f33258180b8]
/usr/local/php-7.1.16/lib/php/extensions/no-debug-non-zts-20160303/swoole.so(+0x700f9)[0x7f33258180f9]
/usr/local/php-7.1.16/lib/php/extensions/no-debug-non-zts-20160303/swoole.so(+0x70657)[0x7f3325818657]
/usr/local/php-7.1.16/lib/php/extensions/no-debug-non-zts-20160303/swoole.so(php_swoole_event_wait+0xda)[0x7f33258328ba]
/usr/local/php-7.1.16/bin/php[0x86d160]
/usr/local/php-7.1.16/bin/php(execute_ex+0x28)[0x84bc38]
/usr/local/php-7.1.16/bin/php(zend_execute+0x1c0)[0x8977d0]
/usr/local/php-7.1.16/bin/php(zend_execute_scripts+0xb3)[0x7f0103]
/usr/local/php-7.1.16/bin/php(php_execute_script+0x290)[0x78f940]
/usr/local/php-7.1.16/bin/php[0x89ab3a]
/usr/local/php-7.1.16/bin/php[0x89b33a]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x36a4a1ed5d]
/usr/local/php-7.1.16/bin/php[0x4398c5]
======= Memory map: ========
00400000-00e7c000 r-xp 00000000 08:03 402045                             /usr/local/php-7.1.16/bin/php
0107c000-01135000 rw-p 00a7c000 08:03 402045                             /usr/local/php-7.1.16/bin/php
01135000-0115a000 rw-p 00000000 00:00 0
0277b000-0299d000 rw-p 00000000 00:00 0                                  [heap]
32d8800000-32d881d000 r-xp 00000000 08:03 1836535                        /lib64/libselinux.so.1
32d881d000-32d8a1c000 ---p 0001d000 08:03 1836535                        /lib64/libselinux.so.1
32d8a1c000-32d8a1d000 r--p 0001c000 08:03 1836535                        /lib64/libselinux.so.1
32d8a1d000-32d8a1e000 rw-p 0001d000 08:03 1836535                        /lib64/libselinux.so.1
32d8a1e000-32d8a1f000 rw-p 00000000 00:00 0
32d8c00000-32d8c0a000 r-xp 00000000 08:03 1836536                        /lib64/libkrb5support.so.0.1
32d8c0a000-32d8e09000 ---p 0000a000 08:03 1836536                        /lib64/libkrb5support.so.0.1
32d8e09000-32d8e0a000 r--p 00009000 08:03 1836536                        /lib64/libkrb5support.so.0.1
32d8e0a000-32d8e0b000 rw-p 0000a000 08:03 1836536                        /lib64/libkrb5support.so.0.1
32d9000000-32d90db000 r-xp 00000000 08:03 1836538                        /lib64/libkrb5.so.3.3
32d90db000-32d92db000 ---p 000db000 08:03 1836538                        /lib64/libkrb5.so.3.3
32d92db000-32d92e5000 r--p 000db000 08:03 1836538                        /lib64/libkrb5.so.3.3
32d92e5000-32d92e7000 rw-p 000e5000 08:03 1836538                        /lib64/libkrb5.so.3.3
32d9400000-32d9429000 r-xp 00000000 08:03 1836537                        /lib64/libk5crypto.so.3.1
32d9429000-32d9629000 ---p 00029000 08:03 1836537                        /lib64/libk5crypto.so.3.1
32d9629000-32d962a000 r--p 00029000 08:03 1836537                        /lib64/libk5crypto.so.3.1
32d962a000-32d962b000 rw-p 0002a000 08:03 1836537                        /lib64/libk5crypto.so.3.1
32d962b000-32d962c000 rw-p 00000000 00:00 0
32d9c00000-32d9c41000 r-xp 00000000 08:03 1836540                        /lib64/libgssapi_krb5.so.2.2
32d9c41000-32d9e41000 ---p 00041000 08:03 1836540                        /lib64/libgssapi_krb5.so.2.2
32d9e41000-32d9e42000 r--p 00041000 08:03 1836540                        /lib64/libgssapi_krb5.so.2.2
32d9e42000-32d9e44000 rw-p 00042000 08:03 1836540                        /lib64/libgssapi_krb5.so.2.2
32da000000-32da062000 r-xp 00000000 08:03 270842                         /usr/lib64/libssl.so.1.0.1e
32da062000-32da261000 ---p 00062000 08:03 270842                         /usr/lib64/libssl.so.1.0.1e
32da261000-32da265000 r--p 00061000 08:03 270842                         /usr/lib64/libssl.so.1.0.1e
32da265000-32da26c000 rw-p 00065000 08:03 270842                         /usr/lib64/libssl.so.1.0.1e
32db400000-32db452000 r-xp 00000000 08:03 287035                         /usr/lib64/libcurl.so.4.1.1
32db452000-32db652000 ---p 00052000 08:03 287035                         /usr/lib64/libcurl.so.4.1.1
32db652000-32db655000 rw-p 00052000 08:03 287035                         /usr/lib64/libcurl.so.4.1.1
32db800000-32db827000 r-xp 00000000 08:03 287117                         /usr/lib64/libssh2.so.1.0.1
32db827000-32dba26000 ---p 00027000 08:03 287117                         /usr/lib64/libssh2.so.1.0.1
32dba26000-32dba28000 rw-p 00026000 08:03 287117                         /usr/lib64/libssh2.so.1.0.1
36a4200000-36a4220000 r-xp 00000000 08:03 1835487                        /lib64/ld-2.12.so
36a441f000-36a4420000 r--p 0001f000 08:03 1835487                        /lib64/ld-2.12.so
36a4420000-36a4421000 rw-p 00020000 08:03 1835487                        /lib64/ld-2.12.so
36a4421000-36a4422000 rw-p 00000000 00:00 0
36a4600000-36a4602000 r-xp 00000000 08:03 1835489                        /lib64/libdl-2.12.so
36a4602000-36a4802000 ---p 00002000 08:03 1835489                        /lib64/libdl-2.12.so
36a4802000-36a4803000 r--p 00002000 08:03 1835489                        /lib64/libdl-2.12.so
36a4803000-36a4804000 rw-p 00003000 08:03 1835489                        /lib64/libdl-2.12.so
36a4a00000-36a4b8a000 r-xp 00000000 08:03 1835488                        /lib64/libc-2.12.so
36a4b8a000-36a4d8a000 ---p 0018a000 08:03 1835488                        /lib64/libc-2.12.so
36a4d8a000-36a4d8e000 r--p 0018a000 08:03 1835488                        /lib64/libc-2.12.so
36a4d8e000-36a4d8f000 rw-p 0018e000 08:03 1835488                        /lib64/libc-2.12.so
36a4d8f000-36a4d94000 rw-p 00000000 00:00 0
36a4e00000-36a4e17000 r-xp 00000000 08:03 1835490                        /lib64/libpthread-2.12.so
36a4e17000-36a5017000 ---p 00017000 08:03 1835490                        /lib64/libpthread-2.12.so
36a5017000-36a5018000 r--p 00017000 08:03 1835490                        /lib64/libpthread-2.12.so
36a5018000-36a5019000 rw-p 00018000 08:03 1835490                        /lib64/libpthread-2.12.so
36a5019000-36a501d000 rw-p 00000000 00:00 0
36a5200000-36a5215000 r-xp 00000000 08:03 1835504                        /lib64/libz.so.1.2.3
36a5215000-36a5414000 ---p 00015000 08:03 1835504                      Aborted (core dumped)


Core was generated by `/usr/local/php-7.1.16/bin/php blocking_timeout.phpt'.
Program terminated with signal 6, Aborted.
#0  0x00000036a4a32625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install php-7.1.16-dist-1.el6.x86_64
(gdb) bt
#0  0x00000036a4a32625 in raise () from /lib64/libc.so.6
#1  0x00000036a4a33e05 in abort () from /lib64/libc.so.6
#2  0x00000036a4a70537 in __libc_message () from /lib64/libc.so.6
#3  0x00000036a4a75f4e in malloc_printerr () from /lib64/libc.so.6
#4  0x00000036a4a78ca0 in _int_free () from /lib64/libc.so.6
#5  0x00007f61929eb857 in deallocate (data=0x2652be0) at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ext/new_allocator.h:110
#6  _M_put_node (data=0x2652be0) at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/stl_list.h:338
#7  _M_erase (data=0x2652be0) at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/stl_list.h:1577
#8  pop_front (data=0x2652be0) at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/stl_list.h:1002
#9  pop_coroutine (data=0x2652be0) at /root/rpmbuild/BUILD/swoole-src-4.2.6/include/channel.h:112
#10 channel_defer_callback (data=0x2652be0) at /root/rpmbuild/BUILD/swoole-src-4.2.6/src/coroutine/channel.cc:29
#11 0x00007f6192a183eb in swReactor_defer_timer_callback (timer=Unhandled dwarf expression opcode 0xf3
) at /root/rpmbuild/BUILD/swoole-src-4.2.6/src/reactor/defer_task.cc:35
#12 0x00007f6192a0a4d9 in swTimer_select (timer=0x7f61930f7c00) at /root/rpmbuild/BUILD/swoole-src-4.2.6/src/network/timer.c:213
#13 0x00007f6192a180b8 in swReactor_onTimeout_and_Finish (reactor=0x259e640) at /root/rpmbuild/BUILD/swoole-src-4.2.6/src/reactor/base.c:147
#14 0x00007f6192a180f9 in swReactor_onTimeout (reactor=0x259e640) at /root/rpmbuild/BUILD/swoole-src-4.2.6/src/reactor/base.c:182
#15 0x00007f6192a18657 in swReactorEpoll_wait (reactor=0x259e640, timeo=Unhandled dwarf expression opcode 0xf3
) at /root/rpmbuild/BUILD/swoole-src-4.2.6/src/reactor/epoll.c:243
#16 0x00007f6192a328ba in php_swoole_event_wait () at /root/rpmbuild/BUILD/swoole-src-4.2.6/swoole_event.c:279
#17 0x000000000086d160 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER ()
#18 0x000000000084bc38 in execute_ex ()
#19 0x00000000008977d0 in zend_execute ()
#20 0x00000000007f0103 in zend_execute_scripts ()
#21 0x000000000078f940 in php_execute_script ()
#22 0x000000000089ab3a in do_cli ()
#23 0x000000000089b33a in main ()
(gdb)




```

4. What version of Swoole are you using (show your `php --ri swoole`)?

```shell

swoole

swoole support => enabled
Version => 4.2.6
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.1e-fips 11 Feb 2013
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

```

5. What is your machine environment used (including version of kernel & php & gcc) ?
```shell
1、Kernel
 CentOS release 6.7 (Final)   2.6.32-573.el6.x86_64 
2、PHP
PHP 7.1.16 (cli) (built: Apr  2 2018 09:46:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
3、GCC
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-2/root/usr --mandir=/opt/rh/devtoolset-2/root/usr/share/man --infodir=/opt/rh/devtoolset-2/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/isl-install --with-cloog=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/cloog-install --with-mpc=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)


```

**Comment by matyhtf** [comment]
Please use Valgrind to analyze memory operations.
```shell
USE_ZEND_ALLOC=0 valgrind php tests/swoole_coroutine_channel/blocking_timeout.phpt
```

**Comment by mangowong** [comment]
```shell
==20856== Memcheck, a memory error detector
==20856== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==20856== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==20856== Command: php /root/swoole-src/tests/swoole_coroutine_channel/blocking_timeout.phpt
==20856== 
--TEST--
swoole_coroutine_channel: blocking and timeout
--SKIPIF--
--FILE--
==20856== Warning: client switching stacks?  SP change: 0x7feffc540 --> 0xeecbff8
==20856==          to suppress, use: --max-stackframe=34092549448 or greater
==20856== Warning: client switching stacks?  SP change: 0xeecbe80 --> 0x7feffc540
==20856==          to suppress, use: --max-stackframe=34092549824 or greater
==20856== Warning: client switching stacks?  SP change: 0x7feffc540 --> 0xf2cbff8
==20856==          to suppress, use: --max-stackframe=34088355144 or greater
==20856==          further instances of this message will not be shown.
==20856== Invalid free() / delete / delete[] / realloc()
==20856==    at 0x4A06016: operator delete(void*) (vg_replace_malloc.c:480)
==20856==    by 0xDAC9EC6: channel_defer_callback(void*) (new_allocator.h:110)
==20856==    by 0xDAF9BCA: swReactor_defer_timer_callback(_swTimer*, _swTimer_node*) (defer_task.cc:35)
==20856==    by 0xDAE8C38: swTimer_select (timer.c:213)
==20856==    by 0xDAF9897: swReactor_onTimeout_and_Finish (base.c:147)
==20856==    by 0xDAF98D8: swReactor_onTimeout (base.c:182)
==20856==    by 0xDAF9E36: swReactorEpoll_wait (epoll.c:243)
==20856==    by 0xDB14269: php_swoole_event_wait (swoole_event.c:279)
==20856==    by 0x8E73D5: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:970)
==20856==    by 0x89611A: execute_ex (zend_vm_execute.h:429)
==20856==    by 0x8E9133: zend_execute (zend_vm_execute.h:474)
==20856==    by 0x8510D3: zend_execute_scripts (zend.c:1482)
==20856==  Address 0xea9c0b0 is 16 bytes inside a block of size 136 alloc'd
==20856==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==20856==    by 0xDB0676E: zim_swoole_channel_coro___construct(_zend_execute_data*, _zval_struct*) (swoole_channel_coro.cc:99)
==20856==    by 0x8E73D5: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:970)
==20856==    by 0x89611A: execute_ex (zend_vm_execute.h:429)
==20856==    by 0x8E9133: zend_execute (zend_vm_execute.h:474)
==20856==    by 0x8510D3: zend_execute_scripts (zend.c:1482)
==20856==    by 0x7F1EBF: php_execute_script (main.c:2577)
==20856==    by 0x8EB2CE: do_cli (php_cli.c:993)
==20856==    by 0x4480BF: main (php_cli.c:1381)
==20856== 
==20856== Invalid read of size 8
==20856==    at 0xDAC99B0: coroutine_resume (base.cc:168)
==20856==    by 0xDAC9ED2: channel_defer_callback(void*) (channel.cc:34)
==20856==    by 0xDAF9BCA: swReactor_defer_timer_callback(_swTimer*, _swTimer_node*) (defer_task.cc:35)
==20856==    by 0xDAE8C38: swTimer_select (timer.c:213)
==20856==    by 0xDAF9897: swReactor_onTimeout_and_Finish (base.c:147)
==20856==    by 0xDAF98D8: swReactor_onTimeout (base.c:182)
==20856==    by 0xDAF9E36: swReactorEpoll_wait (epoll.c:243)
==20856==    by 0xDB14269: php_swoole_event_wait (swoole_event.c:279)
==20856==    by 0x8E73D5: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:970)
==20856==    by 0x89611A: execute_ex (zend_vm_execute.h:429)
==20856==    by 0x8E9133: zend_execute (zend_vm_execute.h:474)
==20856==    by 0x8510D3: zend_execute_scripts (zend.c:1482)
==20856==  Address 0xea9c1b0 is 0 bytes after a block of size 64 alloc'd
==20856==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==20856==    by 0xDACA8A7: std::_Deque_base<void*, std::allocator<void*> >::_M_initialize_map(unsigned long) (new_allocator.h:104)
==20856==    by 0xDACA49A: swoole::Channel::Channel(unsigned long) (stl_deque.h:453)
==20856==    by 0xDB0677E: zim_swoole_channel_coro___construct(_zend_execute_data*, _zval_struct*) (swoole_channel_coro.cc:99)
==20856==    by 0x8E73D5: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:970)
==20856==    by 0x89611A: execute_ex (zend_vm_execute.h:429)
==20856==    by 0x8E9133: zend_execute (zend_vm_execute.h:474)
==20856==    by 0x8510D3: zend_execute_scripts (zend.c:1482)
==20856==    by 0x7F1EBF: php_execute_script (main.c:2577)
==20856==    by 0x8EB2CE: do_cli (php_cli.c:993)
==20856==    by 0x4480BF: main (php_cli.c:1381)
==20856== 
==20856== Invalid read of size 8
==20856==    at 0xDB0F879: internal_coro_resume (swoole_coroutine.cc:84)
==20856==    by 0xDAC99B5: coroutine_resume (base.cc:168)
==20856==    by 0xDAC9ED2: channel_defer_callback(void*) (channel.cc:34)
==20856==    by 0xDAF9BCA: swReactor_defer_timer_callback(_swTimer*, _swTimer_node*) (defer_task.cc:35)
==20856==    by 0xDAE8C38: swTimer_select (timer.c:213)
==20856==    by 0xDAF9897: swReactor_onTimeout_and_Finish (base.c:147)
==20856==    by 0xDAF98D8: swReactor_onTimeout (base.c:182)
==20856==    by 0xDAF9E36: swReactorEpoll_wait (epoll.c:243)
==20856==    by 0xDB14269: php_swoole_event_wait (swoole_event.c:279)
==20856==    by 0x8E73D5: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:970)
==20856==    by 0x89611A: execute_ex (zend_vm_execute.h:429)
==20856==    by 0x8E9133: zend_execute (zend_vm_execute.h:474)
==20856==  Address 0x40 is not stack'd, malloc'd or (recently) free'd
==20856== 
==20856== 
==20856== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==20856==  Access not within mapped region at address 0x40
==20856==    at 0xDB0F879: internal_coro_resume (swoole_coroutine.cc:84)
==20856==    by 0xDAC99B5: coroutine_resume (base.cc:168)
==20856==    by 0xDAC9ED2: channel_defer_callback(void*) (channel.cc:34)
==20856==    by 0xDAF9BCA: swReactor_defer_timer_callback(_swTimer*, _swTimer_node*) (defer_task.cc:35)
==20856==    by 0xDAE8C38: swTimer_select (timer.c:213)
==20856==    by 0xDAF9897: swReactor_onTimeout_and_Finish (base.c:147)
==20856==    by 0xDAF98D8: swReactor_onTimeout (base.c:182)
==20856==    by 0xDAF9E36: swReactorEpoll_wait (epoll.c:243)
==20856==    by 0xDB14269: php_swoole_event_wait (swoole_event.c:279)
==20856==    by 0x8E73D5: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:970)
==20856==    by 0x89611A: execute_ex (zend_vm_execute.h:429)
==20856==    by 0x8E9133: zend_execute (zend_vm_execute.h:474)
==20856==  If you believe this happened as a result of a stack
==20856==  overflow in your program's main thread (unlikely but
==20856==  possible), you can try to increase the size of the
==20856==  main thread stack using the --main-stacksize= flag.
==20856==  The main thread stack size used in this run was 10485760.
==20856== 
==20856== HEAP SUMMARY:
==20856==     in use at exit: 4,255,992 bytes in 26,765 blocks
==20856==   total heap usage: 35,350 allocs, 8,586 frees, 10,559,348 bytes allocated
==20856== 
==20856== LEAK SUMMARY:
==20856==    definitely lost: 0 bytes in 0 blocks
==20856==    indirectly lost: 0 bytes in 0 blocks
==20856==      possibly lost: 2,080,419 bytes in 20,854 blocks
==20856==    still reachable: 2,175,573 bytes in 5,911 blocks
==20856==         suppressed: 0 bytes in 0 blocks
==20856== Rerun with --leak-check=full to see details of leaked memory
==20856== 
==20856== For counts of detected and suppressed errors, rerun with: -v
==20856== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 8 from 6)
[1]    20856 segmentation fault (core dumped)  USE_ZEND_ALLOC=0 valgrind php 
```

**Comment by twose** [comment]
I just test it in the same php version and use valgrind to check it in PHP 7.4 but everything works well.
If you make clean when you upgrade your swoole?

**Comment by mangowong** [comment]
yes! is run make clean  when upgrade  swoole

**Comment by mangowong** [comment]
another machine with swoole 4.0.4  is  run normally
```php

$chan = new chan();
go(function () use ($chan) {
    $data = $chan->pop((float) 0.5);
    assert($data == false);
});
go(function () use ($chan) {
    sleep(1);
    $chan->push(11111);
});

swoole_event_wait();


```
```shell

php
PHP 7.1.16 (cli) (built: Apr  2 2018 09:46:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16, Copyright (c) 1999-2018, by Zend Technologies

swoole
swoole support => enabled
Version => 4.0.4
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608


==20432== Memcheck, a memory error detector
==20432== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==20432== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==20432== Command: /usr/local/php-7.1.16/bin/php hello.php
==20432==
==20432== Warning: client switching stacks?  SP change: 0x7feffca40 --> 0xc7a3518
==20432==          to suppress, use: --max-stackframe=34133611816 or greater
==20432== Warning: client switching stacks?  SP change: 0xc7a3450 --> 0x7feffca40
==20432==          to suppress, use: --max-stackframe=34133612016 or greater
==20432== Warning: client switching stacks?  SP change: 0x7feffca40 --> 0xca27ff8
==20432==          to suppress, use: --max-stackframe=34130971208 or greater
==20432==          further instances of this message will not be shown.
==20432==
==20432== HEAP SUMMARY:
==20432==     in use at exit: 956,502 bytes in 143 blocks
==20432==   total heap usage: 27,187 allocs, 27,044 frees, 8,864,283 bytes allocated
==20432==
==20432== LEAK SUMMARY:
==20432==    definitely lost: 525,680 bytes in 15 blocks
==20432==    indirectly lost: 406,768 bytes in 22 blocks
==20432==      possibly lost: 0 bytes in 0 blocks
==20432==    still reachable: 24,054 bytes in 106 blocks
==20432==         suppressed: 0 bytes in 0 blocks
==20432== Rerun with --leak-check=full to see details of leaked memory
==20432==
==20432== For counts of detected and suppressed errors, rerun with: -v
==20432== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)


```

**Comment by twose** [comment]
已定位到和低版本GCC有关

**Comment by mangowong** [comment]
代码能正常运行情况下最低GCC版本是？ 我编译一个试一下
