### ISSUE TITLE
taskwait segment fault

### ISSUE THREAD

**Issue by mysteriouss** [swoole/swoole-src#2098]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
'task_ipc_mode' => 2, 

$result = $http->taskwait([
            'topic' => 'withdraw',
            'payload' => $decrypted
        ],0);
```
第二次调用时，进程 segment fault : 11

2. What did you expect to see?

taskwait 正常工作

3. What did you see instead?

https://github.com/swoole/swoole-src/blob/77876aad4b423fd2538152d86ce7f63fd075fe71/swoole_server.c#L1213

https://github.com/swoole/swoole-src/blob/77876aad4b423fd2538152d86ce7f63fd075fe71/src/network/timer.c#L166

```
gdb php /core.30119 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/php...Reading symbols from /usr/bin/php...(no debugging symbols found)...done.
(no debugging symbols found)...done.
[New LWP 30119]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `php /usr/local/src/swoole/server_http.php:'.
Program terminated with signal 11, Segmentation fault.
#0  swTimer_del (timer=0x7f27dabeb1a0 <SwooleG>, tnode=0xfe643c46142e30de) at /usr/local/src/swoole/swoole-src-4.2.6/src/network/timer.c:166
166         if (tnode->remove)
Missing separate debuginfos, use: debuginfo-install php72w-cli-7.2.11-1.w7.x86_64
(gdb) bt
#0  swTimer_del (timer=0x7f27dabeb1a0 <SwooleG>, tnode=0xfe643c46142e30de) at /usr/local/src/swoole/swoole-src-4.2.6/src/network/timer.c:166
#1  0x00007f27da56a748 in php_swoole_onFinish (serv=<optimized out>, req=<optimized out>) at /usr/local/src/swoole/swoole-src-4.2.6/swoole_server.c:1213
#2  0x00007f27da4f67ca in swWorker_onTask (factory=factory@entry=0x56086cc31df8, task=task@entry=0x7ffca04eb6d0) at /usr/local/src/swoole/swoole-src-4.2.6/src/network/worker.c:420
#3  0x00007f27da4f6c51 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7ffca04ed740) at /usr/local/src/swoole/swoole-src-4.2.6/src/network/worker.c:834
#4  0x00007f27da503699 in swReactorEpoll_wait (reactor=0x56086cc92e30, timeo=<optimized out>) at /usr/local/src/swoole/swoole-src-4.2.6/src/reactor/epoll.c:258
#5  0x00007f27da4f710e in swWorker_loop (factory=factory@entry=0x56086cc31df8, worker_id=worker_id@entry=3) at /usr/local/src/swoole/swoole-src-4.2.6/src/network/worker.c:792
#6  0x00007f27da4e6044 in swManager_spawn_worker (factory=0x56086cc31df8, worker_id=3) at /usr/local/src/swoole/swoole-src-4.2.6/src/network/manager.c:508
#7  0x00007f27da4e67ee in swManager_start (factory=factory@entry=0x56086cc31df8) at /usr/local/src/swoole/swoole-src-4.2.6/src/network/manager.c:144
#8  0x00007f27da4dd92a in swFactoryProcess_start (factory=0x56086cc31df8) at /usr/local/src/swoole/swoole-src-4.2.6/src/factory/process.c:86
#9  0x00007f27da4f175b in swServer_start (serv=serv@entry=0x56086cc31960) at /usr/local/src/swoole/swoole-src-4.2.6/src/network/server.c:762
#10 0x00007f27da56d755 in zim_swoole_server_start (execute_data=<optimized out>, return_value=0x7ffca04ed9a0) at /usr/local/src/swoole/swoole-src-4.2.6/swoole_server.c:2881
#11 0x000056086a6eb655 in execute_ex ()
#12 0x000056086a6ec9e3 in zend_execute ()
#13 0x000056086a643b93 in zend_execute_scripts ()
#14 0x000056086a5dfdb0 in php_execute_script ()
#15 0x000056086a6eede6 in do_cli ()
#16 0x000056086a454c9e in main ()
(gdb) 
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
$ php --ri swoole

swoole

swoole support => enabled
Version => 4.2.6
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?

```
$ uname -a
Linux localhost.localdomain 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ php -v
PHP 7.2.10 (cli) (built: Sep 15 2018 07:10:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies

$ gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array
--disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux                  
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)
```

**Comment by mysteriouss** [comment]
ok, taskwait 第2个参数是等待时间，所以不能省略？

**Comment by matyhtf** [comment]
@mysteriouss 可以传入 -1 表示永不超时。参数顺序无法变更，这会产生 API 不兼容性
