### ISSUE TITLE
core dump in swoole 4.2.9 with php 7.2.11 

### ISSUE THREAD

**Issue by mangowong** [swoole/swoole-src#2159]
Please answer these questions before submitting your issue. Thanks!

1、core dump info 
  我们的业务使用了协程的Httpclient以及Hook  SOCK，当使用HttpClinet去调用一个第三方接口服务，第三方接口服务部署在内网时，没碰到 coredump 的情况，当第三方接口服务部署到外网时，发现coredump出现概率比较高，不压测的话，没有碰到问题。由于业务代码比较复杂，暂时未能提供稳定复现的DEMO。
```shell
#0  swoole::Coroutine::resume (this=0x0) at /root/rpmbuild/BUILD/swoole-src-4.2.9/src/coroutine/base.cc:68
#1  0x00007f6a65b85c4d in socket_onRead (reactor=0x2d26df0, event=Unhandled dwarf expression opcode 0xf3
) at /root/rpmbuild/BUILD/swoole-src-4.2.9/src/coroutine/socket.cc:614
#2  0x00007f6a65bae76b in swReactorEpoll_wait (reactor=0x2d26df0, timeo=Unhandled dwarf expression opcode 0xf3
) at /root/rpmbuild/BUILD/swoole-src-4.2.9/src/reactor/epoll.c:283
#3  0x00007f6a65ba23ab in swWorker_loop (factory=Unhandled dwarf expression opcode 0xf3
) at /root/rpmbuild/BUILD/swoole-src-4.2.9/src/network/worker.c:799
#4  0x00007f6a65b916e4 in swManager_spawn_worker (factory=0x2c05d78, worker_id=11) at /root/rpmbuild/BUILD/swoole-src-4.2.9/src/network/manager.c:508
#5  0x00007f6a65b91ede in swManager_start (factory=Unhandled dwarf expression opcode 0xf3
) at /root/rpmbuild/BUILD/swoole-src-4.2.9/src/network/manager.c:144
#6  0x00007f6a65b88fda in swFactoryProcess_start (factory=0x2c05d78) at /root/rpmbuild/BUILD/swoole-src-4.2.9/src/factory/process.c:86
#7  0x00007f6a65b9cae3 in swServer_start (serv=0x2c058e0) at /root/rpmbuild/BUILD/swoole-src-4.2.9/src/network/server.c:757
#8  0x00007f6a65c11caf in zim_swoole_server_start (execute_data=Unhandled dwarf expression opcode 0xf3
) at /root/rpmbuild/BUILD/swoole-src-4.2.9/swoole_server.cc:2749
#9  0x00000000008ae755 in execute_ex ()
#10 0x00000000008af7c3 in zend_execute ()
#11 0x000000000080a1b4 in zend_execute_scripts ()
#12 0x00000000007a9f30 in php_execute_script ()
#13 0x00000000008b1ae5 in do_cli ()
#14 0x000000000043f5df in main ()
 
``` 

2. What version of Swoole are you using (show your `php --ri swoole`)?

```shell

swoole

swoole support => enabled
Version => 4.2.9
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.1e-fips 11 Feb 2013
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

```

3. What is your machine environment used (including version of kernel & php & gcc) ?

```shell
 CentOS release 6.7 (Final) 2.6.32-573.el6.x86_64
 PHP 7.2.11 
GCC  version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)
```

**Comment by twose** [comment]
外网请求是否使用了SSL

**Comment by mangowong** [comment]
没有

**Comment by mangowong** [comment]
> 外网请求是否使用了SSL

没有使用

**Comment by matyhtf** [comment]
请加一下我的 QQ：12811247

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/15b4abed203779361e6539e9960922435d7c8674

fixed
