### ISSUE TITLE
使用\Swoole\Process\Pool子进程创建Client问题

### ISSUE THREAD

**Issue by loyating** [swoole/swoole-src#2173]
使用\Swoole\Process\Pool创建N个进程，其中一个子进程 创建了 swoole_client TCP长连只负责接收服务器推送的消息，其它子进程负责数据处理
现在出现一个问题：在跑一段时间后client进程，不确定在什么情况就卡在epoll_wait，收不到任何消息了
strace：epoll_wait(5,
tcpdump 抓包接收消息正常
重启这个子进程后又正常，该如何定位一下这个问题？

**Comment by loyating** [comment]
```sh
(gdb) bt
#0  0x00007f8979b089f3 in __epoll_wait_nocancel () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f8971a7c5d8 in swReactorEpoll_wait (reactor=0x2ecb2a0, timeo=<optimized out>) at /tmp/pear/temp/swoole/src/reactor/epoll.c:226
#2  0x00007f8971a982d2 in php_swoole_event_wait () at /tmp/pear/temp/swoole/swoole_event.c:268
#3  0x00007f8971abb9cb in php_swoole_process_pool_onWorkerStart (pool=<optimized out>, worker_id=0) at /tmp/pear/temp/swoole/swoole_process_pool.c:122
#4  0x00007f8971a630cd in swProcessPool_spawn (pool=pool@entry=0x7f8972c818c0, worker=0x7f89711b7210) at /tmp/pear/temp/swoole/src/network/process_pool.c:361
#5  0x00007f8971a6322c in swProcessPool_start (pool=pool@entry=0x7f8972c818c0) at /tmp/pear/temp/swoole/src/network/process_pool.c:184
#6  0x00007f8971ababe0 in zim_swoole_process_pool_start (execute_data=<optimized out>, return_value=0x7fff6d5d2ad0) at /tmp/pear/temp/swoole/swoole_process_pool.c:434
#7  0x0000000000923596 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /home/zzt/Downloads/php-7.2.5/Zend/zend_vm_execute.h:907
#8  execute_ex (ex=0x4) at /home/zzt/Downloads/php-7.2.5/Zend/zend_vm_execute.h:59749
#9  0x000000000092485e in zend_execute (op_array=0x7f8972c802a0, op_array@entry=0x7f8972c73ec0, return_value=0x0, return_value@entry=0x7f8972c1c440)
    at /home/zzt/Downloads/php-7.2.5/Zend/zend_vm_execute.h:63760
#10 0x0000000000873223 in zend_execute_scripts (type=type@entry=8, retval=0x7f8972c1c440, retval@entry=0x0, file_count=file_count@entry=3) at /home/zzt/Downloads/php-7.2.5/Zend/zend.c:1496
#11 0x000000000080e7f0 in php_execute_script (primary_file=primary_file@entry=0x7fff6d5d50d0) at /home/zzt/Downloads/php-7.2.5/main/main.c:2590
#12 0x0000000000926c39 in do_cli (argc=3, argv=0x2c7aa50) at /home/zzt/Downloads/php-7.2.5/sapi/cli/php_cli.c:1011
#13 0x000000000043bf0c in main (argc=3, argv=0x2c7aa50) at /home/zzt/Downloads/php-7.2.5/sapi/cli/php_cli.c:1404
(gdb) 
#0  0x00007f8979b089f3 in __epoll_wait_nocancel () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f8971a7c5d8 in swReactorEpoll_wait (reactor=0x2ecb2a0, timeo=<optimized out>) at /tmp/pear/temp/swoole/src/reactor/epoll.c:226
#2  0x00007f8971a982d2 in php_swoole_event_wait () at /tmp/pear/temp/swoole/swoole_event.c:268
#3  0x00007f8971abb9cb in php_swoole_process_pool_onWorkerStart (pool=<optimized out>, worker_id=0) at /tmp/pear/temp/swoole/swoole_process_pool.c:122
#4  0x00007f8971a630cd in swProcessPool_spawn (pool=pool@entry=0x7f8972c818c0, worker=0x7f89711b7210) at /tmp/pear/temp/swoole/src/network/process_pool.c:361
#5  0x00007f8971a6322c in swProcessPool_start (pool=pool@entry=0x7f8972c818c0) at /tmp/pear/temp/swoole/src/network/process_pool.c:184
#6  0x00007f8971ababe0 in zim_swoole_process_pool_start (execute_data=<optimized out>, return_value=0x7fff6d5d2ad0) at /tmp/pear/temp/swoole/swoole_process_pool.c:434
#7  0x0000000000923596 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /home/zzt/Downloads/php-7.2.5/Zend/zend_vm_execute.h:907
#8  execute_ex (ex=0x4) at /home/zzt/Downloads/php-7.2.5/Zend/zend_vm_execute.h:59749
#9  0x000000000092485e in zend_execute (op_array=0x7f8972c802a0, op_array@entry=0x7f8972c73ec0, return_value=0x0, return_value@entry=0x7f8972c1c440)
    at /home/zzt/Downloads/php-7.2.5/Zend/zend_vm_execute.h:63760
#10 0x0000000000873223 in zend_execute_scripts (type=type@entry=8, retval=0x7f8972c1c440, retval@entry=0x0, file_count=file_count@entry=3) at /home/zzt/Downloads/php-7.2.5/Zend/zend.c:1496
#11 0x000000000080e7f0 in php_execute_script (primary_file=primary_file@entry=0x7fff6d5d50d0) at /home/zzt/Downloads/php-7.2.5/main/main.c:2590
#12 0x0000000000926c39 in do_cli (argc=3, argv=0x2c7aa50) at /home/zzt/Downloads/php-7.2.5/sapi/cli/php_cli.c:1011
#13 0x000000000043bf0c in main (argc=3, argv=0x2c7aa50) at /home/zzt/Downloads/php-7.2.5/sapi/cli/php_cli.c:1404
```
服务器模拟数据发送，每秒发送五百条数据，当收不到数据后，打印的调用栈信息，重连服务器之后还是会出现这个问题

**Comment by loyating** [comment]
我自己的问题
有多个服务，产生了数据混乱
