### ISSUE TITLE
swoole crashed after run 200+ days

### ISSUE THREAD

**Issue by Does666** [swoole/swoole-src#2190]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
We use swoole as a websocket server. It has been running steadily for more than 200 days. But recently it crashed. When it crashed, it cannot accept new Socket connection.

2. What did you expect to see?
Run stable always.

3. What did you see instead?
warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time
Core was generated by `php main.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f76016160c9 in ?? () from /lib64/libssl.so.10
(gdb) where
#0  0x00007f76016160c9 in ?? () from /lib64/libssl.so.10
#1  0x00007f7601616e7f in ssl3_setup_write_buffer () from /lib64/libssl.so.10
#2  0x00007f7601616ee8 in ssl3_setup_buffers () from /lib64/libssl.so.10
#3  0x00007f7601618135 in ssl23_get_client_hello () from /lib64/libssl.so.10
#4  0x00007f7601618ac8 in ssl23_accept () from /lib64/libssl.so.10
#5  0x00007f75fdee0139 in swSSL_accept () from /usr/lib64/swoole.so
#6  0x00007f75fded30fc in swReactorThread_onRead () from /usr/lib64/swoole.so
#7  0x00007f75fdec886f in swReactorEpoll_wait () from /usr/lib64/swoole.so
#8  0x00007f75fded4f05 in swReactorThread_loop () from /usr/lib64/swoole.so
#9  0x00007f7600c2edf3 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f7600f393dd in clone () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007f76016160c9 in ?? () from /lib64/libssl.so.10
No symbol table info available.
#1  0x00007f7601616e7f in ssl3_setup_write_buffer () from /lib64/libssl.so.10
No symbol table info available.
#2  0x00007f7601616ee8 in ssl3_setup_buffers () from /lib64/libssl.so.10
No symbol table info available.
#3  0x00007f7601618135 in ssl23_get_client_hello () from /lib64/libssl.so.10
No symbol table info available.
#4  0x00007f7601618ac8 in ssl23_accept () from /lib64/libssl.so.10
No symbol table info available.
#5  0x00007f75fdee0139 in swSSL_accept () from /usr/lib64/swoole.so
No symbol table info available.
#6  0x00007f75fded30fc in swReactorThread_onRead () from /usr/lib64/swoole.so
No symbol table info available.
#7  0x00007f75fdec886f in swReactorEpoll_wait () from /usr/lib64/swoole.so
No symbol table info available.
#8  0x00007f75fded4f05 in swReactorThread_loop () from /usr/lib64/swoole.so
No symbol table info available.
#9  0x00007f7600c2edf3 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#10 0x00007f7600f393dd in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb) f 10
#10 0x00007f7600f393dd in clone () from /lib64/libc.so.6
(gdb) i locals
No symbol table info available.

4. What version of Swoole are you using (show your `php --ri swoole`)?
1.9.14

5. What is your machine environment used (including version of kernel & php & gcc) ?
php -v
PHP 5.5.38 (cli) (built: Jul  5 2017 01:20:39) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
#gcc -v
sh: gcc: not found
#uname -a
Linux localhost 3.10.20-rt14+ #1 SMP Wed Dec 5 09:14:46 CST 2018 x86_64 GNU/Linux

**Comment by Does666** [comment]
The same with https://github.com/swoole/swoole-src/issues/1160
