### ISSUE TITLE
v4.2.12-Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by loyating** [swoole/swoole-src#2433]
1. What did you do? If possible, provide a simple script for reproducing the error.
    > 请详细描述问题的产生过程，贴出相关的代码，最好能提供一份可稳定重现的简单脚本代码。

    做了一个简单的测试如下：
    ```php
    //Server.php
    $server = new swoole_server("127.0.0.1", 9510, SWOOLE_SOCK_TCP);
    $server->set([
        'dispatch_mode' => 7
    ]);
    
    $server->on('start', function ($server) {
        echo 'started.', PHP_EOL;
    });
    $server->on('connect', function ($server, $fd) {
        echo "connection open: {$fd}\n";
    });
    $server->on('receive', function ($server, $fd, $reactor_id, $data) {
        $server->send($fd, "Swoole: {$data}");
    });
    $server->on('close', function ($server, $fd) {
        echo "connection close: {$fd}\n";
    });
    $server->start();
    ```
    ```php
    //Client.php
    for ($i = 0; $i < 100; $i++)
    {
        go(function () use ($i) {
        
            $cid = co::getCid();
    
            $client = new swoole_client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_ASYNC);
            
            $client->on("connect", function ($cli) use ($i) {
                swoole_timer_tick(100, function () use ($cli, $i) {
                    $cli->send($i);
                });
            });
            $client->on("receive", function ($cli, $data) use ($cid) {
                echo 'Receive-length(' . $cid . '):', $data, PHP_EOL;
            });
            $client->on("error", function ($cli) {
                echo "connect failed\n";
            });
            $client->on("close", function ($cli) {
                echo "connection close\n";
            });
            
            $client->connect("127.0.0.1", 9510, 0.5);
            
        });
    }```

2. What did you expect to see?
    > 期望的结果是什么？
    
    server设置dispatch_mode为7的时候希望正常运行，看到对应的结果；
    4.2.13中测试没有问题

3. What did you see instead?
    > 实际运行的结果是什么？
    
    4.2.12必现
    ```bash
    ...
    connection open: 99
    connection open: 100
    [2019-03-15 11:21:13 *4615.0]	ERROR	swStream_new(:96): failed to connect to [/tmp/swoole.4615.sock:0]. Error: Resource temporarily unavailable[11].
    [2019-03-15 11:21:13 *4615.0]	ERROR	swReactorEpoll_wait(:261): EPOLLIN handle failed. fd=44. Error: Resource temporarily unavailable[11].
    [2019-03-15 11:21:13 *4615.0]	ERROR	swStream_new(:96): failed to connect to [/tmp/swoole.4615.sock:0]. Error: Resource temporarily unavailable[11].
    Segmentation fault (core dumped)
    ```

4. What version of Swoole are you using (`php --ri swoole`)?
    > 你的版本? 贴出 `php --ri swoole` 所打印的内容	
    4.2.12下
    ```bash
    swoole
    
    Swoole => enabled
    Author => Swoole Team <team@swoole.com>
    Version => 4.2.12
    Built => Jan 21 2019 16:48:36
    coroutine => enabled
    epoll => enabled
    eventfd => enabled
    signalfd => enabled
    cpu_affinity => enabled
    spinlock => enabled
    rwlock => enabled
    openssl => OpenSSL 1.1.0g  2 Nov 2017
    pcre => enabled
    zlib => enabled
    mutex_timedlock => enabled
    pthread_barrier => enabled
    futex => enabled
    mysqlnd => enabled
    async_redis => enabled
    
    Directive => Local Value => Master Value
    swoole.enable_coroutine => On => On
    swoole.display_errors => On => On
    swoole.use_shortname => On => On
    swoole.fast_serialize => Off => Off
    swoole.unixsock_buffer_size => 8388608 => 8388608
    ```
5. What is your machine environment used (including the version of kernel & php & gcc)?
    > 你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？	
    > 可以使用`uname -a`, `php -v`, `gcc -v` 命令打印
    ```bash
    uname -a
    Linux zzt-VirtualBox 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    
    php -v
    PHP 7.2.13 (cli) (built: Dec 26 2018 10:38:26) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    
    gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
    OFFLOAD_TARGET_NAMES=nvptx-none
    OFFLOAD_TARGET_DEFAULT=1
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
    ```

**Comment by loyating** [comment]
```bash
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...done.
[New LWP 4615]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php Server.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___libc_free (mem=0x600000000) at malloc.c:3103
3103	malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x600000000) at malloc.c:3103
#1  0x00007f6317a811aa in swString_free (str=0x5613cb806950)
    at /tmp/pear/temp/swoole/include/swoole.h:744
#2  swStream_free (stream=0x5613cb806c40)
    at /tmp/pear/temp/swoole/src/network/stream.c:68
#3  0x00007f6317a81359 in swStream_new (dst_host=<optimized out>, 
    dst_port=dst_port@entry=0, type=type@entry=6)
    at /tmp/pear/temp/swoole/src/network/stream.c:97
#4  0x00007f6317a7c513 in swReactorThread_dispatch (
    conn=conn@entry=0x7f63164b6418, data=data@entry=0x7fff17eb1d44 "36", 
    length=length@entry=2)
    at /tmp/pear/temp/swoole/src/network/reactor_thread.c:1187
#5  0x00007f6317a7536e in swPort_onRead_raw (reactor=0x5613caf95038, 
    port=<optimized out>, event=0x7fff17eb5e10)
    at /tmp/pear/temp/swoole/src/network/port.c:259
#6  0x00007f6317a79c86 in swReactorThread_onRead (reactor=0x5613caf95038, 
    event=0x7fff17eb5e10)
    at /tmp/pear/temp/swoole/src/network/reactor_thread.c:678
#7  0x00007f6317a91ac6 in swReactorEpoll_wait (reactor=0x5613caf95038, 
    timeo=<optimized out>) at /tmp/pear/temp/swoole/src/reactor/epoll.c:258
#8  0x00007f6317a78d4d in swReactorProcess_loop (pool=<optimized out>, 
    worker=0x7f6316f87638)
    at /tmp/pear/temp/swoole/src/network/reactor_process.c:400
---Type <return> to continue, or q <return> to quit---
#9  0x00007f6317a79732 in swReactorProcess_start (serv=<optimized out>)
    at /tmp/pear/temp/swoole/src/network/reactor_process.c:122
#10 0x00007f6317a8006d in swServer_start (serv=serv@entry=0x5613caf94830)
    at /tmp/pear/temp/swoole/src/network/server.c:661
#11 0x00007f6317afecdc in zim_swoole_server_start (
    execute_data=0x7f6318c1c160, return_value=0x7fff17eb5ff0)
    at /tmp/pear/temp/swoole/swoole_server.cc:3122
#12 0x00005613c982893b in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER ()
    at /data/php-7.2.13/Zend/zend_vm_execute.h:907
#13 execute_ex (ex=0x600000000)
    at /data/php-7.2.13/Zend/zend_vm_execute.h:59765
#14 0x00005613c9828b89 in zend_execute (
    op_array=op_array@entry=0x7f6318c802a0, return_value=0x0, 
    return_value@entry=0x7f6318c923c0)
    at /data/php-7.2.13/Zend/zend_vm_execute.h:63776
#15 0x00005613c97784f2 in zend_execute_scripts (type=type@entry=8, 
    retval=0x7f6318c923c0, retval@entry=0x0, file_count=415350832, 
    file_count@entry=3) at /data/php-7.2.13/Zend/zend.c:1502
#16 0x00005613c9714840 in php_execute_script (primary_file=0x7fff17eb85f0)
    at /data/php-7.2.13/main/main.c:2590
#17 0x00005613c982af9c in do_cli (argc=2, argv=0x5613cad0e310)
    at /data/php-7.2.13/sapi/cli/php_cli.c:1011
#18 0x00005613c934117b in main (argc=2, argv=0x5613cad0e310)
---Type <return> to continue, or q <return> to quit---
    at /data/php-7.2.13/sapi/cli/php_cli.c:1403
(gdb) 
(gdb) f 1
#1  0x00007f6317a811aa in swString_free (str=0x5613cb806950)
    at /tmp/pear/temp/swoole/include/swoole.h:744
744	/tmp/pear/temp/swoole/include/swoole.h: No such file or directory.
(gdb) f 0
#0  __GI___libc_free (mem=0x600000000) at malloc.c:3103
3103	malloc.c: No such file or directory.
(gdb) 
```

**Comment by twose** [comment]
我的理解没错的话, 意思是新版本没问题? 旧版本必现?
那就是已修复的问题了

**Comment by loyating** [comment]
是的，4.2.13  4.3.0 4.3.1 都没问题
