### ISSUE TITLE
"A bug occurred in Swoole-v4.5.2, please report it"

### ISSUE THREAD

**Issue by windylaugit** [swoole/swoole-src#3353]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
使用IMI框架（一个基于Swoole的框架）初始化了一个demo-http项目
composer完成之后，启动了项目（此时一切正常）
使用浏览器（chrome）访问项目主页，页面一直loading直至504。此时项目运行日志打印出日志：
```
A bug occurred in Swoole-v4.5.2, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
```
---------seperator----------
做过以下尝试：
1.1 在任意一台服务器或PC上执行 curl (server url) ，均正常。
1.2 在任意一台PC上，用浏览器访问，均报同样错误。
1.3 使用Postman工具测试，报同样错误。
1.4 尝试更换了 swoole版本（4.5.0->4.5.2），报同样错误。（尝试过4.3.6版本，但github上release的4.3.6我无法编译通过。）

2. What did you expect to see?
期望使用浏览器访问，能正常输出结果，而不是504

3. What did you see instead?
实际浏览器504错误码，且服务端日志打印出上述错误提示。

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.5.2

5. What is your machine environment used (including version of kernel & php & gcc) ?
**OS:** CentOS release 7.4  3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**PHP:**  PHP 7.3.17    Zend Engine v3.3.17
**GCC:** gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

----------------------------------------
**_使用gdb调试：_**
```
(gdb) bt
#0  0x00007efe2a7e7eb3 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007efe2029da76 in swReactorEpoll_wait (reactor=0x2abc490, timeo=<optimized out>) at /alidata/download/swoole/swoole-src-4.5.2/src/reactor/epoll.cc:220
#2  0x00007efe202b114b in swoole_event_wait () at /alidata/download/swoole/swoole-src-4.5.2/src/wrapper/event.cc:77
#3  0x00007efe202ac174 in swReactorThread_start (serv=serv@entry=0x2ac7100) at /alidata/download/swoole/swoole-src-4.5.2/src/server/reactor_thread.cc:980
#4  0x00007efe202a4f21 in swServer_start (serv=serv@entry=0x2ac7100) at /alidata/download/swoole/swoole-src-4.5.2/src/server/master.cc:826
#5  0x00007efe203173e1 in zim_swoole_server_start (execute_data=0x7efe26e1e530, return_value=0x7ffe4a9bc320) at /alidata/download/swoole/swoole-src-4.5.2/swoole_server.cc:3085
#6  0x00000000008de198 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /alidata/download/onekey-lnmp/php-7.3.17/Zend/zend_vm_execute.h:984
#7  execute_ex (ex=0x8) at /alidata/download/onekey-lnmp/php-7.3.17/Zend/zend_vm_execute.h:55527
#8  0x00000000008ded38 in zend_execute (op_array=op_array@entry=0x7efe1ec5d660, return_value=return_value@entry=0x7efe26e1e360) at /alidata/download/onekey-lnmp/php-7.3.17/Zend/zend_vm_execute.h:60939
#9  0x0000000000859b64 in zend_execute_scripts (type=type@entry=8, retval=0x7efe26e1e360, retval@entry=0x0, file_count=file_count@entry=3) at /alidata/download/onekey-lnmp/php-7.3.17/Zend/zend.c:1568
#10 0x00000000007fdae0 in php_execute_script (primary_file=primary_file@entry=0x7ffe4a9be720) at /alidata/download/onekey-lnmp/php-7.3.17/main/main.c:2639
#11 0x00000000008e1125 in do_cli (argc=3, argv=0x284cb00) at /alidata/download/onekey-lnmp/php-7.3.17/sapi/cli/php_cli.c:997
#12 0x00000000004516a0 in main (argc=3, argv=0x284cb00) at /alidata/download/onekey-lnmp/php-7.3.17/sapi/cli/php_cli.c:1393
```
**_gdb+zbacktrace：_**
```
(gdb) zbacktrace
[0x7f3a45e1e530] Swoole\Server->start() [internal function]
[0x7f3a45e1e360] Imi\Tool\Tools\Server\Server->start(NULL, NULL, NULL) /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/src/Tool/Tools/Server/Server.php:50 
[0x7f3a45e1dd60] Imi\Tool\Tool->run() /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/src/Tool/Tool.php:131 
[0x7f3a45e1dcf0] Imi\Tool\Listener\Run->handle(object[0x7f3a45e1dd40]) /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/src/Tool/Listener/Run.php:21 
[0x7f3a45e1dc40] Imi\Event\Event->Imi\Event\{closure}(object[0x7f3a45e1dc90]) /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/src/Event/TEvent.php:44 
[0x7f3a45e1d6e0] Imi\Event\Event->trigger("IMI.INITED", array(0)[0x7f3a45e1d740], NULL, "Imi\Event\EventParam") /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/src/Event/TEvent.php:179 
[0x7f3a45e1d630] Imi\Event\Event->trigger("IMI.INITED") /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/src/Event/Event.php:63 
[0x7f3a45e1d4a0] Imi\App->run("ImiApp") /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/src/App.php:110 
[0x7f3a45e1d1d0] class@anonymous->run() /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/bin/imi.php:48 
[0x7f3a45e1d120] (main) /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/bin/imi.php:51 
[0x7f3a45e1d030] (main) /alidata/www/wl-cms/imi/vendor/yurunsoft/imi/bin/imi:16 

```
**_使用valgrind：_**
```
[root@andylau imi]# cat /tmp/valgrind.log 
==30541== Memcheck, a memory error detector
==30541== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==30541== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==30541== Command: vendor/yurunsoft/imi/bin/imi server/start
==30541== Parent PID: 30493
==30541==
```

**Comment by matyhtf** [comment]
没有有效信息。

使用valgrind，你需要重现一次问题，然后把输出的内容发到这里

**Comment by windylaugit** [comment]
> 没有有效信息。
> 
> 使用valgrind，你需要重现一次问题，然后把输出的内容发到这里

sorry! The log is here: https://github.com/windylaugit/wlcms/blob/master/valgrind-log-for-swoole.log

**Comment by windylaugit** [comment]
> 没有有效信息。
> 
> 使用valgrind，你需要重现一次问题，然后把输出的内容发到这里

sorry! the log file is here:
[valgrind.log](https://github.com/swoole/swoole-src/files/4709666/valgrind.log)

**Comment by matyhtf** [comment]
![QQ20200601-0](https://user-images.githubusercontent.com/2017766/83401737-14a98800-a438-11ea-9a36-8e52c1300861.png)
zlib 库存在 bug，升级 zlib 库版本，或者关闭压缩。
