### ISSUE TITLE
[bug?] WARNING check_worker_exit_status: worker#5[pid=2948] abnormal exit, status=0, signal=11 

### ISSUE THREAD

**Issue by cexll** [swoole/swoole-src#3649]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
use `xxtime/flysystem-aliyun-oss`  frequently Requireid:xxx (No problem with the previous test),Happened after  `getExtension` `getSize
`Call to a member function getExtension() on null[55]` , Restart the machine ` **WARNING check_worker_exit_status: worker#5`**
- wsl1 win10-LTSC 2018
- hyperf2.0 
- php 7.4.3 (NTS)
- swoole 4.5.3
```
[2020-09-12 19:27:25 $2912.0]   WARNING check_worker_exit_status: worker#5[pid=2948] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
```
`uploadController.php`
```php
/**
    /**
     * @Inject
     * @var AliyunOSS
     */
    private $oss;

     * @PostMapping(path="")
     * @throws \League\Flysystem\FileNotFoundException
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function upload(RequestInterface $request)
    {
        $file = $request->file('file');
        $suffix = $request->file('file')->getExtension();

        $result = $this->oss->upload($file->getStream(), $suffix);
        return $this->success([
            'url' => $result,
        ]);
    }
```

`AliyunOSS.php`

```php
public function upload($file, $suffix)
    {
        $fileName = md5(time() . time());
        $path = $this->path . '/' . date('Y-m') . '/' . $fileName . '.' . $suffix;

        if ($this->factory->put($path, $file)) {
            $fileSize = $this->factory->getSize($path);
            $ossPath = $this->OSS_PATH . $path;
            return $ossPath;
        }
        return false;
    }
```

2. What did you expect to see?

Can upload pictures

3. What did you see instead?

```
 WARNING http_request_on_body (ERRNO 9010): parse multipart body failed, n=40
[ERROR] Call to a member function getExtension() on null[55] in /mnt/c/code/php/shuidan/runtime/container/proxy/App_Controller_UploadController.proxy.php
[ERROR] #0 /mnt/c/code/php/shuidan/vendor/hyperf/http-server/src/CoreMiddleware.php(161): App\Controller\UploadController->upload()
#1 /mnt/c/code/php/shuidan/vendor/hyperf/http-server/src/CoreMiddleware.php(113): Hyperf\HttpServer\CoreMiddleware->handleFound()
#2 /mnt/c/code/php/shuidan/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(65): Hyperf\HttpServer\CoreMiddleware->process()
#3 /mnt/c/code/php/shuidan/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest()
#4 /mnt/c/code/php/shuidan/app/Middleware/UserAuthMiddleware.php(39): Hyperf\Dispatcher\HttpRequestHandler->handle()
#5 /mnt/c/code/php/shuidan/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(65): App\Middleware\UserAuthMiddleware->process()
#6 /mnt/c/code/php/shuidan/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest()
#7 /mnt/c/code/php/shuidan/vendor/hyperf/validation/src/Middleware/ValidationMiddleware.php(81): Hyperf\Dispatcher\HttpRequestHandler->handle()
#8 /mnt/c/code/php/shuidan/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(65): Hyperf\Validation\Middleware\ValidationMiddleware->process()
#9 /mnt/c/code/php/shuidan/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest()
#10 /mnt/c/code/php/shuidan/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\Dispatcher\HttpRequestHandler->handle()
#11 /mnt/c/code/php/shuidan/vendor/hyperf/http-server/src/Server.php(118): Hyperf\Dispatcher\HttpDispatcher->dispatch()
#12 {main}


[2020-09-12 19:23:18 $2340.0]   WARNING check_worker_exit_status: worker#5[pid=2352] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
cexll@DESKTOP-ESJUL4O:/mnt/c/code/php/shuidan$ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.3
Built => Sep  8 2020 21:13:21
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1f  31 Mar 2020
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
cexll@DESKTOP-ESJUL4O:/mnt/c/code/php/shuidan$ uname -a && php -v && gcc -v
Linux DESKTOP-ESJUL4O 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
```

> I try to reinstall the system

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by cexll** [comment]
pecl install swoole

**Comment by sy-records** [comment]
用hyperf的文件系统组件试下

**Comment by cexll** [comment]
> 用hyperf的文件系统组件试下

恩,是用的hyperf的文件系统组件

**Comment by sy-records** [comment]
hyperf的文件系统不是这么用的吧，oss是跑过的https://hyperf.wiki/2.0/#/zh-cn/filesystem?id=使用

coredump的问题你可以上Linux试下能复现吗，可能wsl的bug

**Comment by cexll** [comment]
e, 我前天测试是没问题的, 可以上传
