### ISSUE TITLE
php8 ssl core dump

### ISSUE THREAD

**Issue by amuluowin** [swoole/swoole-src#3900]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
**use guzzle to request a https domain**

```shell
Thread 1 "php" received signal SIGPIPE, Broken pipe.
__GI___libc_write (nbytes=293, buf=0x555556367ae0, fd=42) at ../sysdeps/unix/sysv/linux/write.c:26
26      ../sysdeps/unix/sysv/linux/write.c: No such file or directory.
(gdb) bt
#0  __GI___libc_write (nbytes=293, buf=0x555556367ae0, fd=42) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __GI___libc_write (fd=42, buf=0x555556367ae0, nbytes=293) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007ffff79c6399 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007ffff79c158e in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007ffff79c05a4 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#5  0x00007ffff79c0a67 in BIO_write () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#6  0x00007ffff79bede1 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007ffff79c0f3a in BIO_ctrl () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#8  0x00007ffff7c3d8f1 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007ffff7c422bf in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007ffff7c3cecb in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#11 0x00007ffff7c28d78 in SSL_do_handshake () from /lib/x86_64-linux-gnu/libssl.so.1.1
#12 0x00007ffff51cd511 in swoole::network::Socket::ssl_connect (this=0x555556093da0)
    at /mnt/c/Users/Administrator/Desktop/swoole/src/network/socket.cc:1058
#13 0x00007ffff51bbff5 in swoole::coroutine::Socket::ssl_handshake (this=this@entry=0x555556093b10)
    at /mnt/c/Users/Administrator/Desktop/swoole/src/coroutine/socket.cc:1281
#14 0x00007ffff5187149 in socket_enable_crypto (stream=0x7fffd6c3a620, cparam=0x55555c6d6430, sock=0x555556093b10)
    at /mnt/c/Users/Administrator/Desktop/swoole/ext-src/swoole_runtime.cc:639
#15 socket_set_option (stream=0x7fffd6c3a620, option=<optimized out>, value=<optimized out>, ptrparam=0x55555c6d6430)
    at /mnt/c/Users/Administrator/Desktop/swoole/ext-src/swoole_runtime.cc:843
#16 0x00005555557cb5b1 in _php_stream_set_option ()
#17 0x00005555557d5725 in php_stream_xport_crypto_enable ()
#18 0x000055555579d2c9 in ?? ()
#19 0x00005555557a09d2 in ?? ()
#20 0x00005555557cced7 in _php_stream_open_wrapper_ex ()
#21 0x000055555575780d in ?? ()
#22 0x00007ffff23d830c in ?? () from /usr/lib/php/20200930/phar.so
#23 0x000055555587f4b1 in execute_ex ()
#24 0x00007ffff512dfbb in swoole::PHPCoroutine::main_func (arg=0x55555c4d72c0)
--Type <RET> for more, q to quit, c to continue without paging--
    at /mnt/c/Users/Administrator/Desktop/swoole/ext-src/swoole_coroutine.cc:655
#25 0x00007ffff51b0bd1 in std::function<void (void*)>::operator()(void*) const (__args#0=<optimized out>,
    this=0x555556093ab0) at /usr/include/c++/9/bits/std_function.h:683
#26 swoole::coroutine::Context::context_func (arg=0x555556093ab0)
    at /mnt/c/Users/Administrator/Desktop/swoole/src/coroutine/context.cc:136
#27 0x00007ffff520f8e1 in make_fcontext ()
    at /mnt/c/Users/Administrator/Desktop/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#28 0x0000000000000000 in ?? ()
```

2. What did you expect to see?
not core dump

3. What did you see instead?
run success

4. What version of Swoole are you using (show your `php --ri swoole`)?

```shell
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.9
Built => Nov 28 2020 09:56:15
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```shell
Linux Albert 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```php
PHP 8.0.0 (cli) (built: Nov 27 2020 12:26:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
```
```shell
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
```

**Comment by amuluowin** [comment]
This problem occurs in the PHP8-JIT,the jit config is

```php
zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=1
opcache.jit=1255
opcache.jit_buffer_size=128M
opcache.jit=tracing
opcache.jit_hot_func=64
opcache.jit_hot_loop=32
```

This is the valgrind log file
[v.log](https://github.com/swoole/swoole-src/files/5614145/v.log)

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/dc7aa6a855c026341dbc1acdce065058d26e3135
