### ISSUE TITLE
segmentation fault in 4.5.9

### ISSUE THREAD

**Issue by Appla** [swoole/swoole-src#3906]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
<?php

\Swoole\Timer::tick(1000, fn() => printf('[%d] Running in Timer::tick%s', \Swoole\Coroutine::getCid() ,\PHP_EOL));
\Swoole\Event::cycle(fn() => printf('[%d] Running in event cycle!!!%s', \Swoole\Coroutine::getCid() , \PHP_EOL));
\Swoole\Coroutine::create(function(){
   \Swoole\Coroutine\System::sleep(10);
   \Swoole\Event::exit();
});
\Swoole\Event::wait();

```

2. What did you expect to see?
```
[-1] Running in event cycle!!!
[2] Running in Timer::tick
[-1] Running in event cycle!!!
[3] Running in Timer::tick
...
```

3. What did you see instead?
```
segmentation fault (core dumped) 


//core dump bt

#0  0x00007f6520158f58 in sw_zend_fci_cache_discard (fci_cache=0x7369687424202020) at /path/to/swoole-src/ext-src/php_swoole.h:1067
#1  sw_zend_fci_cache_free (fci_cache=0x7369687424202020) at /path/to/swoole-src/ext-src/php_swoole.h:1067
#2  0x00007f652020e57b in std::function<void (void*)>::operator()(void*) const (__args#0=<optimized out>, this=0x7ffc5c9fea60) at /usr/include/c++/9/bits/std_function.h:683
#3  swoole::CallbackManager::execute (this=0x55cb75f85d50) at /path/to/swoole-src/include/swoole_reactor.h:63
#4  swoole::Reactor::<lambda(swoole::Reactor*)>::operator() (__closure=<optimized out>, reactor=<optimized out>) at /path/to/swoole-src/src/reactor/base.cc:111
#5  std::_Function_handler<void(swoole::Reactor*), swoole::Reactor::Reactor(int, swoole::Reactor::Type)::<lambda(swoole::Reactor*)> >::_M_invoke(const std::_Any_data &, swoole::Reactor *&&) (
    __functor=..., __args#0=<optimized out>) at /usr/include/c++/9/bits/std_function.h:300
#6  0x00007f652020e2c5 in std::function<void (swoole::Reactor*)>::operator()(swoole::Reactor*) const (__args#0=<optimized out>, this=0x55cb75e2b7d8) at /usr/include/c++/9/bits/std_function.h:683
#7  swoole::Reactor::execute_end_callbacks (this=0x55cb75e2c3e0, timedout=timedout@entry=true) at /path/to/swoole-src/src/reactor/base.cc:363
#8  0x00007f652020fc11 in swoole::ReactorEpoll::wait (this=0x55cb75e2b740, timeo=<optimized out>) at /path/to/swoole-src/src/reactor/epoll.cc:209
#9  0x00007f652015afbf in swoole::Reactor::wait (this=<optimized out>, timeout=0x0) at /path/to/swoole-src/include/swoole_reactor.h:157
#10 php_swoole_event_wait () at /path/to/swoole-src/ext-src/swoole_event.cc:286
#11 php_swoole_event_wait () at /path/to/swoole-src/ext-src/swoole_event.cc:257
#12 0x000055cb753bfb89 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at ./Zend/zend_vm_execute.h:1618
#13 execute_ex (ex=0x7369687424202020) at ./Zend/zend_vm_execute.h:53817
#14 0x000055cb753c114b in zend_execute (op_array=0x7f6521476d20, return_value=0x0) at ./Zend/zend_vm_execute.h:57913
#15 0x000055cb753381ec in zend_execute_scripts (type=type@entry=8, retval=0x7f65214a5780, retval@entry=0x0, file_count=557920288, file_count@entry=3) at ./Zend/zend.c:1665
#16 0x000055cb752d7ed0 in php_execute_script (primary_file=<optimized out>) at ./main/main.c:2617
#17 0x000055cb753c3282 in do_cli (argc=2, argv=0x55cb75d08ac0) at ./sapi/cli/php_cli.c:961
#18 0x000055cb7519f938 in main (argc=2, argv=0x55cb75d08ac0) at ./sapi/cli/php_cli.c:1356
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
 php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.9
Built => Dec  1 2020 10:57:40
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1h  22 Sep 2020
http2 => enabled
json => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```

PHP 7.4.11 (cli) (built: Oct  6 2020 10:34:39) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
---------------
can be reproduced both
Linux debian 5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux
Linux ubuntu 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

sometimes can be reproduced on centos 7.9
```

**Comment by Appla** [comment]
I found it out, another uninitialized POD caused problem.
