### ISSUE TITLE
WARNING check_worker_exit_status: worker#3[pid=16582] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by leocavalcante** [swoole/swoole-src#3966]
#### Snippet
```php
<?php declare(strict_types=1);

$server = new \Swoole\Http\Server('localhost', 9051);

$server->on('request', static function (\Swoole\Http\Request $request, \Swoole\Http\Response $response): void {
    $response->end();

    $total = count(iterator_to_array(\Swoole\Coroutine::list()));
    echo "There are $total coroutines\n";

    \Swoole\Coroutine::create(static function (): void {
        $cid = \Swoole\Coroutine::getCid();
        $i = random_int(1, 100);

        while ($i <= 75) {
            echo "#$cid still alive ($i) from not ref from request object\n";
            \Swoole\Coroutine::sleep(1);
            $i = random_int(1, 100);
        }

        echo "\$i is $i [closing $cid]\n";
    });
});

$server->start();
```

#### Expected
```zsh
➜  swoole-test (master) ✗ php index2.php
There are 1 coroutines
#2 still alive (64) from not ref from request object
#2 still alive (34) from not ref from request object
#2 still alive (12) from not ref from request object
#2 still alive (59) from not ref from request object
#2 still alive (14) from not ref from request object
#2 still alive (71) from not ref from request object
#2 still alive (10) from not ref from request object
$i is 80 [closing 2]
```

#### Actual
```zsh
➜  swoole-test (master) ✗ php index2.php
There are 1 coroutines
#2 still alive (64) from not ref from request object
#2 still alive (34) from not ref from request object
#2 still alive (12) from not ref from request object
#2 still alive (59) from not ref from request object
#2 still alive (14) from not ref from request object
#2 still alive (71) from not ref from request object
#2 still alive (10) from not ref from request object
$i is 80 [closing 2]
[2020-12-29 14:09:25 $16574.0]  WARNING check_worker_exit_status: worker#3[pid=16582] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.10, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
```

```bash
➜  ~ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.10
Built => Dec 29 2020 13:33:41
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1i  8 Dec 2020
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.display_errors => On => On
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_shortname => On => On
```

```bash
➜  ~ php -v
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
``` 

```bash
➜  ~ uname -a
Linux LCPC 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sy-records** [comment]
I wasn't able to reproduce the question, can you provide some other information? https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md#coredump

**Comment by leocavalcante** [comment]
Sure. `gdb` output:
```gdb
#0  0x00007ffff77485ce in epoll_wait (epfd=13, events=0x555555dedec0, maxevents=maxevents@entry=4096, timeout=999) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00007ffff31cda06 in swoole::ReactorEpoll::wait (this=0x555555dccd60, timeo=<optimized out>) at /home/leo/projects/swoole-src/include/swoole_reactor.h:259
#2  0x00007ffff31e6194 in swoole::Reactor::wait (this=<optimized out>, timeout=0x0) at /home/leo/projects/swoole-src/include/swoole_reactor.h:157
#3  swoole_event_wait () at /home/leo/projects/swoole-src/src/wrapper/event.cc:81
#4  0x00007ffff31e0623 in swoole::Server::start_reactor_threads (this=this@entry=0x555555dccf10) at /home/leo/projects/swoole-src/src/server/reactor_thread.cc:816
#5  0x00007ffff31d8b8d in swoole::Server::start (this=this@entry=0x555555dccf10) at /home/leo/projects/swoole-src/src/server/master.cc:619
#6  0x00007ffff31812af in zim_swoole_server_start (execute_data=0x7ffff54130e0, return_value=0x7fffffff9d48) at /home/leo/projects/swoole-src/ext-src/swoole_server.cc:2650
#7  0x0000555555653236 in ?? ()
#8  0x000055555587c933 in execute_ex ()
#9  0x00007ffff33fa91c in nr_php_execute_file () at /home/hudson/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:909
#10 nr_php_execute_enabled () at /home/hudson/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1103
#11 0x00007ffff33fb102 in nr_php_execute () at /home/hudson/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1337
#12 0x000055555588404b in zend_execute ()
#13 0x00005555557fa7fc in zend_execute_scripts ()
#14 0x000055555579a000 in php_execute_script ()
#15 0x0000555555886182 in ?? ()
#16 0x0000555555661e38 in ?? ()
#17 0x00007ffff764d0b3 in __libc_start_main (main=0x555555661a30, argc=2, argv=0x7fffffffdac8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdab8) at ../csu/libc-start.c:308
#18 0x0000555555661fde in _start ()
```
```gdb
(gdb) f 0
#0  0x00007ffff77485ce in epoll_wait (epfd=13, events=0x555555dedec0, maxevents=maxevents@entry=4096, timeout=999) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
30      ../sysdeps/unix/sysv/linux/epoll_wait.c: No such file or directory.
(gdb) f 1
#1  0x00007ffff31cda06 in swoole::ReactorEpoll::wait (this=0x555555dccd60, timeo=<optimized out>) at /home/leo/projects/swoole-src/include/swoole_reactor.h:259
259             return defer_tasks == nullptr ? timeout_msec : 0;
(gdb) f 2
#2  0x00007ffff31e6194 in swoole::Reactor::wait (this=<optimized out>, timeout=0x0) at /home/leo/projects/swoole-src/include/swoole_reactor.h:157
157             return impl->wait(timeout);
(gdb) f 3
#3  swoole_event_wait () at /home/leo/projects/swoole-src/src/wrapper/event.cc:81
81              retval = SwooleTG.reactor->wait(nullptr);
(gdb) f 4
#4  0x00007ffff31e0623 in swoole::Server::start_reactor_threads (this=this@entry=0x555555dccf10) at /home/leo/projects/swoole-src/src/server/reactor_thread.cc:816
816         return swoole_event_wait();
```

This is branch `v4.5.10` compiled with `--enable-debug` flag.

**Comment by huanghantao** [comment]
Have you install swow?

**Comment by leocavalcante** [comment]
No, never heard of before, is this https://github.com/swow/swow?

**Comment by huanghantao** [comment]
> No, never heard of before, is this https://github.com/swow/swow? Curious: is it related to Swoole or an entire alternative project?

No, swow and Swoole would have conflicts. I had the same problem with you before, so I asked

**Comment by leocavalcante** [comment]
@huanghantao, sorry going away from the issues subject, but I noticed that you and @sy-records, both core contributors to Swoole and others more, are also committing to Swow. Can you please brief a little about this project [Swow]? What are pros and cons against Swoole?

**Comment by huanghantao** [comment]
> @huanghantao, sorry going away from the issues subject, but I noticed that you and @sy-records, both core contributors to Swoole and others more, are also committing to Swow. Can you please brief a little about this project [Swow]? What are pros and cons against Swoole?

Maybe you could ask @twose

**Comment by matyhtf** [comment]
I can't reproduce this problem. Please use valgrind to track memory exception information

```shell
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php
```

**Comment by leocavalcante** [comment]
Lol, weirdly I'm not being able to reproduce it neither anymore.

![image](https://user-images.githubusercontent.com/183722/104449052-c5eecf80-557c-11eb-954e-e41f71be9533.png)

Will check my env and come back with a Valgrind output on any news.
Thank you!
