### ISSUE TITLE
fwrite php://stdout failed

### ISSUE THREAD

**Issue by limingxinleo** [swoole/swoole-src#4001]
```
<?php


\Swoole\Coroutine::set([
    'hook_flags' => SWOOLE_HOOK_ALL
]);

Swoole\Coroutine\run(function () {
    $resource = fopen('php://stdout', 'w');
    \Swoole\Coroutine\parallel(100, function () use ($resource) {
        fwrite($resource, str_repeat('xx', 65535) . PHP_EOL);
    });
});

```

上述代码会导致以下报错

```
Fatal error: Uncaught Swoole\Error: Socket#9 has already been bound to another coroutine#2, writing of the same socket in coroutine#3 at the same time is not allowed in /Users/limingxin/Applications/GitHub/limingxinleo/hyperf2.0-demo/test.php:11
Stack trace:
#0 /Users/limingxin/Applications/GitHub/limingxinleo/hyperf2.0-demo/test.php(11): fwrite(Resource id #5, 'xxxxxxxxxxxxxxx...')
#1 @swoole-src/library/core/Coroutine/functions.php(36): {closure}()
#2 {main}
  thrown in /Users/limingxin/Applications/GitHub/limingxinleo/hyperf2.0-demo/test.php on line 11
PHP Deprecated:  Swoole\Event::rshutdown(): Event::wait() in shutdown function is deprecated in Unknown on line 0

Deprecated: Swoole\Event::rshutdown(): Event::wait() in shutdown function is deprecated in Unknown on line 0
```

**Comment by limingxinleo** [comment]
https://github.com/hyperf/hyperf/issues/3121
https://github.com/hyperf/hyperf/issues/3134
