### ISSUE TITLE
strict_types=1 cause Fatal error when using Swoole\Coroutine::getContext()

### ISSUE THREAD

**Issue by Socengel** [swoole/swoole-src#4051]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
<?php

declare(strict_types=1);

namespace {

    use Co\Context;
    use Swoole\Coroutine;

    if (!function_exists('test_function')) {
        function test_function(?int $cid = null) : Context
        {
            return Coroutine::getContext($cid);
        }
    }

    Co\Run(function () {
        $test = test_function();
    });
}
```

2. What did you expect to see?

Process finished with exit code 0

3. What did you see instead?

```
Fatal error: Uncaught TypeError: Swoole\Coroutine::getContext(): Argument #1 ($cid) must be of type int, null given in /var/www/example/script/test/strict_test.php:13
Stack trace:
#0 /var/www/example/script/test/strict_test.php(13): Swoole\Coroutine::getContext(NULL)
#1 /var/www/example/script/test/strict_test.php(17): test_function()
#2 {main}
  thrown in /var/www/example/script/test/strict_test.php on line 13

Process finished with exit code 255

```

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.2
Built => Feb  6 2021 02:17:05
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
dtls => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux d889ce82ad32 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 GNU/Linux
```
```
PHP 8.0.2 (cli) (built: Feb  6 2021 02:16:18) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies
```
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)
```

**Comment by Yurunsoft** [comment]
I have created the PR

You can modify the code first to make the program run normally:

```php
<?php

declare(strict_types=1);

namespace {

    use Co\Context;
    use Swoole\Coroutine;

    if (!function_exists('test_function')) {
        function test_function(?int $cid = null) : Context
        {
            // modify this line
            return Coroutine::getContext($cid ?? Coroutine::getCid());
        }
    }

    Co\Run(function () {
        $test = test_function();
    });
}
```

**Comment by Yurunsoft** [comment]
```php
Coroutine::getContext(0); // current coroutine context
```

**Comment by sy-records** [comment]
```php
        function test_function(int $cid = 0) : Context
        {
            // modify this line
            return Coroutine::getContext($cid);
        }
```

**Comment by Socengel** [comment]
There is no problem to run code, i misssed documentation mismatch. in documentation and In ide stubs. 
```
    /**
     * @return mixed
     */
    public static function getContext($cid = null)
    {
    }
```

**Comment by sy-records** [comment]
see https://www.swoole.co.uk/docs/modules/swoole-coroutine-getContext

ide stubs : https://github.com/swoole/ide-helper/issues/19#issuecomment-548223274
