### ISSUE TITLE
BUG with Swoole Curl Handler 

### ISSUE THREAD

**Issue by pervozdanniy** [swoole/swoole-src#4061]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
\Swoole\Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL);

$ch = curl_init();
curl_setopt($ch, CURLOPT_PORT, 9200); 
curl_setopt($ch, CURLOPT_URL, 'elastic');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
dump(curl_exec($ch));
```
If I change order of setting  `CURLOPT_PORT` and `CURLOPT_URL` everything works fine. I've faced this issue while using `curl_setopt_array` and was unable to impact options order

2. What did you expect to see?

   Simply working curl

3. What did you see instead?

```
[2021-02-18 16:54:50] local.ERROR: Trying to access array offset on value of type null {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at @swoole-src/library/core/Curl/Handler.php:302)
[stacktrace]
#0 @swoole-src/library/core/Curl/Handler.php(302): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to acces...', '@swoole-src/lib...', 302, Array)
#1 @swoole-src/library/core/Curl/Handler.php(364): Swoole\\Curl\\Handler->setPort(9200)
#2 @swoole-src/library/core/Curl/Handler.php(162): Swoole\\Curl\\Handler->setOption(3, '9200')
#3 @swoole-src/library/ext/curl.php(27): Swoole\\Curl\\Handler->setOpt(3, '9200')
#4 [internal function]: swoole_curl_setopt_array(Object(Swoole\\Curl\\Handler), Array, true)
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.10
Built => Feb 16 2021 15:00:59
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1i  8 Dec 2020
http2 => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `` & `gcc -v`) ?
```
Linux 5608fc807ade 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 Linux
```

```
PHP 7.4.15 (cli) (built: Feb  4 2021 17:57:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies
```

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/10.2.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-10.2.1_pre1/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 10.2.1_pre1' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20201203 (Alpine 10.2.1_pre1) 
```

**Comment by sy-records** [comment]
Thank you for your feedback.

This is a Notice error, which is thrown in PHP 7.4, but not in lower versions.
![image](https://user-images.githubusercontent.com/33931153/108443868-8bbbd080-7294-11eb-8d44-40ecb240828f.png)

You are recommended to use `v4.6` native curl hook(`SWOOLE_HOOK_NATIVE_CURL`) if you can upgrade to a higher version.
