### ISSUE TITLE
php7 + 1.7.21 ontask执行完成之后return出错

### ISSUE THREAD

**Issue by zzjin** [swoole/swoole-src#420]
RT.测试如果swoole_server下,ontask传递一个string.ontask可移执行,但是return之后会报错,导致task进程退出
类似#417
测试server代码:
```php
<?php
class SwooleServer{
    private $serv;
    public function __construct() {
        $this -> serv = new swoole_server('0.0.0.0',9512);
        $this -> serv -> set(array(
            'worker_num' => 4,
            'max_request' => 10,
            'dispatch_mode' => 3,
            'task_worker_num' => 4,
            'task_max_request' => 10,
            'open_eof_check' => true, //打开EOF检测
            'package_eof' => "\r\n", //设置EOF
            'open_eof_split' => true,
        ));

        $this -> serv -> on('Receive', array($this, 'onReceive'));
        $this -> serv -> on('Task', array($this, 'onTask'));
        $this -> serv -> on('Finish', array($this, 'onFinish'));
        $this -> serv -> start();
    }

    public function onReceive(swoole_server $serv, $fd, $from_id, $data) {
        // $serv -> task(['fd'=>$fd,'data'=>$data]);
        $serv -> task('test_data');
        $serv -> send($fd, 'ok'.$serv -> setting['package_eof']);
    }

    public function onTask(swoole_server $serv, $task_id, $from_id, $data) {
        var_dump($data);
        return ['test'=>$data];
    }

    public function onFinish(swoole_server $serv, $task_id, $data) {
        var_dump($data);
        unset($data);
    }
}
$server = new SwooleServer();
```
报错信息:
```
string(9) "test_data"
[2015-12-05 15:58:42 $3482.0]	WARN	swManager_check_exit_status: worker#4 abnormal exit, status=0, signal=11
```

**Comment by matyhtf** [comment]
无法重现此问题。请确认是否正确编译，使用gdb查看core信息
http://wiki.swoole.com/wiki/page/10.html

**Comment by zzjin** [comment]
core dump输出:
```
#0  i_zval_ptr_dtor (zval_ptr=0x7ffd6e14d870) at /home/zzjin/install/php-7.0.0/Zend/zend_variables.h:57
#1  _zval_ptr_dtor (zval_ptr=0x7ffd6e14d870) at /home/zzjin/install/php-7.0.0/Zend/zend_execute_API.c:527
#2  0x00007fbb30c9416f in php_swoole_onTask (serv=0x2f81ae0, req=<optimized out>) at /home/zzjin/install/swoole-src/swoole_server.c:684
#3  0x00007fbb30cbd404 in swProcessPool_worker_loop (pool=0x7fbb302011c0, worker=0x7fbb302028b0) at /home/zzjin/install/swoole-src/src/network/ProcessPool.c:327
#4  0x00007fbb30cbde2c in swProcessPool_spawn (worker=0x7fbb302028b0) at /home/zzjin/install/swoole-src/src/network/ProcessPool.c:234
#5  0x00007fbb30cbdf61 in swProcessPool_start (pool=0x7fbb302011c0) at /home/zzjin/install/swoole-src/src/network/ProcessPool.c:106
#6  0x00007fbb30cc3ca1 in swManager_start (factory=factory@entry=0x2f81ff0) at /home/zzjin/install/swoole-src/src/network/Manager.c:138
#7  0x00007fbb30cb3814 in swFactoryProcess_start (factory=0x2f81ff0) at /home/zzjin/install/swoole-src/src/factory/FactoryProcess.c:86
#8  0x00007fbb30cba77d in swServer_start (serv=serv@entry=0x2f81ae0) at /home/zzjin/install/swoole-src/src/network/Server.c:597
#9  0x00007fbb30c971eb in zif_swoole_server_start (execute_data=<optimized out>, return_value=0x7fbb31813130) at /home/zzjin/install/swoole-src/swoole_server.c:2006
#10 0x00000000008590eb in ZEND_DO_FCALL_SPEC_HANDLER () at /home/zzjin/install/php-7.0.0/Zend/zend_vm_execute.h:842
#11 0x000000000081c00b in execute_ex (ex=<optimized out>) at /home/zzjin/install/php-7.0.0/Zend/zend_vm_execute.h:414
#12 0x0000000000864bd7 in zend_execute (op_array=0x7fbb3187c000, op_array@entry=0x7fbb29a00e28, return_value=return_value@entry=0x7fbb318130c0) at /home/zzjin/install/php-7.0.0/Zend/zend_vm_execute.h:458
#13 0x00000000007e0ae4 in zend_execute_scripts (type=type@entry=0x8, retval=0x7fbb318130c0, retval@entry=0x0, file_count=file_count@entry=0x3) at /home/zzjin/install/php-7.0.0/Zend/zend.c:1428
#14 0x0000000000784ed8 in php_execute_script (primary_file=primary_file@entry=0x7ffd6e152170) at /home/zzjin/install/php-7.0.0/main/main.c:2471
#15 0x00000000008667a3 in do_cli (argc=0x2, argv=0x2da0570) at /home/zzjin/install/php-7.0.0/sapi/cli/php_cli.c:974
#16 0x000000000043f810 in main (argc=0x2, argv=0x2da0570) at /home/zzjin/install/php-7.0.0/sapi/cli/php_cli.c:1345
```
