### ISSUE TITLE
WARNING	http_request_on_body (ERRNO 9010): parse multipart body failed, n=2

### ISSUE THREAD

**Issue by Yii18** [swoole/swoole-src#4396]
### Swoole版本，PHP版本，以及操作系统版本信息
[2021-09-08 02:23:22 *4655.0]	WARNING	http_request_on_header_value: invalid multipart/form-data body fd:1
[2021-09-08 02:23:34 *4656.1]	WARNING	http_request_on_header_value: invalid multipart/form-data body fd:2
[2021-09-08 02:25:15 *4657.2]	WARNING	http_request_on_header_value: invalid multipart/form-data body fd:3
[2021-09-08 02:27:45 *4658.3]	WARNING	http_request_on_body (ERRNO 9010): parse multipart body failed, n=2

### 相关代码
```php

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jun 13 2020 07:11:39
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.3
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

 ```
[2021-09-08 02:44:58] [ERROR] onRequest: Uncaught exception "ErrorException"([0]Undefined index: REQUEST_URI) at /data/programs/fp-admin-center/vendor/hhxsv5/laravel-s/src/Swoole/Request.php:64,
#0 /data/programs/fp-admin-center/vendor/hhxsv5/laravel-s/src/Swoole/Request.php(64): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined index...', '/data/programs/...', 64, Array)
#1 /data/programs/fp-admin-center/vendor/hhxsv5/laravel-s/src/LaravelS.php(145): Hhxsv5\LaravelS\Swoole\Request->toIlluminateRequest(Array, Array)
#2 /data/programs/fp-admin-center/vendor/hhxsv5/laravel-s/src/LaravelS.php(152): Hhxsv5\LaravelS\LaravelS->convertRequest(Object(Hhxsv5\LaravelS\Illuminate\Laravel), Object(Swoole\Http\Request))
#3 [internal function]: Hhxsv5\LaravelS\LaravelS->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#4 /data/programs/fp-admin-center/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(347): Swoole\Server->start()
#5 /data/programs/fp-admin-center/vendor/hhxsv5/laravel-s/src/Console/Portal.php(153): Hhxsv5\LaravelS\Swoole\Server->run()
#6 /data/programs/fp-admin-center/vendor/hhxsv5/laravel-s/src/Console/Portal.php(212): Hhxsv5\LaravelS\Console\Portal->start()
#7 /data/programs/fp-admin-center/vendor/hhxsv5/laravel-s/src/Console/Portal.php(62): Hhxsv5\LaravelS\Console\Portal->restart()
#8 /data/programs/fp-admin-center/vendor/symfony/console/Command/Command.php(258): Hhxsv5\LaravelS\Console\Portal->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /data/programs/fp-admin-center/bin/laravels(164): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 {main}





 ```

**Comment by matyhtf** [comment]
说明有非法的的 `multipart/form-data` 格式数据，请将原始的 HTTP 请求报文发给我们。另外，建议升级一下 swoole 的版本
