### ISSUE TITLE
Coredump on closing connection when response made on curl callback function

### ISSUE THREAD

**Issue by samlm0** [swoole/swoole-src#4699]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
<?php
$server = new \Swoole\Coroutine\Http\Server("unix://" . __DIR__ . '/test.sock');
$server->handle('/', function (\Swoole\Http\Request $request, \Swoole\Http\Response $response) {
    $response->detach();
    $socket = $response->socket;
    $headers = [];
    $checkHttpCode = false;
    $isHeaderSended = false;
    $httpCode = 200;

    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, 'http://www.baidu.com');
    curl_setopt($curl, CURLOPT_HEADERFUNCTION, function ($curl, $header) use (&$headers, &$httpCode, &$checkHttpCode) {
        if (!$checkHttpCode) {
            $checkHttpCode = true;
            preg_match('/HTTP\/[0-9.]+\s(\d+)\s(.*)/', $header, $matches, PREG_OFFSET_CAPTURE, 0);
            if (!empty($matches)) {
                $httpCode = $matches[1][0];
                return strlen($header);
            }
        }
        $content = trim($header);

        if (empty($content)) return strlen($header);
        list($key, $value) = explode(": ", $content);
        if (in_array(strtolower($key), ['content-length', 'transfer-encoding'])) return strlen($header);
        $headers[$key] = $value;
        return strlen($header);
    });

    curl_setopt($curl, CURLOPT_WRITEFUNCTION, function ($curl, $str) use ($response, &$socket, &$headers, &$isHeaderSended, &$httpCode) {
        if (!$isHeaderSended) {
            $isHeaderSended = true;
            // $response->status($httpCode);
            if ($httpCode == 200) {
                $socket->send("HTTP/1.1 {$httpCode} OK\r\n");
            } else {
                $socket->send("HTTP/1.1 {$httpCode} ERROR\r\n");
            }

            foreach (array_merge([
                'Content-Type' => 'application/octet-stream',
                'X-Accel-Buffering' => 'no',
                'server' => 'webserver/1.0'
            ], $headers) as $k => $v) {
                $socket->send("{$k}: {$v}\r\n");
            }
            $socket->send("\r\n");
        }

        return strlen($str);
    });

    curl_exec($curl);
    curl_close($curl);

    // $socket->send("HTTP/1.1 200 OK\r\n");
    // $socket->send("header: 1\r\n");
    // $socket->send("header: 2\r\n");
    // $socket->send("\r\n");

    // No body send

    return $socket->close();
});

$server->set([
    'http_compression' => false,
    'http_parse_post' => false,
    'http_parse_files' => false,
]);
go(function () {
    go(function () {
        global $server;
        $server->start();
    });

    go(function () {
        $unixSocketPath = __DIR__ . '/test.sock';
        while (!file_exists($unixSocketPath)) \Swoole\Coroutine\System::sleep(0.1);
        chmod($unixSocketPath, 0777);
    });
});
```

2. What did you expect to see?

HTTP Connection normal close

3. What did you see instead?

Segmentation fault (core dumped)

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.9
Built => Apr 21 2022 07:05:27
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1n  15 Mar 2022
dtls => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
```
5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux the-hostname 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```
```
PHP 7.3.31-1~deb10u1 (cli) (built: Oct 24 2021 15:18:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.31, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.31-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)
```

**Comment by samlm0** [comment]
尝试使用 gdb 获得调试信息

```
(gdb) bt
#0  swoole_strnstr (needle=<synthetic pointer>, needle_length=4, haystack_length=915843904, 
    haystack=0x7f8671e8b000 <error: Cannot access memory at address 0x7f8671e8b000>)
    at /tmp/pear/temp/swoole/include/swoole.h:301
#1  swoole_strnpos (needle_length=4, needle=<synthetic pointer>, haystack_length=915843904, haystack=0x7f8671d9b018 "")
    at /tmp/pear/temp/swoole/include/swoole.h:318
#2  zim_swoole_http_server_coro_onAccept (execute_data=<optimized out>, return_value=<optimized out>)
    at /tmp/pear/temp/swoole/ext-src/swoole_http_server_coro.cc:581
#3  0x00007f86719a5846 in swoole::PHPCoroutine::main_func (arg=0x7f866dc14cb0)
    at /tmp/pear/temp/swoole/ext-src/swoole_coroutine.cc:804
#4  0x00007f8671a1f3a0 in std::function<void (void*)>::operator()(void*) const (__args#0=<optimized out>, 
    this=0x5603369c0f70) at /usr/include/c++/8/bits/std_function.h:682
#5  swoole::coroutine::Context::context_func (arg=0x5603369c0f70) at /tmp/pear/temp/swoole/src/coroutine/context.cc:142
#6  0x00007f8671a95191 in swoole_make_fcontext ()
    at /tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#7  0x0000000000000000 in ?? ()
(gdb) zbacktrace 
[0x7f867
```

**Comment by samlm0** [comment]
same as #4503

**Comment by route33** [comment]
when is going to be released?

**Comment by matyhtf** [comment]
@route33 We will release a new version at next Friday.
