### ISSUE TITLE
try..catch E_ERROR异常在某些场景下得不到执行

### ISSUE THREAD

**Issue by dongzitai** [swoole/swoole-src#4863]
## 环境

```
OS: Linux 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64
GCC_VERSION: 8.3.1 20190311 (Red Hat 8.3.1-3)
OPENSSL_VERSION: OpenSSL 1.0.2k-fips  26 Jan 2017
PHP_VERSION : 7.4.30
SWOOLE: 4.8.12-dev
```

## Swoole示例代码

```php
// server.php
$port=9099;
$http = new Swoole\Http\Server('127.0.0.1', $port);
$http->set([
    'worker_num' => 1,
    'daemonize' => false,
    'backlog' => 128,
    'enable_coroutine' => true,
]);
$http->on('start', function ($server)use($port) {
    echo "Swoole http server is started at http://127.0.0.1:$port\n";
});

$http->on('request', function ($request, $response) {
    $response->header('Content-Type', 'text/plain');

    $wsdl='http://1.1.1.1/soap.cls?wsdl';
    $option = array_merge([
        'connection_timeout' => 3,
        'location' => $wsdl,
        'features' => SOAP_SINGLE_ELEMENT_ARRAYS,
        'exceptions' => true,
    ], []);
    try {
        $client =new \SoapClient($wsdl, $option);
    } catch (\Exception $e) {
        var_dump($e);
    }
    $response->end('Hello World');
});

$http->start();
```

## 执行结果

```
[2022-10-07 20:52:35 $25504.0]	WARNING	Server::check_worker_exit_status(): worker(pid=25506, id=0) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.8.12-dev, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64
GCC_VERSION: 8.3.1 20190311 (Red Hat 8.3.1-3)
OPENSSL_VERSION: OpenSSL 1.0.2k-fips  26 Jan 2017
PHP_VERSION : 7.4.30
```

## 预期

协程执行的php代码可以catch到E_ERROR异常。

## coredump堆栈

死循环

```
...
#15591 0x00000000008eb0e8 in zend_throw_exception_object (exception=0x7ffd5bc734c0) at /root/src-debug/php-src/Zend/zend_exceptions.c:1068
#15592 0x00000000006a7e08 in soap_real_error_handler (error_num=1, error_filename=0x7ff292afe0b8 "[no active file]", error_lineno=0, format=0x1116a02 "Uncaught %s\n  thrown", args=0x7ffd5bc735c8)
    at /root/src-debug/php-src/ext/soap/soap.c:2152
#15593 0x00000000006a82dc in soap_error_handler (error_num=1, error_filename=0x7ff292afe0b8 "[no active file]", error_lineno=0, format=0x1116a02 "Uncaught %s\n  thrown", args=0x7ffd5bc735c8)
    at /root/src-debug/php-src/ext/soap/soap.c:2241
#15594 0x00000000008ea9ab in zend_error_va (type=1, file=0x7ff292afe0b8 "[no active file]", lineno=0, format=0x1116a02 "Uncaught %s\n  thrown") at /root/src-debug/php-src/Zend/zend_exceptions.c:968
#15595 0x00000000008eafed in zend_exception_error (ex=0x7ff292bd9240, severity=1) at /root/src-debug/php-src/Zend/zend_exceptions.c:1040
#15596 0x00000000008e7408 in zend_throw_exception_internal (exception=0x7ffd5bc74150) at /root/src-debug/php-src/Zend/zend_exceptions.c:166
#15597 0x00000000008eb0e8 in zend_throw_exception_object (exception=0x7ffd5bc74150) at /root/src-debug/php-src/Zend/zend_exceptions.c:1068
#15598 0x00000000006a7e08 in soap_real_error_handler (error_num=1, error_filename=0x7ff292afe248 "[no active file]", error_lineno=0, format=0x1116a02 "Uncaught %s\n  thrown", args=0x7ffd5bc74258)
    at /root/src-debug/php-src/ext/soap/soap.c:2152
#15599 0x00000000006a82dc in soap_error_handler (error_num=1, error_filename=0x7ff292afe248 "[no active file]", error_lineno=0, format=0x1116a02 "Uncaught %s\n  thrown", args=0x7ffd5bc74258)
    at /root/src-debug/php-src/ext/soap/soap.c:2241
#15600 0x00000000008ea9ab in zend_error_va (type=1, file=0x7ff292afe248 "[no active file]", lineno=0, format=0x1116a02 "Uncaught %s\n  thrown") at /root/src-debug/php-src/Zend/zend_exceptions.c:968
#15601 0x00000000008eafed in zend_exception_error (ex=0x7ff292bd9180, severity=1) at /root/src-debug/php-src/Zend/zend_exceptions.c:1040
#15602 0x00000000008e7408 in zend_throw_exception_internal (exception=0x7ffd5bc74de0) at /root/src-debug/php-src/Zend/zend_exceptions.c:166
#15603 0x00000000008eb0e8 in zend_throw_exception_object (exception=0x7ffd5bc74de0) at /root/src-debug/php-src/Zend/zend_exceptions.c:1068
#15604 0x00000000006a7e08 in soap_real_error_handler (error_num=1, error_filename=0x7ff292afe478 "[no active file]", error_lineno=0, format=0x1116a02 "Uncaught %s\n  thrown", args=0x7ffd5bc74ee8)
    at /root/src-debug/php-src/ext/soap/soap.c:2152
#15605 0x00000000006a82dc in soap_error_handler (error_num=1, error_filename=0x7ff292afe478 "[no active file]", error_lineno=0, format=0x1116a02 "Uncaught %s\n  thrown", args=0x7ffd5bc74ee8)
    at /root/src-debug/php-src/ext/soap/soap.c:2241
#15606 0x00000000008ea9ab in zend_error_va (type=1, file=0x7ff292afe478 "[no active file]", lineno=0, format=0x1116a02 "Uncaught %s\n  thrown") at /root/src-debug/php-src/Zend/zend_exceptions.c:968
#15607 0x00000000008eafed in zend_exception_error (ex=0x7ff292bd90c0, severity=1) at /root/src-debug/php-src/Zend/zend_exceptions.c:1040
#15608 0x00000000008e7408 in zend_throw_exception_internal (exception=0x7ffd5bc75a70) at /root/src-debug/php-src/Zend/zend_exceptions.c:166
#15609 0x00000000008eb0e8 in zend_throw_exception_object (exception=0x7ffd5bc75a70) at /root/src-debug/php-src/Zend/zend_exceptions.c:1068
#15610 0x00000000006a7e08 in soap_real_error_handler (error_num=1, error_filename=0x7ff292bd43d8 "/root/src-debug/soap-bug.php", error_lineno=43, format=0x1116a02 "Uncaught %s\n  thrown", args=0x7ffd5bc75b78)
    at /root/src-debug/php-src/ext/soap/soap.c:2152
#15611 0x00000000006a82dc in soap_error_handler (error_num=1, error_filename=0x7ff292bd43d8 "/root/src-debug/soap-bug.php", error_lineno=43, format=0x1116a02 "Uncaught %s\n  thrown", args=0x7ffd5bc75b78)
    at /root/src-debug/php-src/ext/soap/soap.c:2241
#15612 0x00000000008ea9ab in zend_error_va (type=1, file=0x7ff292bd43d8 "/root/src-debug/soap-bug.php", lineno=43, format=0x1116a02 "Uncaught %s\n  thrown") at /root/src-debug/php-src/Zend/zend_exceptions.c:968
#15613 0x00000000008eafed in zend_exception_error (ex=0x7ff292affe40, severity=1) at /root/src-debug/php-src/Zend/zend_exceptions.c:1040
#15614 0x0000000000823fbd in php_execute_script (primary_file=0x7ffd5bc791b0) at /root/src-debug/php-src/main/main.c:2680
#15615 0x00000000009966bd in do_cli (argc=2, argv=0x1b3cd30) at /root/src-debug/php-src/sapi/cli/php_cli.c:964
#15616 0x0000000000997697 in main (argc=2, argv=0x1b3cd30) at /root/src-debug/php-src/sapi/cli/php_cli.c:1360
```

### swoole环境执行流程

```
b zend_throw_exception_internal
b main.c:2607
b main.c:2676
b ZEND_HANDLE_EXCEPTION_SPEC_HANDLER
b zend_dispatch_try_catch_finally_helper_SPEC
Breakpoint 3, zend_throw_exception_internal (exception=0x7fff8160ec20) at /root/src-debug/php-src/Zend/zend_exceptions.c:153
153		if (exception != NULL) {
(gdb) c
Continuing.

Breakpoint 2, php_execute_script (primary_file=0x7fff81612e50) at /root/src-debug/php-src/main/main.c:2676
2676		} zend_end_try();
(gdb) c
Continuing.

Breakpoint 3, zend_throw_exception_internal (exception=0x7fff8160f710) at /root/src-debug/php-src/Zend/zend_exceptions.c:153
153		if (exception != NULL) {
(gdb) c
Continuing.

Breakpoint 3, zend_throw_exception_internal (exception=0x7fff8160ea80) at /root/src-debug/php-src/Zend/zend_exceptions.c:153
153		if (exception != NULL) {
(gdb) c
Continuing.

Breakpoint 3, zend_throw_exception_internal (exception=0x7fff8160ddf0) at /root/src-debug/php-src/Zend/zend_exceptions.c:153
153		if (exception != NULL) {
(gdb) c
Continuing.
```

PHP异常捕获执行流程没有得到执行。

## 非swoole示例代码

```php
<?php
$wsdl='http://1.1.1.1/soap.cls?wsdl';
    $option = array_merge([
        'connection_timeout' => 1,
        'location' => $wsdl,
        'features' => $serviceConfig['features'] ?? SOAP_SINGLE_ELEMENT_ARRAYS,
        'exceptions' => true,
    ], []);
    try {
        $client =new \SoapClient($wsdl, $option);
    } catch (\Exception $e) {
        var_dump($e);
    }
    sleep(10000);
```

## 非swoole执行流程

```
b zend_throw_exception_internal
b main.c:2607
b main.c:2676
b ZEND_HANDLE_EXCEPTION_SPEC_HANDLER
b zend_dispatch_try_catch_finally_helper_SPEC
Breakpoint 1, zend_throw_exception_internal (exception=0x7fffffff8c40) at /root/src-debug/php-src/Zend/zend_exceptions.c:153
153		if (exception != NULL) {
(gdb) c
Continuing.

Breakpoint 4, ZEND_HANDLE_EXCEPTION_SPEC_HANDLER () at /root/src-debug/php-src/Zend/zend_vm_execute.h:2596
2596		const zend_op *throw_op = EG(opline_before_exception);
(gdb) c
Continuing.

Breakpoint 5, zend_dispatch_try_catch_finally_helper_SPEC (try_catch_offset=0, op_num=16) at /root/src-debug/php-src/Zend/zend_vm_execute.h:2533
2533		zend_object *ex = EG(exception);
(gdb) c
Continuing.
```

PHP异常捕获执行流程得到执行。

对比swoole和非swoole的执行流程，说明swoole下，PHP发生异常后，swoole接管即会打断PHP代码的执行流程导致`try..catch`没有得到执行。

**Comment by NathanFreeman** [comment]
https://github.com/swoole/swoole-src/issues/4650
