### ISSUE TITLE
项目根目录产生了大量的core.xxxx文件

### ISSUE THREAD

**Issue by drttcrh** [swoole/swoole-src#4902]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
线上项目根目录产生了大量的core.xxx文件，测试环境swoole编译增加debug参数，通过wrk并发测试复现大量core.xxx文件，如下图所示
![image](https://user-images.githubusercontent.com/13195127/200712330-fb159710-74b3-4f6a-933e-054f3e15b8b5.png)

- 通过gdb调试：
```
NU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /www/server/php/73/bin/php...done.
[New LWP 11329]
[New LWP 11341]
[New LWP 11339]
[New LWP 12069]
[New LWP 11346]
[New LWP 11342]
[New LWP 11343]
[New LWP 11344]
[New LWP 11345]
[New LWP 11340]
[New LWP 12070]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `gateway.Worker.6                             '.
Program terminated with signal 7, Bus error.
#0  lex_scan (zendlval=zendlval@entry=0x4205770, elem=0x4205810) at Zend/zend_language_scanner.c:7890
7890	Zend/zend_language_scanner.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 c-ares-1.10.0-3.el7.x86_64 freetype-2.8-14.el7_9.1.x86_64 glibc-2.17-317.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libicu-50.2-4.el7_7.x86_64 libjpeg-turbo-1.2.90-8.el7.x86_64 libpng-1.5.13-8.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libwebp-0.3.0-7.el7.x86_64 libxml2-2.9.1-6.el7.5.x86_64 libzip5-1.5.2-1.el7.remi.x86_64 nss-softokn-freebl-3.53.1-6.el7_9.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 pcre-8.32-17.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64

```
- 使用bt定位错误
```
(gdb) bt
#0  lex_scan (zendlval=zendlval@entry=0x4205770, elem=0x4205810) at Zend/zend_language_scanner.c:7890
#1  0x000000000087d0fa in zendlex (elem=elem@entry=0x4205810) at /www/server/php/73/src/Zend/zend_compile.c:1703
#2  0x00000000008629fa in zendparse () at /www/server/php/73/src/Zend/zend_language_parser.c:4211
#3  0x00000000008650f7 in zend_compile (type=type@entry=2) at Zend/zend_language_scanner.l:587
#4  0x00000000008664f3 in compile_file (file_handle=0x4206400, type=2) at Zend/zend_language_scanner.l:637
#5  0x00000000006f53d8 in phar_compile_file (file_handle=<optimized out>, type=<optimized out>)
    at /www/server/php/73/src/ext/phar/phar.c:3348
#6  0x00000000008665d3 in compile_filename (type=type@entry=2, filename=filename@entry=0x7f180c71ed30) at Zend/zend_language_scanner.l:662
#7  0x00000000008deba5 in zend_include_or_eval (inc_filename=0x7f180c71ed30, type=2) at /www/server/php/73/src/Zend/zend_execute.c:3193
#8  0x0000000000912b0a in ZEND_INCLUDE_OR_EVAL_SPEC_CV_HANDLER () at /www/server/php/73/src/Zend/zend_vm_execute.h:37452
#9  0x00000000009194e5 in execute_ex (ex=0x4205770) at /www/server/php/73/src/Zend/zend_vm_execute.h:59363
#10 0x00007f1821330465 in swoole::PHPCoroutine::main_func (arg=<optimized out>) at /opt/swoole-v4.5.1/swoole_coroutine.cc:706
#11 0x00007f18212dbfba in swoole::Context::context_func (arg=0x2844820) at /opt/swoole-v4.5.1/src/coroutine/context.cc:125
#12 0x00007f18213b84f1 in make_fcontext () at /opt/swoole-v4.5.1/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#13 0x0000000000200010 in ?? ()
#14 0x0000000000200011 in ?? ()
#15 0x0000000000000000 in ?? ()
```

2. What did you expect to see?
希望得到解决

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.1
Built => Nov  8 2022 18:07:24
coroutine => enabled
debug => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux xxx 4.19.0-9.el7.ucloud.x86_64 #1 SMP Mon Sep 28 10:29:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.3.26 (cli) (built: Jan 14 2021 18:14:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
```

**Comment by matyhtf** [comment]
应该是 include 读取文件协程被挂起引起，请升级到 4.8.12
