### ISSUE TITLE
PHP 8.1.16 + swoole 5.0.1 enable curl core

### ISSUE THREAD

**Issue by xuanyanwow** [swoole/swoole-src#4996]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

- 框架： Lumen (9.1.5) (Laravel Components ^9.21)
- 编译加入` --enable-swoole-curl` 后调用 HTTP组件 core dump

复现代码
```php
 Illuminate\Support\Facades\Http::asForm()
        ->timeout(5)
        ->retry(3, 100)
        ->post($url, [
            'content' => '{"test":1}',
        ])
        ->throw();
```

2. What did you expect to see?

3. What did you see instead?

`Segmentation fault`

4. What version of Swoole are you using (show your `php --ri swoole`)?

```

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.1
Built => Mar  6 2023 10:45:46
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
PHP 8.1.16 (cli) (built: Mar  6 2023 10:11:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies
```

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux      
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
```

**Comment by NathanFreeman** [comment]
用的是laravel octane吗？

**Comment by xuanyanwow** [comment]
使用的是 LaravelS 
- 开始出现以上问题是在队列消费中，`php artisan queue:work`
- 在tinker中直接运行也可以复现 `php artinsan tinker`

**Comment by NathanFreeman** [comment]
如果是`SWOOLE_PROCESS`模式下的话，Laravel Octane那边也有一个也超时有关的bug，就是只要超过规定最大执行时间的话，超时退出就会`Segmentation fault`

https://github.com/swoole/swoole-src/pull/4997
看看这个修复能不能解决你的问题，如果不能的话，看看能不能提供一份最小的复现代码我这边看看。

**Comment by xuanyanwow** [comment]
5.0.1 && 5.0.2  都存在bug，与什么框架和无关了。本来是想拉取一个新的lumen框架提供最小测试用例，然后发现直接在composer阶段都已经错误
```sh
[root@397dcb98d908 test]# composer create-project --prefer-dist laravel/lumen ./
Creating a "laravel/lumen" project at "./"
Segmentation fault
```

## php -v
```
[root@397dcb98d908 test]# php -v
PHP 8.1.16 (cli) (built: Mar  6 2023 17:46:24) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies
```

## php -m
```
[root@397dcb98d908 test]# php -m
[PHP Modules]
apcu
bcmath
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gmp
hash
iconv
imagick
json
ldap
libxml
mbstring
memcached
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
swoole
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

## php --ri swoole


```
[root@397dcb98d908 test]# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.2
Built => Mar  8 2023 15:31:16
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by xuanyanwow** [comment]
系统curl版本
```
wget https://curl.se/download/curl-7.88.1.tar.gz --no-check-certificate
```

**Comment by NathanFreeman** [comment]
按照这个https://wiki.swoole.com/#/other/issue?id=关于段错误核心转储 贴一下那个错误信息，我这边看看

**Comment by xuanyanwow** [comment]
```
(gdb) bt
#0  zend_hash_destroy (ht=0x0) at /tmp/php-8.1.16/Zend/zend_hash.c:1592
#1  0x00007feb57c9011c in _php_curl_free (ch=0x7feb56a08200) at /tmp/swoole-src-5.0.2/thirdparty/php/curl/interface.cc:2344
#2  swoole_curl_free_obj (object=0x7feb56a08390) at /tmp/swoole-src-5.0.2/thirdparty/php/curl/interface.cc:2410
#3  0x000000000084ba3b in zend_objects_store_del (object=0x7feb56a08390) at /tmp/php-8.1.16/Zend/zend_objects_API.c:200
#4  0x00000000007cfabc in i_zval_ptr_dtor (zval_ptr=0x7feb5bb995a0) at /tmp/php-8.1.16/Zend/zend_variables.h:44
#5  zend_array_destroy (ht=0x7feb56a5ef18) at /tmp/php-8.1.16/Zend/zend_hash.c:1671
#6  0x00000000008247bc in i_zval_ptr_dtor (zval_ptr=<optimized out>) at /tmp/php-8.1.16/Zend/zend_variables.h:44
#7  i_free_compiled_variables (execute_data=<optimized out>) at /tmp/php-8.1.16/Zend/zend_execute.c:3792
#8  execute_ex (ex=0x0) at /tmp/php-8.1.16/Zend/zend_vm_execute.h:55653
#9  0x000000000082cc74 in zend_execute (op_array=0x7feb5ba75700, return_value=0x0) at /tmp/php-8.1.16/Zend/zend_vm_execute.h:60151
#10 0x00000000007bf7c4 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /tmp/php-8.1.16/Zend/zend.c:1799
#11 0x000000000075e129 in php_execute_script (primary_file=primary_file@entry=0x7ffc8c3ad8b0) at /tmp/php-8.1.16/main/main.c:2542
#12 0x000000000089ef5f in do_cli (argc=6, argv=0x309f920) at /tmp/php-8.1.16/sapi/cli/php_cli.c:965
#13 0x0000000000458cbb in main (argc=6, argv=0x309f920) at /tmp/php-8.1.16/sapi/cli/php_cli.c:1367
```


```
(gdb) f 1
#1  0x00007feb57c9011c in _php_curl_free (ch=0x7feb56a08200) at /tmp/swoole-src-5.0.2/thirdparty/php/curl/interface.cc:2344
2344            zend_hash_destroy(ch->to_free->slist);
```

```
(gdb) f 0
#0  zend_hash_destroy (ht=0x0) at /tmp/php-8.1.16/Zend/zend_hash.c:1592
1592    /tmp/php-8.1.16/Zend/zend_hash.c: No such file or directory.
```

**Comment by NathanFreeman** [comment]
这个curl版本很高了，我今晚看看php有没有兼容这个版本的curl的代码变化，有的话我今晚同步过来给Swoole，没有的话我给PHP提个pr然后在同步到Swoole

**Comment by xuanyanwow** [comment]
好的，辛苦了

**Comment by matyhtf** [comment]
无法重现你的问题

```shell
/work/test # php -v
PHP 8.1.16 (cli) (built: Mar  9 2023 02:32:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
/work/test # php --ri curl

curl

cURL support => enabled
cURL Information => 7.88.1
Age => 10
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => No
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => No
GSSAPI => No
KERBEROS5 => No
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, mqtt, pop3, pop3s, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-pc-linux-musl
SSL Version => OpenSSL/1.1.1t
ZLib Version => 1.2.12

Directive => Local Value => Master Value
curl.cainfo => no value => no value
/work/test # php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.2
Built => Mar  9 2023 02:23:13
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1t  7 Feb 2023
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
c-ares => 1.18.1
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_postgresql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
/work/test # 
```

![2023-03-09 10-48-45 的屏幕截图](https://user-images.githubusercontent.com/2017766/223902868-213057dd-e4e9-4958-9471-83b1db1eda09.png)

**Comment by matyhtf** [comment]
请添加我的微信 19921030512，详细沟通。尝试升级到 5.0.2 ，也可能编译不正确。

**Comment by matyhtf** [comment]
已沟通，curl 版本不正确，php -curl 是 7.29.0 ，而 swoole 编译使用了 curl 7.88.1

**Comment by Jackfinal** [comment]
> 系统curl版本
> 
> ```
> wget https://curl.se/download/curl-7.88.1.tar.gz --no-check-certificate
> ```

curl -V curl 7.88.1
安装时老是报错error "require cURL version 7.56.0 or later"

**Comment by NathanFreeman** [comment]
@Jackfinal 
使用export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/，这个值根据你服务器来
![图片](https://github.com/swoole/swoole-src/assets/33935209/1a71e9e9-3ac8-484f-9318-08cb4c8f3517)

**Comment by Jackfinal** [comment]
您好，您的邮件我已收到，无法亲自回复您的邮件。

**Comment by shixiaobo8** [comment]
> 报错error "require cURL version 7.56.0 or later"

安装swoole 扩展
wget https://pecl.php.net/get/swoole-5.1.1.tgz --no-check-certificate

tar -zxvf swoole-5.1.1.tgz
cd swoole-5.1.1
export LD_LIBRARY_PATH=/usr/local/curl-7.57.0/lib
export LDFLAGS="-L/usr/local/curl-7.57.0/lib"
export CPPFLAGS="-I/usr/local/curl-7.57.0/include"

/data/server/php8215/bin/phpize
./configure --with-php-config=/data/server/php8215/bin/php-config --enable-openssl --enable-swoole-curl --enable-mysqlnd   --enable-sockets --enable-mysqlnd

make -j$(nproc)  && make install

**Comment by shixiaobo8** [comment]
安装curl 高版本
curl 7.56 以上的版本
