### ISSUE TITLE
php8.2 swoole 环境下使用socket_set_block会有DEPRECATED错误

### ISSUE THREAD

**Issue by bb7788** [swoole/swoole-src#5119]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

// error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT);
error_reporting(E_ALL);
var_dump(ini_get("error_reporting"));
$socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
socket_set_block($socket);

php8.2 swoole环境下使用 socket_set_block，会有DEPRECATED错误警告，动态属性废弃。
```
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Config\Listener\RegisterPropertyHandlerListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\ExceptionHandler\Listener\ExceptionHandlerListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\DbConnection\Listener\RegisterConnectionResolverListener listener.
[DEBUG] Crontab index-force-merge have been registered.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Crontab\Listener\CrontabRegisterListener listener.
string(5) "32767"
Creation of dynamic property Swoole\Coroutine\Socket::$__ext_sockets_nonblock is deprecated
[ERROR] ErrorException: Creation of dynamic property Swoole\Coroutine\Socket::$__ext_sockets_nonblock is deprecated in @swoole/library/ext/sockets.php:217
Stack trace:
#0 @swoole/library/ext/sockets.php(217): Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler::Hyperf\ExceptionHandler\Listener\{closure}()
#1 [internal function]: swoole_socket_set_block()
#2 /data/project/test/app/Command/TestCommand.php(71): socket_set_block()
#3 /data/project/test/vendor/hyperf/command/src/Command.php(428): App\Command\TestCommand->handle()
#4 [internal function]: Hyperf\Command\Command->Hyperf\Command\{closure}()
#5 {main}
[DEBUG] Event Hyperf\Command\Event\FailToHandle handled by Hyperf\Command\Listener\FailToHandleListener listener.
[DEBUG] Event Hyperf\Command\Event\AfterExecute handled by App\Listener\ResumeExitCoordinatorListener listener.
real	0m 1.30s
user	0m 0.55s
sys	0m 0.13s

```

3. What did you expect to see?

4. What did you see instead?

5. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.3
Built => Jun 17 2023 12:45:06
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 3.1.1 30 May 2023
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.19.1
zlib => 1.2.13
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled
coroutine_postgresql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```
6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux 8d5fe4efe0d6 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 Linux
```
```
PHP 8.2.8 (cli) (built: Jul  6 2023 19:21:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies
```

**Comment by matyhtf** [comment]
最新的代码已修复了，属性未定义

**Comment by guandeng** [comment]
> 最新的代码已修复了，属性未定义

在5.1.2也还有这个提示

**Comment by hetao29** [comment]
5.1.2也有相同的问题
```bash
@swoole/library/ext/sockets.php(217)    E_DEPRECATED:Creation of dynamic property Swoole\Coroutine\Socket::$__ext_sockets_nonblock is deprecated
```
