### ISSUE TITLE
Swoole 5.1 pgsql execute issue

### ISSUE THREAD

**Issue by volodymyr-hordiienko** [swoole/swoole-src#5159]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
Trying to select from postgres database using async version of pgsql 

```
    $this->pool = new PDOPool((new PDOConfig)
        ->withDriver('pgsql')
        ->withHost('db')
        ->withPort(5432)
        ->withDbName('test-db')
        ->withCharset('utf8mb4')
        ->withUsername('test-user')
        ->withPassword('test-password')
    );
    .....
    $pdo = $this->pool->get();

    $statement = $pdo->prepare('select ? + ?');
    $statement->execute([random_int(1, 100), random_int(1, 100)]);
    $data = $statement->fetchAll();
    var_dump($data);
    $this->pool->put($pdo);
```

2. What did you expect to see?

Result of sum from postgresql

3. What did you see instead?

```
swoole5-swoole-1  | HINT:  Could not choose a best candidate operator. You might need to add explicit type casts. in @swoole/library/core/Database/PDOStatementProxy.php:53
swoole5-swoole-1  | Stack trace:
swoole5-swoole-1  | #0 @swoole/library/core/Database/PDOStatementProxy.php(53): PDOStatement->execute(Array)
swoole5-swoole-1  | #1 /app/src/Application.php(59): Swoole\Database\PDOStatementProxy->__call('execute', Array)
swoole5-swoole-1  | #2 [internal function]: App\Application->App\{closure}()
swoole5-swoole-1  | #3 {main}
swoole5-swoole-1  |   thrown in @swoole/library/core/Database/PDOStatementProxy.php on line 53
swoole5-swoole-1  | [2023-10-05 11:07:44 *30.7] ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught PDOException: SQLSTATE[42725]: Ambiguous function: 7 ERROR:  operator is not unique: unknown + unknown
swoole5-swoole-1  | LINE 1: select $1 + $2
swoole5-swoole-1  |                              ^
```

Looks like its generate SQL `select $1 + $2` instead of `select <int> + <int>`

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
root@dcb1de98e0c7:/app# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.0
Built => Sep 29 2023 18:38:14
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.9 30 May 2023
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
zlib => 1.2.13
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_pgsql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
root@dcb1de98e0c7:/app# 
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
root@dcb1de98e0c7:/app# uname -a                      
Linux dcb1de98e0c7 5.15.49-linuxkit-pr #1 SMP Thu May 25 07:17:40 UTC 2023 x86_64 GNU/Linux
```

```
root@dcb1de98e0c7:/app# php -v
PHP 8.3.0RC2 (cli) (built: Sep 20 2023 17:19:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.0RC2, Copyright (c) Zend Technologies
```

```
root@dcb1de98e0c7:/app# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 12.2.0-14' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-12-bTRWOB/gcc-12-12.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-12-bTRWOB/gcc-12-12.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14) 
```

**Comment by NathanFreeman** [comment]
This is not a problem with Swoole and PHP.
To resolve this issue, you need to provide more context and information to specify the operator being used. This can be done by providing additional conditions in the query, explicitly stating the data types of the variables, or using appropriate functions.
