### ISSUE TITLE
 Uncaught Swoole\Error: cURL is executing, cannot be operated in

### ISSUE THREAD

**Issue by cloud-arrow** [swoole/swoole-src#5226]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
队列下执行会报这个错误

```
PHP Fatal error:  Uncaught Swoole\Error: cURL is executing, cannot be operated in /var/www/backend/vendor/symfony/http-client/CurlHttpClient.php:329
Stack trace:
#0 /var/www/backend/vendor/symfony/http-client/CurlHttpClient.php(329): curl_multi_exec(Resource id #699, 0)
#1 /var/www/backend/vendor/symfony/http-client/Internal/HttplugWaitLoop.php(65): Symfony\Component\HttpClient\CurlHttpClient->stream(Object(SplObjectStorage), NULL)
#2 /var/www/backend/vendor/symfony/http-client/HttplugClient.php(130): Symfony\Component\HttpClient\Internal\HttplugWaitLoop->wait(Object(Symfony\Component\HttpClient\Response\CurlResponse))
#3 /var/www/backend/vendor/guzzlehttp/promises/src/Promise.php(248): Symfony\Component\HttpClient\HttplugClient::Symfony\Component\HttpClient\{closure}(true)
#4 /var/www/backend/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#5 /var/www/backend/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#6 /var/www/backend/vendor/guzzl in /var/www/backend/vendor/symfony/http-client/CurlHttpClient.php on line 329
```

2. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.13
Built => Nov 29 2023 01:46:49
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1w  11 Sep 2023
dtls => enabled
curl-native => enabled
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

3. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

`php -v`

PHP 7.4.27 (cli) (built: Dec 16 2021 22:42:18) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies

**Comment by cloud-arrow** [comment]
@matyhtf  大佬帮忙看一下，🙏

**Comment by NathanFreeman** [comment]
看起来像是两个协程用了同一个curl连接

**Comment by cloud-arrow** [comment]
> 看起来像是两个协程用了同一个curl连接

不是吧，共用同一个连接，我记得是报这种错误的 
Fatal error: Uncaught Swoole\Error: Socket#6 has already been bound to another coroutine#2, reading or writing of the same socket in coroutine#3 at the same time is not allowed

**Comment by NathanFreeman** [comment]
没错，是多个协程共用一个curl连接
```c++
    Coroutine *check_bound_co() {
        if (co) {
            swoole_fatal_error(SW_ERROR_CO_HAS_BEEN_BOUND, "cURL is executing, cannot be operated");
            return nullptr;
        }
        return Coroutine::get_current_safe();
    }
```

**Comment by cloud-arrow** [comment]
> 没错，是多个协程共用一个curl连接
> 
> ```c++
>     Coroutine *check_bound_co() {
>         if (co) {
>             swoole_fatal_error(SW_ERROR_CO_HAS_BEEN_BOUND, "cURL is executing, cannot be operated");
>             return nullptr;
>         }
>         return Coroutine::get_current_safe();
>     }
> ```

你好，那这个要怎么解决？ @NathanFreeman

**Comment by NathanFreeman** [comment]
检查一下代码是哪里出问题或者找不到问题代码在哪就关闭协程

**Comment by matyhtf** [comment]
两个协程公用了同一个 curl 句柄导致

**Comment by qiqizjl** [comment]
我们也同样出现了这个问题  怀疑是symfony/http-client这个库的问题？
