### ISSUE TITLE
make test error report

### ISSUE THREAD

**Issue by FunnyRyan** [swoole/swoole-src#5250]
```
=====================================================================
BORKED TEST SUMMARY
---------------------------------------------------------------------
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug38334.skip.php(6): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug38334.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_2_2.skip.php(7): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_2_2.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_2_2.skip.php(7): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_3_2.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug70862_1.skip.php(6): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug70862_1.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_2_2.skip.php(7): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug78192_2.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_2_2.skip.php(7): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug79664_2.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_2_2.skip.php(7): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug_44159_sqlite_version_2.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug_63916_2.skip.php(7): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug_63916_2.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_2_2.skip.php(7): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/open_basedir.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug70862_1.skip.php(6): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/pdo_fetch_func_001_1.phpt]
Fatal error: Uncaught Error: Undefined constant "SWOOLE_BASE" in /home/codefiles/swoole-src-5.1.2/tests/include/config.php:38
Stack trace:
#0 /home/codefiles/swoole-src-5.1.2/tests/include/bootstrap.php(10): require_once()
#1 /home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/bug44327_2_2.skip.php(7): require('/home/codefiles...')
#2 {main}
  thrown in /home/codefiles/swoole-src-5.1.2/tests/include/config.php on line 38 [/home/codefiles/swoole-src-5.1.2/tests/swoole_pdo_sqlite/pdo_sqlite_filename_uri.phpt]
=====================================================================
```

does anyone knows if these test reports are normal? Compilation did not indicate failure, but 'make test' resulted in an error."

**Comment by NathanFreeman** [comment]
`echo "extension=swoole.so" >> /path/to/your/php.ini`
