### ISSUE TITLE
worker(pid=5361, id=5) abnormal exit

### ISSUE THREAD

**Issue by thethunderturner** [swoole/swoole-src#5565]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I tried uploading a 56MB file using livewire's fileupload with laravel.

2. What did you expect to see?
I expected the file to be uploaded (in livewires tmp directory)

3. What did you see instead?
Instead the upload failed and I got these error on my screen:
![image](https://github.com/user-attachments/assets/1d3b0f9c-acc5-4a10-9669-422e8f7eb32d)
and this error on my browser console:
![image](https://github.com/user-attachments/assets/5ce03cb4-e6ff-4143-bd59-1ee4c1a90e12)

Laravel log:
```log
[2024-11-17 09:37:46 #5311.0]	WARNING	Server::check_worker_exit_status(): worker(pid=5361, id=5) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.1.2, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 6.11.8-2-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 15 Nov 2024 02:20:46 +0000 x86_64
GCC_VERSION: 14.2.1 20240910
PHP_VERSION : 8.3.13

[2024-11-17 10:03:16 #5299.15]	WARNING	Port_onRead_http() (ERRNO 7102): Request Entity Too Large: header-length (1572) + content-length (56122239) is greater than the package_max_length(10485760) from session#5 on localhost:8000
[2024-11-17 10:05:10 #5299.11]	WARNING	Port_onRead_http() (ERRNO 7102): Request Entity Too Large: header-length (1572) + content-length (56122239) is greater than the package_max_length(10485760) from session#1 on localhost:8000
[2024-11-17 10:07:51 #10162.0]	WARNING	Server::check_worker_exit_status(): worker(pid=10186, id=23) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.1.2, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 6.11.8-2-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 15 Nov 2024 02:20:46 +0000 x86_64
GCC_VERSION: 14.2.1 20240910
PHP_VERSION : 8.3.13

[2024-11-17 10:07:59 #10152.13]	WARNING	Port_onRead_http() (ERRNO 7102): Request Entity Too Large: header-length (1572) + content-length (56122239) is greater than the package_max_length(10485760) from session#3 on localhost:8000
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.2
Built => Nov  6 2024 14:41:27
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.3.1.zlib-ng
brotli => E16781312/D16781312
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
coroutine_pgsql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux cachyos 6.11.8-2-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 15 Nov 2024 02:20:46 +0000 x86_64 GNU/Linux

PHP 8.3.13 (cli) (built: Oct 23 2024 15:27:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.13, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /tmp/pkg/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++,rust --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://github.com/CachyOS/CachyOS-PKGBUILDS/issues --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 14.2.1 20240910 (GCC) 
```

**Comment by NathanFreeman** [comment]
Please execute `php -m` to check the list of PHP extensions.

You can try setting the `upload_max_filesize` configuration. As long as the content-length header of the http message is greater than `package_max_length`, swoole will write the uploaded file content directly to a temporary file instead of keeping it in memory.

```php
  'swoole' => [
        'options' => [
            'package_max_length' => 1 * 1024 * 1024,
            'upload_max_filesize' => 5 * 1024 * 1024
        ],
    ],
```

Because `upload_max_filesize` is set to a value greater than 0, the client can upload files larger than `package_max_length` without encountering an error. When `upload_max_filesize` is not 0, Swoole will write the uploaded file, which means the request body, to disk instead of keeping it in memory. Of course, the request headers will still be transmitted in memory.

Please try to use gdb or valgrind to capture the error information. see https://wiki.swoole.com/en/#/other/issue?id=about-segmentation-fault-core-dump

**Comment by thethunderturner** [comment]
```
 ~  php -m                                                                                                                                                                                                                                                 ✔  20s  10:45:52 
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
hash
iconv
intl
json
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
SimpleXML
SPL
standard
swoole
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

How do I edit the configuration you mentioned? I change the values on my `php.ini`
`package_max_length` doesnt exist
`upload_max_filesize = 256M`

**Comment by NathanFreeman** [comment]
`upload_max_filesize` and `package_max_length` are configurations for the Swoole HTTP server. You need to change them in your application. Are you using Laravel Octane?

**Comment by thethunderturner** [comment]
> `upload_max_filesize` and `package_max_length` are configurations for the Swoole HTTP server. You need to change them in your application. Are you using Laravel Octane?

Correct!

**Comment by NathanFreeman** [comment]
You can directly set it in octane.php. The main issue is the segmentation fault, which needs to be diagnosed using gdb and valgrind.

**Comment by thethunderturner** [comment]
> You can directly set it in octane.php. The main issue is the segmentation fault, which needs to be diagnosed using gdb and valgrind.

```
Core was generated by `/usr/bin/php swoole-server /home/mateo/Desktop/Projects/HomeServer/storage/logs'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  zend_mm_alloc_small (heap=0x71026a600040, bin_num=11) at /usr/src/debug/php/php-8.3.13/Zend/zend_alloc.c:1315
1315                    heap->free_slot[bin_num] = p->next_free_slot;
(gdb) bt
#0  zend_mm_alloc_small (heap=0x71026a600040, bin_num=11) at /usr/src/debug/php/php-8.3.13/Zend/zend_alloc.c:1315
#1  zend_mm_alloc_heap (heap=0x71026a600040, size=<optimized out>) at /usr/src/debug/php/php-8.3.13/Zend/zend_alloc.c:1386
#2  _emalloc (size=<optimized out>) at /usr/src/debug/php/php-8.3.13/Zend/zend_alloc.c:2616
#3  0x00005e0d6a22ba69 in assemble_code_blocks (cfg=cfg@entry=0x7fff6b4f27b0, op_array=op_array@entry=0x71026a796f58, ctx=0x7fff6b4f28c0) at /usr/src/debug/php/php-8.3.13/Zend/Optimizer/block_pass.c:982
#4  0x00005e0d6a22e9ae in zend_optimize_cfg (op_array=op_array@entry=0x71026a796f58, ctx=ctx@entry=0x7fff6b4f28c0) at /usr/src/debug/php/php-8.3.13/Zend/Optimizer/block_pass.c:1763
#5  0x00005e0d6a2244fa in zend_optimize (op_array=0x71026a796f58, ctx=ctx@entry=0x7fff6b4f28c0) at /usr/src/debug/php/php-8.3.13/Zend/Optimizer/zend_optimizer.c:1009
#6  0x00005e0d6a2289b3 in zend_optimize_script (script=script@entry=0x710269009600, optimization_level=2147401727, debug_level=0) at /usr/src/debug/php/php-8.3.13/Zend/Optimizer/zend_optimizer.c:1494
#7  0x000071026ccb8358 in cache_script_in_shared_memory (new_persistent_script=0x710269009600, key=0x5e0d59e6cd50, from_shared_memory=<synthetic pointer>) at /usr/src/debug/php/php-8.3.13/ext/opcache/ZendAccelerator.c:1562
#8  persistent_compile_file (file_handle=<optimized out>, type=<optimized out>) at /usr/src/debug/php/php-8.3.13/ext/opcache/ZendAccelerator.c:2156
#9  persistent_compile_file (file_handle=<optimized out>, type=<optimized out>) at /usr/src/debug/php/php-8.3.13/ext/opcache/ZendAccelerator.c:1975
#10 0x00005e0d6a11cf36 in compile_filename (type=type@entry=8, filename=filename@entry=0x5e0d59e6cd50) at /usr/src/debug/php/php-8.3.13/Zend/zend_language_scanner.c:706
#11 0x00005e0d6a1a6da2 in zend_include_or_eval (inc_filename_zv=<optimized out>, type=8) at /usr/src/debug/php/php-8.3.13/Zend/zend_execute.c:4946
#12 0x00005e0d6a1b74dc in ZEND_INCLUDE_OR_EVAL_SPEC_CV_HANDLER () at /usr/src/debug/php/php-8.3.13/Zend/zend_vm_execute.h:39836
#13 0x00005e0d6a1e43b4 in execute_ex (ex=0x207670) at /usr/src/debug/php/php-8.3.13/Zend/zend_vm_execute.h:60595
#14 0x00005e0d6a15b3f7 in zend_call_function (fci=<optimized out>, fci_cache=<optimized out>) at /usr/src/debug/php/php-8.3.13/Zend/zend_execute_API.c:957
#15 0x000071026969b217 in sw_zend_call_function_ex (function_name=0x0, fci_cache=0x71026a7cd028, param_count=2, params=0x7fff6b4f2d20, retval=0x0) at /tmp/pear/temp/swoole/ext-src/php_swoole_private.h:852
#16 zend::function::call (fci_cache=fci_cache@entry=0x71026a7cd028, argc=argc@entry=2, argv=argv@entry=0x7fff6b4f2dd0, retval=retval@entry=0x0, enable_coroutine=<optimized out>) at /tmp/pear/temp/swoole/ext-src/php_swoole_cxx.cc:44
#17 0x000071026973871a in php_swoole_server_onWorkerStart (serv=0x5e0d832d8b20, worker=<optimized out>) at /tmp/pear/temp/swoole/ext-src/swoole_server.cc:1484
#18 0x00007102697dd794 in std::function<void(swoole::Server*, swoole::Worker*)>::operator() (this=0x5e0d832d9138, __args#0=<optimized out>, __args#1=<optimized out>) at /usr/include/c++/14.2.1/bits/std_function.h:587
#19 swoole::Server::call_worker_start_callback (this=0x5e0d832d8b20, worker=0x71026dba7a20) at /tmp/pear/temp/swoole/src/server/worker.cc:304
#20 0x00007102697e0021 in swoole::Server::start_event_worker (this=this@entry=0x5e0d832d8b20, worker=worker@entry=0x71026dba7a20) at /tmp/pear/temp/swoole/src/server/worker.cc:504
#21 0x00007102697bccb3 in swoole::Server::spawn_event_worker (this=0x5e0d832d8b20, worker=0x71026dba7a20) at /tmp/pear/temp/swoole/src/server/manager.cc:622
#22 0x00007102697bec1f in operator() (__closure=0x7fff6b4f30c0) at /tmp/pear/temp/swoole/src/server/manager.cc:129
#23 0x000071026975dc23 in std::function<void()>::operator() (this=0x7fff6b4f30c0) at /usr/include/c++/14.2.1/bits/std_function.h:591
#24 swoole_fork_exec (fn=...) at /tmp/pear/temp/swoole/src/core/base.cc:362
#25 0x00007102697bf1e4 in swoole::Server::start_manager_process (this=<optimized out>) at /tmp/pear/temp/swoole/src/server/manager.cc:151
#26 0x00007102697d29d7 in swoole::ProcessFactory::start (this=0x5e0d832f29d0) at /tmp/pear/temp/swoole/src/server/process.cc:62
#27 0x00007102697c93f2 in swoole::Server::start (this=this@entry=0x5e0d832d8b20) at /tmp/pear/temp/swoole/src/server/master.cc:665
#28 0x0000710269743500 in zim_swoole_server_start (execute_data=<optimized out>, return_value=0x7fff6b4f3290) at /tmp/pear/temp/swoole/ext-src/swoole_server.cc:2583
#29 0x00005e0d6a1ec408 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php/php-8.3.13/Zend/zend_vm_execute.h:1867
#30 execute_ex (ex=0x207670) at /usr/src/debug/php/php-8.3.13/Zend/zend_vm_execute.h:57248
#31 0x00005e0d6a1ecf94 in zend_execute (op_array=0x71026a675800, return_value=0x0) at /usr/src/debug/php/php-8.3.13/Zend/zend_vm_execute.h:61604
#32 0x00005e0d6a16dced in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /usr/src/debug/php/php-8.3.13/Zend/zend.c:1893
#33 0x00005e0d6a0ef7e5 in php_execute_script (primary_file=primary_file@entry=0x7fff6b4f5830) at /usr/src/debug/php/php-8.3.13/main/main.c:2528
#34 0x00005e0d6a277223 in do_cli (argc=argc@entry=3, argv=argv@entry=0x5e0d82f8a000) at /usr/src/debug/php/php-8.3.13/sapi/cli/php_cli.c:966
#35 0x00005e0d69e51553 in main (argc=3, argv=0x5e0d82f8a000) at /usr/src/debug/php/php-8.3.13/sapi/cli/php_cli.c:1341
```

Calling #19 I get this:
```
(gdb) f 19
#19 swoole::Server::call_worker_start_callback (this=0x5e0d832d8b20, worker=0x71026dba7a20) at /tmp/pear/temp/swoole/src/server/worker.cc:304
warning: 304    /tmp/pear/temp/swoole/src/server/worker.cc: No such file or directory
```

Also just to make a note, I use arch linux, and for me the core dumps were in:
```
 ~  cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
```

**Comment by thethunderturner** [comment]
Fixed issue
