### ISSUE TITLE
ReactorEpoll.c:133: swReactorEpoll_add: Assertion `fd > 2' failed.swoole ver=1.8.2

### ISSUE THREAD

**Issue by lilien1010** [swoole/swoole-src#564]
php: /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:133: swReactorEpoll_add: Assertion `fd > 2' failed.

it shows this fatal error while I am using async_http_client

**Comment by lilien1010** [comment]
```
#0  0x000000346fe32925 in raise () from /lib64/libc.so.6
#1  0x000000346fe34105 in abort () from /lib64/libc.so.6
#2  0x000000346fe2ba4e in __assert_fail_base () from /lib64/libc.so.6
#3  0x000000346fe2bb10 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fa716e8ca34 in swReactorEpoll_add (reactor=0x2bc9670, fd=0, fdtype=<value optimized out>) at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:133
#5  0x00007fa716e91a23 in swClient_tcp_connect_async (cli=0x7fa715d92108, host=<value optimized out>, port=<value optimized out>, timeout=<value optimized out>, 
    nonblock=<value optimized out>) at /tmp/pear/temp/swoole/src/network/Client.c:416
#6  0x00007fa716e72579 in zim_swoole_client_connect (ht=<value optimized out>, return_value=0x7fa71e1a6688, return_value_ptr=<value optimized out>, this_ptr=0x7fa71e1a66b8, 
    return_value_used=<value optimized out>) at /tmp/pear/temp/swoole/swoole_client.c:858
#7  0x00000000007c02ff in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php5.4-201206232330/Zend/zend_vm_execute.h:642
#8  0x00000000007ad5c0 in execute (op_array=0x2bbe030) at /usr/local/src/php5.4-201206232330/Zend/zend_vm_execute.h:410
#9  0x00000000007386f9 in zend_call_function (fci=0x7fff1c6912b0, fci_cache=<value optimized out>) at /usr/local/src/php5.4-201206232330/Zend/zend_execute_API.c:958
#10 0x0000000000739490 in call_user_function_ex (function_table=<value optimized out>, object_pp=<value optimized out>, function_name=<value optimized out>, 
    retval_ptr_ptr=<value optimized out>, param_count=<value optimized out>, params=<value optimized out>, no_separation=0, symbol_table=0x0)
    at /usr/local/src/php5.4-201206232330/Zend/zend_execute_API.c:750
#11 0x00007fa716e73fee in php_swoole_onInterval (timer=0x7fa7170bca40, tnode=0x2be9ff0) at /tmp/pear/temp/swoole/swoole_timer.c:212
#12 0x00007fa716e9958d in swTimer_select (timer=0x7fa7170bca40) at /tmp/pear/temp/swoole/src/network/Timer.c:157
#13 0x00007fa716e8ab5f in swReactor_onTimeout_and_Finish (reactor=0x2bc9670) at /tmp/pear/temp/swoole/src/reactor/ReactorBase.c:193
#14 0x00007fa716e8abc9 in swReactor_onTimeout (reactor=0x2bc9670) at /tmp/pear/temp/swoole/src/reactor/ReactorBase.c:227
#15 0x00007fa716e8c33a in swReactorEpoll_wait (reactor=0x2bc9670, timeo=<value optimized out>) at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:297
#16 0x00007fa716e7382e in php_swoole_event_wait () at /tmp/pear/temp/swoole/swoole_event.c:190
#17 0x00000000007387ad in zend_call_function (fci=0x7fff1c691620, fci_cache=<value optimized out>) at /usr/local/src/php5.4-201206232330/Zend/zend_execute_API.c:980
#18 0x0000000000739490 in call_user_function_ex (function_table=<value optimized out>, object_pp=<value optimized out>, function_name=<value optimized out>, 
    retval_ptr_ptr=<value optimized out>, param_count=<value optimized out>, params=<value optimized out>, no_separation=1, symbol_table=0x0)
    at /usr/local/src/php5.4-201206232330/Zend/zend_execute_API.c:750
#19 0x00000000007394e2 in call_user_function (function_table=0x295bbe0, object_pp=<value optimized out>, function_name=<value optimized out>, retval_ptr=0x7fff1c6916e0, 
    param_count=<value optimized out>, params=<value optimized out>) at /usr/local/src/php5.4-201206232330/Zend/zend_execute_API.c:723
#20 0x000000000066c397 in user_shutdown_function_call (shutdown_function_entry=0x7fa715d92918) at /usr/local/src/php5.4-201206232330/ext/standard/basic_functions.c:4941
#21 0x0000000000751bf5 in zend_hash_apply (ht=0x7fa715d95188, apply_func=0x66c340 <user_shutdown_function_call>) at /usr/local/src/php5.4-201206232330/Zend/zend_hash.c:716
#22 0x000000000066d7f6 in php_call_shutdown_functions () at /usr/local/src/php5.4-201206232330/ext/standard/basic_functions.c:5033
#23 0x00000000006e89d5 in php_request_shutdown (dummy=<value optimized out>) at /usr/local/src/php5.4-201206232330/main/main.c:1718
#24 0x00000000007ede00 in do_cli (argc=2, argv=0x7fff1c692f38) at /usr/local/src/php5.4-201206232330/sapi/cli/php_cli.c:1174
#25 0x00000000007ef238 in main (argc=2, argv=0x7fff1c692f38) at /usr/local/src/php5.4-201206232330/sapi/cli/php_cli.c:1361
```

it coredump like this

**Comment by matyhtf** [comment]
请贴出你的测试代码。

**Comment by matyhtf** [comment]
请使用最新的master分支代码测试一下。
