### ISSUE TITLE
coredump when using swoole_table

### ISSUE THREAD

**Issue by millken** [swoole/swoole-src#608]
test code on php-7.0.4 ,swoole master branch 
```php
$table = new \swoole_table(1024);
$table->column('fd', \swoole_table::TYPE_INT);
$table->column('from_id', \swoole_table::TYPE_INT);
$table->column('data', \swoole_table::TYPE_STRING, 64);
$table->create();
```
```
(gdb) bt
#0  0x0000000000000002 in ?? ()
#1  0x00007fffee704394 in swTable_new (rows_size=1024)
    at /home/php/swoole-src/src/memory/Table.c:79
#2  0x00007fffee6f5b86 in zim_swoole_table___construct (execute_data=0x7ffff4a13130, 
    return_value=0x7ffff4a13120) at /home/php/swoole-src/swoole_table.c:198
#3  0x00000000007a0928 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7ffff4a13030)
    at /home/php/php-7.0.4/Zend/zend_vm_execute.h:842
#4  0x0000000000768f80 in execute_ex (ex=<value optimized out>)
    at /home/php/php-7.0.4/Zend/zend_vm_execute.h:417
#5  0x00000000007bb8bb in zend_execute (op_array=0x7ffff4a730e0, 
    return_value=<value optimized out>) at /home/php/php-7.0.4/Zend/zend_vm_execute.h:458
#6  0x000000000072a3c3 in zend_execute_scripts (type=8, retval=0x0, file_count=3)
    at /home/php/php-7.0.4/Zend/zend.c:1427
#7  0x00000000006cce20 in php_execute_script (primary_file=0x7fffffffdd30)
    at /home/php/php-7.0.4/main/main.c:2484
#8  0x00000000007bfc43 in do_cli (argc=3, argv=0xd261b0)
    at /home/php/php-7.0.4/sapi/cli/php_cli.c:974
#9  0x00000000007c03ea in main (argc=3, argv=0xd261b0)
    at /home/php/php-7.0.4/sapi/cli/php_cli.c:1345

```

**Comment by matyhtf** [comment]
使用最新的swoole-1.8.4版本未发现有core dump
