### ISSUE TITLE
coredump happened when swWorker_send2worker 

### ISSUE THREAD

**Issue by lilien1010** [swoole/swoole-src#734]
```
(gdb) bt
#0  swWorker_send2worker (dst_worker=dst_worker@entry=0x7f683da5ef88, buf=buf@entry=0x7fff084884c0, n=n@entry=299, flag=flag@entry=3) at /tmp/pear/temp/swoole/src/network/Worker.c:579
#1  0x00007f683e6e4160 in swProcessPool_dispatch (pool=<optimized out>, data=data@entry=0x7fff084884c0, dst_worker_id=dst_worker_id@entry=0x7fff08488498)
    at /tmp/pear/temp/swoole/src/network/ProcessPool.c:152
#2  0x00007f683e6bd8af in zim_swoole_server_task (ht=<optimized out>, return_value=0x7f683bd7e608, return_value_ptr=<optimized out>, this_ptr=<optimized out>, 
    return_value_used=<optimized out>) at /tmp/pear/temp/swoole/swoole_server.c:2316
#3  0x00000000007f2268 in zend_do_fcall_common_helper_SPEC (execute_data=0x7f6844f5ab40) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:643
#4  0x0000000000773a8c in execute (op_array=0x7f683bd426d8) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:410
#5  0x0000000000741181 in zend_call_function (fci=fci@entry=0x7fff0848a700, fci_cache=<optimized out>, fci_cache@entry=0x0) at /usr/local/src/php-5.4.40/Zend/zend_execute_API.c:956
#6  0x00000000007414be in call_user_function_ex (function_table=<optimized out>, object_pp=object_pp@entry=0x0, function_name=<optimized out>, 
    retval_ptr_ptr=retval_ptr_ptr@entry=0x7fff0848a7a8, param_count=param_count@entry=4, params=<optimized out>, no_separation=no_separation@entry=0, symbol_table=symbol_table@entry=0x0)
    at /usr/local/src/php-5.4.40/Zend/zend_execute_API.c:748
#7  0x00007f683e6ba72c in php_swoole_onReceive (serv=<optimized out>, req=<optimized out>) at /tmp/pear/temp/swoole/swoole_server.c:610
#8  0x00007f683e6e9ec9 in swWorker_onTask (factory=factory@entry=0x2122220, task=task@entry=0x7fff0848a850) at /tmp/pear/temp/swoole/src/network/Worker.c:192
#9  0x00007f683e6ea1f1 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7fff0848c8b0) at /tmp/pear/temp/swoole/src/network/Worker.c:542
#10 0x00007f683e6dd080 in swReactorEpoll_wait (reactor=0x2162bb0, timeo=<optimized out>) at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:258
#11 0x00007f683e6ead60 in swWorker_loop (factory=factory@entry=0x2122220, worker_id=worker_id@entry=1) at /tmp/pear/temp/swoole/src/network/Worker.c:489
#12 0x00007f683e6e83a0 in swManager_spawn_worker (factory=0x2122220, worker_id=1) at /tmp/pear/temp/swoole/src/network/Manager.c:682
#13 0x00007f683e6e87b7 in swManager_start (factory=factory@entry=0x2122220) at /tmp/pear/temp/swoole/src/network/Manager.c:135
#14 0x00007f683e6da342 in swFactoryProcess_start (factory=0x2122220) at /tmp/pear/temp/swoole/src/factory/FactoryProcess.c:86
#15 0x00007f683e6e0889 in swServer_start (serv=serv@entry=0x2121df0) at /tmp/pear/temp/swoole/src/network/Server.c:620
#16 0x00007f683e6bc628 in zim_swoole_server_start (ht=<optimized out>, return_value=0x7f6844f92fa0, return_value_ptr=<optimized out>, this_ptr=0x7f6844f8fb18, 
    return_value_used=<optimized out>) at /tmp/pear/temp/swoole/swoole_server.c:1781
#17 0x00000000007f2268 in zend_do_fcall_common_helper_SPEC (execute_data=0x7f6844f5a198) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:643
#18 0x0000000000773a8c in execute (op_array=0x7f6844f8f1f0) at /usr/local/src/php-5.4.40/Zend/zend_vm_execute.h:410
#19 0x000000000074f25e in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /usr/local/src/php-5.4.40/Zend/zend.c:1329
#20 0x00000000006f2c49 in php_execute_script (primary_file=primary_file@entry=0x7fff0848ef90) at /usr/local/src/php-5.4.40/main/main.c:2502
#21 0x00000000007f40e4 in do_cli (argc=4, argv=0x7fff08490368) at /usr/local/src/php-5.4.40/sapi/cli/php_cli.c:989
#22 0x0000000000432a38 in main (argc=4, argv=0x7fff08490368) at /usr/local/src/php-5.4.40/sapi/cli/php_cli.c:1365
(gdb) 
```

**Comment by lilien1010** [comment]
这个问题从 好几个版本以前就有了，一直没有解决··

**Comment by lilien1010** [comment]
```
swoole support => enabled
Version => 1.8.4
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
Linux Native AIO => enabled
GCC AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608
```
php 版本 5.4.40

**Comment by matyhtf** [comment]
启动顺序问题导致，现在已经改为先启动task进程。另外gcc版本是否过低
