### ISSUE TITLE
swoole_http_client close时coredump

### ISSUE THREAD

**Issue by dailei** [swoole/swoole-src#755]
PHP-5.6.22 + SWOOLE-1.8.7

```
swoole

swoole support => enabled
Version => 1.8.7
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
sockets => enabled
openssl => enabled
http2 => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608
```

```
<?php

$client = new swoole_http_client('172.16.3.8');
$client->close();

```

```
(gdb) bt
#0  0x00007ff3a0e51019 in zim_swoole_http_client_close (ht=0, return_value=0x7ff3a78bff70, return_value_ptr=<value optimized out>, this_ptr=0x7ff3a78bffd0, 
    return_value_used=0) at /usr/local/src/swoole-src-1.8.7-stable/swoole_http_client.c:975
#1  0x000000000078af12 in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php-5.6.22/Zend/zend_vm_execute.h:558
#2  0x000000000077a7a0 in execute_ex (execute_data=0x7ff3a788c178) at /usr/local/src/php-5.6.22/Zend/zend_vm_execute.h:363
#3  0x000000000070bfb9 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/local/src/php-5.6.22/Zend/zend.c:1341
#4  0x00000000006ab73a in php_execute_script (primary_file=0x7ffdd73dd450) at /usr/local/src/php-5.6.22/main/main.c:2613
#5  0x00000000007b2a1c in do_cli (argc=2, argv=0x13de0b0) at /usr/local/src/php-5.6.22/sapi/cli/php_cli.c:994
#6  0x00000000007b31b8 in main (argc=2, argv=0x13de0b0) at /usr/local/src/php-5.6.22/sapi/cli/php_cli.c:1378
```

**Comment by matyhtf** [comment]
感谢反馈，已修复。
