### ISSUE TITLE
worker不定期出现signal=11

### ISSUE THREAD

**Issue by safecat** [swoole/swoole-src#764]
用swoole写了一个im，上线后看起来运行正常，一天后查看错误日志发现大量报错如：

```
[2016-07-15 00:19:10 $1800.0]	WARNING	swManager_check_exit_status: worker#1 abnormal exit, status=0, signal=11
[2016-07-15 00:23:21 $1800.0]	WARNING	swManager_check_exit_status: worker#3 abnormal exit, status=0, signal=11
[2016-07-15 00:23:34 $1800.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11
[2016-07-15 00:24:08 $1800.0]	WARNING	swManager_check_exit_status: worker#1 abnormal exit, status=0, signal=11
[2016-07-15 00:26:07 $1800.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11
[2016-07-15 00:26:21 $1800.0]	WARNING	swManager_check_exit_status: worker#3 abnormal exit, status=0, signal=11
[2016-07-15 00:27:22 $1800.0]	WARNING	swManager_check_exit_status: worker#3 abnormal exit, status=0, signal=11
[2016-07-15 00:30:33 $1800.0]	WARNING	swManager_check_exit_status: worker#3 abnormal exit, status=0, signal=11
```

但无法稳定重现，用ab打或者curl循环都无法复现（完全无法复现），切换到测试环境服务器就没问题，开发机（mac）也无法重现，但两机软硬件配置几乎完全一样，仅内存大小、worker数量、mysql配置不同。PHP版本如下：

```
PHP 5.5.9-1ubuntu4.18 (cli) (built: Jun  1 2016 12:46:54) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo
```

后来发现一个稳定复现的方式：用Firefox打开im界面，在界面完全加载（要执行4个Http请求）之前按下刷新键，如此快速刷新十多遍，基本上一定会导致一个worker退出。在chrome上如法炮制，发现复现难度提高，大约刷新几十遍才能复现一次，有时刷新一百多次都很难复现。但因为有了Firefox的比较稳定的复现，得以用gdb -p pid的方式调试，得出报错如下：

```
(gdb) bt
#0  0x00000000006c6e5a in ?? ()
#1  0x00000000006c8be2 in _estrndup ()
#2  0x00000000006608d1 in php_var_unserialize ()
#3  0x00000000004603e0 in ?? ()
#4  0x0000000000660955 in php_var_unserialize ()
#5  0x000000000046043d in ?? ()
#6  0x0000000000660955 in php_var_unserialize ()
#7  0x00007f6f5b03fdda in php_swoole_get_task_result (task_result=task_result@entry=0x7ffda739f810)
    at /tmp/pear/temp/swoole/swoole_server.c:235
#8  0x00007f6f5b040042 in php_swoole_onFinish (serv=<optimized out>, req=0x7ffda739f810)
    at /tmp/pear/temp/swoole/swoole_server.c:818
#9  0x00007f6f5b079b0e in swWorker_onTask (factory=factory@entry=0x11ef790, task=task@entry=0x7ffda739f810)
    at /tmp/pear/temp/swoole/src/network/Worker.c:274
#10 0x00007f6f5b079dd9 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7ffda73a1890)
    at /tmp/pear/temp/swoole/src/network/Worker.c:549
#11 0x00007f6f5b06bca9 in swReactorEpoll_wait (reactor=0x11f3640, timeo=<optimized out>)
    at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:258
#12 0x00007f6f5b07a9e3 in swWorker_loop (factory=factory@entry=0x11ef790, worker_id=worker_id@entry=3)
    at /tmp/pear/temp/swoole/src/network/Worker.c:496
#13 0x00007f6f5b077dcc in swManager_spawn_worker (factory=0x11ef790, worker_id=3)
    at /tmp/pear/temp/swoole/src/network/Manager.c:679
#14 0x00007f6f5b0789d5 in swManager_loop_sync (factory=0x11ef790) at /tmp/pear/temp/swoole/src/network/Manager.c:539
#15 swManager_start (factory=factory@entry=0x11ef790) at /tmp/pear/temp/swoole/src/network/Manager.c:183
#16 0x00007f6f5b068b62 in swFactoryProcess_start (factory=0x11ef790) at /tmp/pear/temp/swoole/src/factory/FactoryProcess.c:86
#17 0x00007f6f5b06f339 in swServer_start (serv=serv@entry=0x11ef360) at /tmp/pear/temp/swoole/src/network/Server.c:645
#18 0x00007f6f5b0520c7 in zim_swoole_http_server_start (ht=<optimized out>, return_value=0x7f6f5db3b310, 
    return_value_ptr=<optimized out>, this_ptr=0x7f6f5db3f738, return_value_used=<optimized out>)
    at /tmp/pear/temp/swoole/swoole_http_server.c:1379
#19 0x00000000006dd80b in dtrace_execute_internal ()
#20 0x000000000079c790 in ?? ()
#21 0x00000000007170c8 in execute_ex ()
#22 0x00000000006dd709 in dtrace_execute_ex ()
#23 0x000000000079cde0 in ?? ()
#24 0x00000000007170c8 in execute_ex ()
#25 0x00000000006dd709 in dtrace_execute_ex ()
#26 0x00000000006eed60 in zend_execute_scripts ()
#27 0x000000000068f765 in php_execute_script ()
#28 0x000000000079e76e in ?? ()
#29 0x0000000000461d80 in main ()
```

不懂C，从中找不到什么有用的信息。bug复现几十遍，报错都是如此。

后来在前面挡了一层nginx，发现报错内容变了，而且报错不止一种，粘贴如下：

```
(gdb) bt
#0  0x00000000006c6e5a in ?? ()
#1  0x00000000006c8be2 in _estrndup ()
#2  0x00000000006f13fc in add_assoc_string_ex ()
#3  0x0000000000701c8f in zend_fetch_debug_backtrace ()
#4  0x0000000000701f78 in ?? ()
#5  0x00000000006dd80b in dtrace_execute_internal ()
#6  0x000000000079c790 in ?? ()
#7  0x00000000007170c8 in execute_ex ()
#8  0x00000000006dd709 in dtrace_execute_ex ()
#9  0x000000000079cde0 in ?? ()
#10 0x00000000007170c8 in execute_ex ()
#11 0x00000000006dd709 in dtrace_execute_ex ()
#12 0x000000000079cde0 in ?? ()
#13 0x00000000007170c8 in execute_ex ()
#14 0x00000000006dd709 in dtrace_execute_ex ()
#15 0x00000000006dfa01 in zend_call_function ()
#16 0x00000000006dfbfe in call_user_function_ex ()
#17 0x00007f9e6c6bfc0a in http_onReceive (serv=<optimized out>, req=<optimized out>)
    at /tmp/pear/temp/swoole/swoole_http_server.c:994
#18 0x00007f9e6c6e3a09 in swWorker_onTask (factory=factory@entry=0x1727780, task=task@entry=0x7fff008a1c10)
    at /tmp/pear/temp/swoole/src/network/Worker.c:193
#19 0x00007f9e6c6e3dd9 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7fff008a3c90)
    at /tmp/pear/temp/swoole/src/network/Worker.c:549
#20 0x00007f9e6c6d5ca9 in swReactorEpoll_wait (reactor=0x172b630, timeo=<optimized out>)
    at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:258
#21 0x00007f9e6c6e49e3 in swWorker_loop (factory=factory@entry=0x1727780, worker_id=worker_id@entry=3)
    at /tmp/pear/temp/swoole/src/network/Worker.c:496
#22 0x00007f9e6c6e1dcc in swManager_spawn_worker (factory=0x1727780, worker_id=3)
    at /tmp/pear/temp/swoole/src/network/Manager.c:679
#23 0x00007f9e6c6e29d5 in swManager_loop_sync (factory=0x1727780) at /tmp/pear/temp/swoole/src/network/Manager.c:539
#24 swManager_start (factory=factory@entry=0x1727780) at /tmp/pear/temp/swoole/src/network/Manager.c:183
#25 0x00007f9e6c6d2b62 in swFactoryProcess_start (factory=0x1727780) at /tmp/pear/temp/swoole/src/factory/FactoryProcess.c:86
#26 0x00007f9e6c6d9339 in swServer_start (serv=serv@entry=0x1727350) at /tmp/pear/temp/swoole/src/network/Server.c:645
#27 0x00007f9e6c6bc0c7 in zim_swoole_http_server_start (ht=<optimized out>, return_value=0x7f9e6f197f68, 
    return_value_ptr=<optimized out>, this_ptr=0x7f9e6f1aa098, return_value_used=<optimized out>)
    at /tmp/pear/temp/swoole/swoole_http_server.c:1379
#28 0x00000000006dd80b in dtrace_execute_internal ()
#29 0x000000000079c790 in ?? ()
#30 0x00000000007170c8 in execute_ex ()
#31 0x00000000006dd709 in dtrace_execute_ex ()
#32 0x000000000079cde0 in ?? ()
#33 0x00000000007170c8 in execute_ex ()
#34 0x00000000006dd709 in dtrace_execute_ex ()
---Type <return> to continue, or q <return> to quit---
#35 0x00000000006eed60 in zend_execute_scripts ()
#36 0x000000000068f765 in php_execute_script ()
#37 0x000000000079e76e in ?? ()
#38 0x0000000000461d80 in main ()
```

```
(gdb) bt
#0  0x00000000006c6e5a in ?? ()
#1  0x00000000006c8be2 in _estrndup ()
#2  0x00000000006f13fc in add_assoc_string_ex ()
#3  0x00007f9e6c6c0033 in http_onReceive (serv=<optimized out>, req=<optimized out>)
    at /tmp/pear/temp/swoole/swoole_http_server.c:958
#4  0x00007f9e6c6e3a09 in swWorker_onTask (factory=factory@entry=0x1727780, task=task@entry=0x7fff008a1c10)
    at /tmp/pear/temp/swoole/src/network/Worker.c:193
#5  0x00007f9e6c6e3dd9 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7fff008a3c90)
    at /tmp/pear/temp/swoole/src/network/Worker.c:549
#6  0x00007f9e6c6d5ca9 in swReactorEpoll_wait (reactor=0x172b630, timeo=<optimized out>)
    at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:258
#7  0x00007f9e6c6e49e3 in swWorker_loop (factory=factory@entry=0x1727780, worker_id=worker_id@entry=3)
    at /tmp/pear/temp/swoole/src/network/Worker.c:496
#8  0x00007f9e6c6e1dcc in swManager_spawn_worker (factory=0x1727780, worker_id=3)
    at /tmp/pear/temp/swoole/src/network/Manager.c:679
#9  0x00007f9e6c6e29d5 in swManager_loop_sync (factory=0x1727780) at /tmp/pear/temp/swoole/src/network/Manager.c:539
#10 swManager_start (factory=factory@entry=0x1727780) at /tmp/pear/temp/swoole/src/network/Manager.c:183
#11 0x00007f9e6c6d2b62 in swFactoryProcess_start (factory=0x1727780) at /tmp/pear/temp/swoole/src/factory/FactoryProcess.c:86
#12 0x00007f9e6c6d9339 in swServer_start (serv=serv@entry=0x1727350) at /tmp/pear/temp/swoole/src/network/Server.c:645
#13 0x00007f9e6c6bc0c7 in zim_swoole_http_server_start (ht=<optimized out>, return_value=0x7f9e6f197f68, 
    return_value_ptr=<optimized out>, this_ptr=0x7f9e6f1aa098, return_value_used=<optimized out>)
    at /tmp/pear/temp/swoole/swoole_http_server.c:1379
#14 0x00000000006dd80b in dtrace_execute_internal ()
#15 0x000000000079c790 in ?? ()
#16 0x00000000007170c8 in execute_ex ()
#17 0x00000000006dd709 in dtrace_execute_ex ()
#18 0x000000000079cde0 in ?? ()
#19 0x00000000007170c8 in execute_ex ()
#20 0x00000000006dd709 in dtrace_execute_ex ()
#21 0x00000000006eed60 in zend_execute_scripts ()
#22 0x000000000068f765 in php_execute_script ()
#23 0x000000000079e76e in ?? ()
#24 0x0000000000461d80 in main ()
```

```
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00000000006c6e5a in ?? ()
(gdb) bt
#0  0x00000000006c6e5a in ?? ()
#1  0x00000000006c8be2 in _estrndup ()
#2  0x00000000004e80ab in ?? ()
#3  0x000000000069d2d4 in php_default_treat_data ()
#4  0x00000000005458cd in mbstr_treat_data ()
#5  0x00007f9e6c6bbb6b in http_request_on_body (parser=<optimized out>, 
    at=0x7f9e5bd1acca "company_id=c9c2e7nok2ap&referrer=&title=&pv=&platform=pc&uid=u9c2e7ntj1vo", length=73)
    at /tmp/pear/temp/swoole/swoole_http_server.c:778
#6  0x00007f9e6c6ea479 in php_http_parser_execute (parser=0x7f9e5d304fd0, settings=<optimized out>, data=<optimized out>, 
    len=<optimized out>) at /tmp/pear/temp/swoole/thirdparty/php_http_parser.c:1436
#7  0x00007f9e6c6bfa55 in http_onReceive (serv=<optimized out>, req=0x7fff008a1c10)
    at /tmp/pear/temp/swoole/swoole_http_server.c:913
#8  0x00007f9e6c6e3a09 in swWorker_onTask (factory=factory@entry=0x1727780, task=task@entry=0x7fff008a1c10)
    at /tmp/pear/temp/swoole/src/network/Worker.c:193
#9  0x00007f9e6c6e3dd9 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7fff008a3c90)
    at /tmp/pear/temp/swoole/src/network/Worker.c:549
#10 0x00007f9e6c6d5ca9 in swReactorEpoll_wait (reactor=0x172a9e0, timeo=<optimized out>)
    at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:258
#11 0x00007f9e6c6e49e3 in swWorker_loop (factory=factory@entry=0x1727780, worker_id=worker_id@entry=3)
    at /tmp/pear/temp/swoole/src/network/Worker.c:496
#12 0x00007f9e6c6e1dcc in swManager_spawn_worker (factory=0x1727780, worker_id=3)
    at /tmp/pear/temp/swoole/src/network/Manager.c:679
#13 0x00007f9e6c6e21ef in swManager_start (factory=factory@entry=0x1727780) at /tmp/pear/temp/swoole/src/network/Manager.c:143
#14 0x00007f9e6c6d2b62 in swFactoryProcess_start (factory=0x1727780) at /tmp/pear/temp/swoole/src/factory/FactoryProcess.c:86
---Type <return> to continue, or q <return> to quit---
#15 0x00007f9e6c6d9339 in swServer_start (serv=serv@entry=0x1727350) at /tmp/pear/temp/swoole/src/network/Server.c:645
#16 0x00007f9e6c6bc0c7 in zim_swoole_http_server_start (ht=<optimized out>, return_value=0x7f9e6f197f68, 
    return_value_ptr=<optimized out>, this_ptr=0x7f9e6f1aa098, return_value_used=<optimized out>)
    at /tmp/pear/temp/swoole/swoole_http_server.c:1379
#17 0x00000000006dd80b in dtrace_execute_internal ()
#18 0x000000000079c790 in ?? ()
#19 0x00000000007170c8 in execute_ex ()
#20 0x00000000006dd709 in dtrace_execute_ex ()
#21 0x000000000079cde0 in ?? ()
#22 0x00000000007170c8 in execute_ex ()
#23 0x00000000006dd709 in dtrace_execute_ex ()
#24 0x00000000006eed60 in zend_execute_scripts ()
#25 0x000000000068f765 in php_execute_script ()
#26 0x000000000079e76e in ?? ()
#27 0x0000000000461d80 in main ()
```

重启机器问题依旧。

ubuntu 14.04 64bit，swoole版本是1.8.7，不知道为什么不打coredump（ulimit命令执行过了），只能用插入pid的方式去gdb，搞了一整天，在PHP代码里到处打日志做实验，实在蒙圈，还望作者赐教，万分感谢！

**Comment by safecat** [comment]
早上详细对比了测试环境和正式环境后发现因为测试环境安装的比较早（pecl install swoole），所以swoole版本=1.8.4，将其升级到1.8.7之后，复现问题。多次测试后发现从1.8.6开始有此问题，1.8.4/5都没有问题，1.8.4只会报
```
[2016-07-15 11:12:44 *22260.0]	ERROR	swFactoryProcess_finish (ERROR 1004): send 482 byte failed, because session#111 is closed.
[2016-07-15 11:12:46 *22260.0]	ERROR	swFactoryProcess_finish (ERROR 1004): send 1573 byte failed, because session#115 is closed.
[2016-07-15 11:12:46 *22260.0]	ERROR	swFactoryProcess_finish (ERROR 1004): send 1573 byte failed, because session#116 is closed.
[2016-07-15 11:13:12 *22260.0]	ERROR	swFactoryProcess_finish (ERROR 1004): send 1573 byte failed, because session#150 is closed.
[2016-07-15 11:13:25 *22260.0]	ERROR	swFactoryProcess_finish (ERROR 1004): send 1573 byte failed, because session#191 is closed.
```
worker不会crash

**Comment by matyhtf** [comment]
因为 User Cancel 导致的内存读取错误，已解决。

https://github.com/swoole/swoole-src/issues/768
