### ISSUE TITLE
swoole_http_server 在 Mac 下高并发请求出错

### ISSUE THREAD

**Issue by andot** [swoole/swoole-src#779]
测试环境：

Mac OS X 10.11.6
PHP 5.5
swoole 1.8.7

测试程序：
https://github.com/hprose/hprose-swoole/blob/master/examples/src/HttpServer.php
https://github.com/hprose/hprose-swoole/blob/master/examples/src/HttpClientBenchmark.php

先运行服务器，再运行客户端，服务器端会不断输出：

```
[2016-07-25 20:34:45 *37519.0]  WARNING swReactorKqueue_wait: kqueue event unknow filter=-1
[2016-07-25 20:34:45 *37519.0]  WARNING swReactorKqueue_wait: kqueue event unknow filter=-1
[2016-07-25 20:34:45 *37519.0]  WARNING swReactorKqueue_wait: kqueue event unknow filter=-1
[2016-07-25 20:34:45 *37519.0]  WARNING swReactorKqueue_wait: kqueue event unknow filter=-1
[2016-07-25 20:34:45 *37519.0]  WARNING swReactorKqueue_wait: kqueue event unknow filter=-1
[2016-07-25 20:34:45 *37519.0]  WARNING swReactorKqueue_wait: kqueue event unknow filter=-1

```

直到终端会失去响应。

该程序在 Linux 上测试没有问题。

测试环境为：

Ubuntu 64bit 16.04
PHP 7
swoole 1.8.7

运行结果为服务器端无输出（正常），客户端输出：

```
float(1.3037090301514)
float(0.00013037090301514)
```

**Comment by andot** [comment]
在测试环境为：

Ubuntu 64bit 16.04
PHP 7.0.4
swoole 1.8.8-rc1

下运行上面的程序，客户端崩溃：

```php
(gdb) bt
#0  php_swoole_client_check_setting (cli=0x0, zset=<optimized out>)
    at /home/andot/桌面/swoole-src/swoole_client.c:357
#1  0x00007fffefa52256 in http_client_create (object=0x7ffff390f9f0)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:773
#2  http_client_execute (zobject=0x7ffff390f9f0, uri=0x7ffff388b458 "/", 
    uri_len=1, callback=0x7ffff390fa50)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:211
#3  0x00007fffefa527d6 in zim_swoole_http_client_post (
    execute_data=0x7ffff390f9d0, return_value=0x7ffff390f9a0)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:1286
#4  0x00005555557a18aa in dtrace_execute_internal ()
#5  0x0000555555835320 in ?? ()
#6  0x00005555557f116b in execute_ex ()
#7  0x00005555557a1741 in dtrace_execute_ex ()
#8  0x000055555583545d in ?? ()
#9  0x00005555557f116b in execute_ex ()
#10 0x00005555557a1741 in dtrace_execute_ex ()
#11 0x000055555583545d in ?? ()
#12 0x00005555557f116b in execute_ex ()
#13 0x00005555557a1741 in dtrace_execute_ex ()
#14 0x000055555583545d in ?? ()
#15 0x00005555557f116b in execute_ex ()
#16 0x00005555557a1741 in dtrace_execute_ex ()
---Type <return> to continue, or q <return> to quit---
#17 0x000055555583545d in ?? ()
#18 0x00005555557f116b in execute_ex ()
#19 0x00005555557a1741 in dtrace_execute_ex ()
#20 0x000055555583545d in ?? ()
#21 0x00005555557f116b in execute_ex ()
#22 0x00005555557a1741 in dtrace_execute_ex ()
#23 0x000055555583545d in ?? ()
#24 0x00005555557f116b in execute_ex ()
#25 0x00005555557a1741 in dtrace_execute_ex ()
#26 0x000055555583545d in ?? ()
#27 0x00005555557f116b in execute_ex ()
#28 0x00005555557a1741 in dtrace_execute_ex ()
#29 0x000055555583545d in ?? ()
#30 0x00005555557f116b in execute_ex ()
#31 0x00005555557a1741 in dtrace_execute_ex ()
#32 0x000055555583545d in ?? ()
#33 0x00005555557f116b in execute_ex ()
#34 0x00005555557a1741 in dtrace_execute_ex ()
#35 0x000055555583545d in ?? ()
#36 0x00005555557f116b in execute_ex ()
#37 0x00005555557a1741 in dtrace_execute_ex ()
#38 0x000055555583545d in ?? ()
#39 0x00005555557f116b in execute_ex ()
---Type <return> to continue, or q <return> to quit---
#40 0x00005555557a1741 in dtrace_execute_ex ()
#41 0x00005555557a335c in zend_call_function ()
#42 0x00005555556f0b95 in zif_call_user_func ()
#43 0x00005555557a18aa in dtrace_execute_internal ()
#44 0x0000555555835320 in ?? ()
#45 0x00005555557f116b in execute_ex ()
#46 0x00005555557a1741 in dtrace_execute_ex ()
#47 0x000055555583545d in ?? ()
#48 0x00005555557f116b in execute_ex ()
#49 0x00005555557a1741 in dtrace_execute_ex ()
#50 0x000055555583545d in ?? ()
#51 0x00005555557f116b in execute_ex ()
#52 0x00005555557a1741 in dtrace_execute_ex ()
#53 0x00005555557a335c in zend_call_function ()
#54 0x00005555556f0b95 in zif_call_user_func ()
#55 0x00005555557a18aa in dtrace_execute_internal ()
#56 0x0000555555835320 in ?? ()
#57 0x00005555557f116b in execute_ex ()
#58 0x00005555557a1741 in dtrace_execute_ex ()
#59 0x000055555583545d in ?? ()
#60 0x00005555557f116b in execute_ex ()
#61 0x00005555557a1741 in dtrace_execute_ex ()
#62 0x000055555583545d in ?? ()
---Type <return> to continue, or q <return> to quit---
#63 0x00005555557f116b in execute_ex ()
#64 0x00005555557a1741 in dtrace_execute_ex ()
#65 0x000055555583545d in ?? ()
#66 0x00005555557f116b in execute_ex ()
#67 0x00005555557a1741 in dtrace_execute_ex ()
#68 0x000055555583545d in ?? ()
#69 0x00005555557f116b in execute_ex ()
#70 0x00005555557a1741 in dtrace_execute_ex ()
#71 0x000055555583545d in ?? ()
#72 0x00005555557f116b in execute_ex ()
#73 0x00005555557a1741 in dtrace_execute_ex ()
#74 0x000055555583545d in ?? ()
#75 0x00005555557f116b in execute_ex ()
#76 0x00005555557a1741 in dtrace_execute_ex ()
#77 0x0000555555834708 in ?? ()
#78 0x00005555557f116b in execute_ex ()
#79 0x00005555557a1741 in dtrace_execute_ex ()
#80 0x00005555557a335c in zend_call_function ()
#81 0x00005555556f0d6b in zif_call_user_func_array ()
#82 0x00005555557a18aa in dtrace_execute_internal ()
#83 0x0000555555835320 in ?? ()
#84 0x00005555557f116b in execute_ex ()
#85 0x00005555557a1741 in dtrace_execute_ex ()
---Type <return> to continue, or q <return> to quit---
#86 0x0000555555834708 in ?? ()
#87 0x00005555557f116b in execute_ex ()
#88 0x00005555557a1741 in dtrace_execute_ex ()
#89 0x000055555583545d in ?? ()
#90 0x00005555557f116b in execute_ex ()
#91 0x00005555557a1741 in dtrace_execute_ex ()
#92 0x00005555557dd436 in zend_generator_resume ()
#93 0x00005555557de490 in zim_Generator_current ()
#94 0x00005555557a18aa in dtrace_execute_internal ()
#95 0x0000555555835320 in ?? ()
#96 0x00005555557f116b in execute_ex ()
#97 0x00005555557a1741 in dtrace_execute_ex ()
#98 0x000055555583545d in ?? ()
#99 0x00005555557f116b in execute_ex ()
#100 0x00005555557a1741 in dtrace_execute_ex ()
#101 0x0000555555843fd7 in zend_execute ()
#102 0x00005555557b1993 in zend_execute_scripts ()
#103 0x00005555557524e0 in php_execute_script ()
#104 0x0000555555845ca4 in ?? ()
#105 0x0000555555637d54 in main ()
(gdb) 
```

**Comment by wanminny** [comment]
mac 同有！OS X 10.11.4 (15E65)

**Comment by superbogy** [comment]
+1

**Comment by ljj7410** [comment]
+1

**Comment by Robert-Xie** [comment]
+1

**Comment by xuguoliangjj** [comment]
+1

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/5125878684c2c7e2ef66de80036f751ae9d5c72b

**Comment by matyhtf** [comment]
已修复
