### ISSUE TITLE
swoole_http_client 的 websocket 崩溃

### ISSUE THREAD

**Issue by andot** [swoole/swoole-src#781]
服务器代码：
```php
<?php
$server = new swoole_websocket_server("0.0.0.0", 9501);

$server->on('open', function ($server, $request) {
    echo "server: handshake success with fd{$request->fd}\n";
});

$server->on('message', function ($server, $frame) {
    var_dump($frame->data);
    $server->push($frame->fd, $frame->data, $frame->opcode, true);
});

$server->on('close', function ($ser, $fd) {
    echo "client {$fd} closed\n";
});

$server->start();
```

客户端代码：
```php
<?php
$client = new swoole_http_client('127.0.0.1', 9501);

$client->on('message', function ($client, $frame) {
    var_dump($frame->data);
});

$client->upgrade('/', function($client) {
    $client->push('Hello World');
    for ($i = 0; $i < 10; $i++) {
        $client->push('Hello World' . $i);
    }
});
```

测试环境：

Ubuntu 14.06 64bit
PHP 7.0.4
swoole-1.8.8-rc1

先执行服务器，后执行客户端，服务器无输出，客户端直接崩溃。gdb 调试信息如下：

```
(gdb) bt
#0  0x00005555557c505c in zend_hash_str_find ()
#1  0x00007fffefa406ba in sw_zend_hash_find (v=<synthetic pointer>, len=15, 
    k=0x7fffefa7db9a "open_eof_split", ht=0x0)
    at /home/andot/桌面/swoole-src/php7_wrapper.h:309
#2  php_swoole_client_check_setting (cli=0x0, zset=<optimized out>)
    at /home/andot/桌面/swoole-src/swoole_client.c:294
#3  0x00007fffefa52256 in http_client_create (object=0x7ffff3813130)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:773
#4  http_client_execute (zobject=0x7ffff3813130, uri=0x7ffff3860838 "/", 
    uri_len=1, callback=0x7ffff3813180)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:211
#5  0x00007fffefa52576 in zim_swoole_http_client_upgrade (
    execute_data=0x7ffff3813110, return_value=0x7ffff3813100)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:1339
#6  0x00005555557a18aa in dtrace_execute_internal ()
#7  0x0000555555835320 in ?? ()
#8  0x00005555557f116b in execute_ex ()
#9  0x00005555557a1741 in dtrace_execute_ex ()
#10 0x0000555555843fd7 in zend_execute ()
#11 0x00005555557b1993 in zend_execute_scripts ()
#12 0x00005555557524e0 in php_execute_script ()
#13 0x0000555555845ca4 in ?? ()
#14 0x0000555555637d54 in main ()
```

**Comment by andot** [comment]
运行刚刚的修正版之后，gdb信息变为如下内容：
```gdb
(gdb) bt
#0  0x00007fffefa52256 in http_client_create (object=0x7ffff3813130)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:775
#1  http_client_execute (zobject=0x7ffff3813130, uri=0x7ffff3860838 "/", 
    uri_len=1, callback=0x7ffff3813180)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:211
#2  0x00007fffefa52576 in zim_swoole_http_client_upgrade (
    execute_data=0x7ffff3813110, return_value=0x7ffff3813100)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:1339
#3  0x00005555557a18aa in dtrace_execute_internal ()
#4  0x0000555555835320 in ?? ()
#5  0x00005555557f116b in execute_ex ()
#6  0x00005555557a1741 in dtrace_execute_ex ()
#7  0x0000555555843fd7 in zend_execute ()
#8  0x00005555557b1993 in zend_execute_scripts ()
#9  0x00005555557524e0 in php_execute_script ()
#10 0x0000555555845ca4 in ?? ()
#11 0x0000555555637d54 in main ()
(gdb) 
```
