### ISSUE TITLE
swoole_http_client 的 websocket 崩溃

### ISSUE THREAD

**Issue by andot** [swoole/swoole-src#782]
https://github.com/swoole/swoole-src/issues/781

运行刚刚的修正版之后，gdb信息变为如下内容：

```gdb
(gdb) bt
#0  0x00007fffefa52256 in http_client_create (object=0x7ffff3813130)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:775
#1  http_client_execute (zobject=0x7ffff3813130, uri=0x7ffff3860838 "/", 
    uri_len=1, callback=0x7ffff3813180)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:211
#2  0x00007fffefa52576 in zim_swoole_http_client_upgrade (
    execute_data=0x7ffff3813110, return_value=0x7ffff3813100)
    at /home/andot/桌面/swoole-src/swoole_http_client.c:1339
#3  0x00005555557a18aa in dtrace_execute_internal ()
#4  0x0000555555835320 in ?? ()
#5  0x00005555557f116b in execute_ex ()
#6  0x00005555557a1741 in dtrace_execute_ex ()
#7  0x0000555555843fd7 in zend_execute ()
#8  0x00005555557b1993 in zend_execute_scripts ()
#9  0x00005555557524e0 in php_execute_script ()
#10 0x0000555555845ca4 in ?? ()
#11 0x0000555555637d54 in main ()
(gdb) 
```

**Comment by matyhtf** [comment]
确实存在问题，这里实现有问题。现在重新解决后，用你的程序测试没问题了。

**Comment by andot** [comment]
嗯，测试成功 ✌️
