### ISSUE TITLE
申请内存 core问题

### ISSUE THREAD

**Issue by iou402** [swoole/swoole-src#817]
woole版本 1.8.4 
php版本 7.0.2

问题描述: malloc 申请内存时会造成core 从gdb中可以看出 table->lock.lock(&table->lock);然后swTableRow **tmp = sw_malloc(sizeof(swTableRow *) * table->size); 就core了 造成锁都没有释放,重启之后进程就一直在等待锁 死了

```php
#0  0x000000319f876083 in malloc_consolidate () from /lib64/libc.so.6
#1  0x000000319f879c28 in _int_malloc () from /lib64/libc.so.6
#2  0x000000319f87ab1c in malloc () from /lib64/libc.so.6
#3  0x00007f856b594ae6 in swTable_compress_list (table=0x7f856a3d74a8) at /tools/php7/swoole-1.8.4/src/memory/Table.c:38
#4  0x00007f856b594e6c in swTableRow_del (table=0x7f856a3d74a8, key=0x7f854714c7c0 "42539740", keylen=8)
    at /tools/php7/swoole-1.8.4/src/memory/Table.c:446
#5  0x00007f856b5830cb in zim_swoole_table_del (execute_data=0x7f856ba14700, return_value=0x7f856ba146d0)
    at /tools/php7/swoole-1.8.4/swoole_table.c:504
#6  0x000000000087eb47 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f856ba145c0)
    at /tools/php7/php-7.0.2/Zend/zend_vm_execute.h:842
#7  0x0000000000846f50 in execute_ex (ex=<value optimized out>) at /tools/php7/php-7.0.2/Zend/zend_vm_execute.h:417
#8  0x00000000007fb568 in zend_call_function (fci=0x7ffe265f2680, fci_cache=0x7ffe265f2600)
    at /tools/php7/php-7.0.2/Zend/zend_execute_API.c:860
#9  0x00000000007fbaca in call_user_function_ex (function_table=<value optimized out>, object=<value optimized out>, 
    function_name=<value optimized out>, retval_ptr=<value optimized out>, param_count=<value optimized out>, 
    params=<value optimized out>, no_separation=0, symbol_table=0x0) at /tools/php7/php-7.0.2/Zend/zend_execute_API.c:685
#10 0x00007f856b57b91b in sw_call_user_function_ex (cli=<value optimized out>, data=0x20a52d0 "SW\002\001\001\001", 
    length=<value optimized out>) at /tools/php7/swoole-1.8.4/php7_wrapper.h:224
#11 client_onReceive (cli=<value optimized out>, data=0x20a52d0 "SW\002\001\001\001", length=<value optimized out>)
    at /tools/php7/swoole-1.8.4/swoole_client.c:237
#12 0x00007f856b57b9a0 in client_onPackage (conn=<value optimized out>, data=<value optimized out>, length=<value optimized out>)
    at /tools/php7/swoole-1.8.4/swoole_client.c:207
#13 0x00007f856b5ab4b5 in swProtocol_recv_check_length (protocol=0x7f85471548e0, conn=0x7f8547d2ade0, buffer=0x2052f20)
    at /tools/php7/swoole-1.8.4/src/protocol/Base.c:157
#14 0x00007f856b59f60e in swClient_onStreamRead (reactor=<value optimized out>, event=0x7ffe265f2960)
    at /tools/php7/swoole-1.8.4/src/network/Client.c:693
#15 0x00007f856b599cb4 in swReactorEpoll_wait (reactor=0x203fc20, timeo=<value optimized out>)
    at /tools/php7/swoole-1.8.4/src/reactor/ReactorEpoll.c:258
#16 0x00007f856b5a7853 in swWorker_loop (factory=<value optimized out>, worker_id=<value optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /tools/php7/swoole-1.8.4/src/network/Worker.c:489
#17 0x00007f856b5a4cb0 in swManager_spawn_worker (factory=0x203dc50, worker_id=1)
    at /tools/php7/swoole-1.8.4/src/network/Manager.c:682
#18 0x00007f856b5a5769 in swManager_start (factory=0x203dc50) at /tools/php7/swoole-1.8.4/src/network/Manager.c:135
#19 0x00007f856b596f42 in swFactoryProcess_start (factory=0x203dc50) at /tools/php7/swoole-1.8.4/src/factory/FactoryProcess.c:86
#20 0x00007f856b59c75e in swServer_start (serv=0x203d820) at /tools/php7/swoole-1.8.4/src/network/Server.c:620
#21 0x00007f856b576fee in zim_swoole_server_start (execute_data=<value optimized out>, return_value=0x7f856ba141d0)
    at /tools/php7/swoole-1.8.4/swoole_server.c:1781
#22 0x000000000087eb47 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f856ba14110)
    at /tools/php7/php-7.0.2/Zend/zend_vm_execute.h:842
#23 0x0000000000846f50 in execute_ex (ex=<value optimized out>) at /tools/php7/php-7.0.2/Zend/zend_vm_execute.h:417
#24 0x0000000000899acb in zend_execute (op_array=0x7f856ba7d000, return_value=<value optimized out>)
    at /tools/php7/php-7.0.2/Zend/zend_vm_execute.h:458
#25 0x00000000008084c3 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tools/php7/php-7.0.2/Zend/zend.c:1427
#26 0x00000000007ab060 in php_execute_script (primary_file=0x7ffe265f6090) at /tools/php7/php-7.0.2/main/main.c:2471
#27 0x000000000089de43 in do_cli (argc=5, argv=0x1e2e4f0) at /tools/php7/php-7.0.2/sapi/cli/php_cli.c:974
#28 0x000000000089e5ea in main (argc=5, argv=0x1e2e4f0) at /tools/php7/php-7.0.2/sapi/cli/php_cli.c:1345
```

**Comment by matyhtf** [comment]
请使用 1.8.9 版本测试一下

**Comment by matyhtf** [comment]
Table的lock已经移除了。
