### ISSUE TITLE
HttpServer segfault with Thread mode

### ISSUE THREAD

**Issue by szicsu** [swoole/swoole-src#871]
I try the threading mode with this code:
```php
class myCounter{
    private static $i = 0;
    public static function inc(){ return ++self::$i;}
}
$http = new swoole_http_server("0.0.0.0", 9100, SWOOLE_THREAD);
$http->set([ 'daemonize' => FALSE, 'worker_num' => 4]);

$http->on('request', function(swoole_http_request $request, swoole_http_response $response){
    $response->end(sprintf('Counter: %s' . PHP_EOL, myCounter::inc()));
});
$http->start();
```
Unfortunately I get lot of different segfaults:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb7fe700 (LWP 26)]
0x00005555557cb644 in zend_hash_find ()
(gdb) backtrace
#0  0x00005555557cb644 in zend_hash_find ()
#1  0x00005555557f33dc in zend_std_get_static_property ()
#2  0x00005555558103fa in ?? ()
#3  0x00005555557f76db in execute_ex ()
#4  0x00005555557a7348 in dtrace_execute_ex ()
#5  0x000055555583c48d in ?? ()
#6  0x00005555557f76db in execute_ex ()
#7  0x00005555557a7348 in dtrace_execute_ex ()
#8  0x00005555557a905e in zend_call_function ()
#9  0x00005555557a9449 in call_user_function_ex ()
#10 0x00007ffff32aedec in sw_call_user_function_ex (ymbol_table=<optimized out>, no_separation=<optimized out>, params=<optimized out>, param_count=<optimized out>, retval_ptr_ptr=<optimized out>, 
    function_name=<optimized out>, object_pp=<optimized out>, function_table=<optimized out>) at /usr/local/src/swoole-src/php7_wrapper.h:231
#11 http_onReceive (serv=0x555555c5a100 <executor_globals>, req=0x5555565b61e0) at /usr/local/src/swoole-src/swoole_http_server.c:981
#12 0x00007ffff32d44fb in swWorker_onTask (factory=0x8, task=0x5555565b61e0) at /usr/local/src/swoole-src/src/network/Worker.c:193
#13 0x00007ffff32c26e2 in swFactoryThread_onTask (pool=<optimized out>, data=0x5555565b61e0, len=<optimized out>) at /usr/local/src/swoole-src/src/factory/FactoryThread.c:241
#14 0x00007ffff32ce487 in swThreadPool_loop (arg=<optimized out>) at /usr/local/src/swoole-src/src/network/ThreadPool.c:181
#15 0x00007ffff62b30a4 in start_thread (arg=0x7fffeb7fe700) at pthread_create.c:309
#16 0x00007ffff65b062d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb7fe700 (LWP 40)]
0x0000555555793f53 in _emalloc ()
(gdb) backtrace
#0  0x0000555555793f53 in _emalloc ()
#1  0x00005555557c5162 in _zend_hash_str_update ()
#2  0x00005555557ba891 in add_assoc_stringl_ex ()
#3  0x00007ffff32aeb74 in http_onReceive (serv=0x55555657a000, req=0x5555565b6420) at /usr/local/src/swoole-src/swoole_http_server.c:918
#4  0x00007ffff32d44fb in swWorker_onTask (factory=0x4, task=0x5555565b6420) at /usr/local/src/swoole-src/src/network/Worker.c:193
#5  0x00007ffff32c26e2 in swFactoryThread_onTask (pool=<optimized out>, data=0x5555565b6420, len=<optimized out>) at /usr/local/src/swoole-src/src/factory/FactoryThread.c:241
#6  0x00007ffff32ce487 in swThreadPool_loop (arg=<optimized out>) at /usr/local/src/swoole-src/src/network/ThreadPool.c:181
#7  0x00007ffff62b30a4 in start_thread (arg=0x7fffeb7fe700) at pthread_create.c:309
#8  0x00007ffff65b062d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
I played with `--enable-tcmalloc` complier options, but it's not helped :(

I use the PHP with ZTS, but it's not started:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe989b700 (LWP 18)]
0x00005555557e023f in zend_update_property ()
(gdb) backtrace
#0  0x00005555557e023f in zend_update_property ()
#1  0x00005555557e03f8 in zend_update_property_long ()
#2  0x00007fffebe30ae8 in php_swoole_onWorkerStart (serv=0x5555565fc000, worker_id=0) at /usr/local/src/swoole-src/swoole_server.c:943
#3  0x00007fffebe5c4ff in swFactoryThread_onStart (pool=<optimized out>, id=0) at /usr/local/src/swoole-src/src/factory/FactoryThread.c:191
#4  0x00007fffebe68157 in swThreadPool_loop (arg=<optimized out>) at /usr/local/src/swoole-src/src/network/ThreadPool.c:152
#5  0x00007ffff665e0a4 in start_thread (arg=0x7fffe989b700) at pthread_create.c:309
#6  0x00007ffff639362d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

My system:
 - Debian8 
 - PHP 7.0.11
 - Swoole - master

**Comment by matyhtf** [comment]
Thread mode is still a problem, please use the process mode
