### ISSUE TITLE
coredump use php7 with throwable

### ISSUE THREAD

**Issue by lscgzwd** [swoole/swoole-src#924]
GDB

```
#0  0x00000000007b81cb in zval_delref_p (zval_ptr=0x7fe908acc298) at /data/php7-src/php-7.0.9/Zend/zend_types.h:827
#1  i_zval_ptr_dtor (zval_ptr=0x7fe908acc298) at /data/php7-src/php-7.0.9/Zend/zend_variables.h:57
#2  _zval_ptr_dtor (zval_ptr=0x7fe908acc298) at /data/php7-src/php-7.0.9/Zend/zend_execute_API.c:533
#3  0x00007fe90c04a350 in http_onReceive (serv=0x3068040, req=<value optimized out>) at /data/php7-src/swoole-src/swoole_http_server.c:999
#4  0x00007fe90c075b02 in swWorker_onTask (factory=<value optimized out>, task=0x7fff5f5a5ff8) at /data/php7-src/swoole-src/src/network/Worker.c:193
#5  0x00007fe90c070103 in swReactorThread_dispatch (conn=0x7fe90a81ba10, 
    data=0x3112620 "GET /staff/export-list?staffType=-1&status=0&token=ed3ac60f6cebe71635b54c4ef9b55c42f3d9a22da81f112854734917e367cb6b&companyID=645286680350170311 HTTP/1.0\r\nHost: 127.0.0.1:9501\r\nConnection: close\r\nPrag"..., length=<value optimized out>) at /data/php7-src/swoole-src/src/network/ReactorThread.c:1295
#6  0x00007fe90c077ad2 in swPort_onRead_http (reactor=0x3068978, port=0x7fe90be1b358, event=0x7fff5f5a80e0) at /data/php7-src/swoole-src/src/network/Port.c:460
#7  0x00007fe90c0675d0 in swReactorEpoll_wait (reactor=0x3068978, timeo=<value optimized out>) at /data/php7-src/swoole-src/src/reactor/ReactorEpoll.c:258
#8  0x00007fe90c072d41 in swReactorProcess_loop (pool=<value optimized out>, worker=0x7fe90be1c180) at /data/php7-src/swoole-src/src/network/ReactorProcess.c:377
#9  0x00007fe90c06ea87 in swProcessPool_spawn (worker=0x7fe90be1c180) at /data/php7-src/swoole-src/src/network/ProcessPool.c:248
#10 0x00007fe90c06efa9 in swProcessPool_start (pool=0x7fe90be1b2b8) at /data/php7-src/swoole-src/src/network/ProcessPool.c:111
#11 0x00007fe90c073273 in swReactorProcess_start (serv=<value optimized out>) at /data/php7-src/swoole-src/src/network/ReactorProcess.c:175
#12 0x00007fe90c06a850 in swServer_start (serv=0x3068040) at /data/php7-src/swoole-src/src/network/Server.c:667
#13 0x00007fe90c048eaf in zim_swoole_http_server_start (execute_data=0x7fe90cc13a60, return_value=0x7fe90cc13a50) at /data/php7-src/swoole-src/swoole_http_server.c:1388
#14 0x000000000083d2b8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7fe90cc13840) at /data/php7-src/php-7.0.9/Zend/zend_vm_execute.h:842
#15 0x0000000000805190 in execute_ex (ex=<value optimized out>) at /data/php7-src/php-7.0.9/Zend/zend_vm_execute.h:417
#16 0x00000000008582eb in zend_execute (op_array=0x7fe90cc7c000, return_value=<value optimized out>) at /data/php7-src/php-7.0.9/Zend/zend_vm_execute.h:458
#17 0x00000000007c5b43 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /data/php7-src/php-7.0.9/Zend/zend.c:1427
#18 0x00000000007680b0 in php_execute_script (primary_file=0x7fff5f5ab8b0) at /data/php7-src/php-7.0.9/main/main.c:2494
#19 0x000000000085c64a in do_cli (argc=3, argv=0x2f2f440) at /data/php7-src/php-7.0.9/sapi/cli/php_cli.c:974
#20 0x000000000085ce4a in main (argc=3, argv=0x2f2f440) at /data/php7-src/php-7.0.9/sapi/cli/php_cli.c:1344
```

php版本7.0.9
swoole: 1.9.0

```
/**
     * Swoole\Http\Server http request callback
     * @param Request $request
     * @param Response $response
     */
    public function onRequest(Request $request, Response $response)
    {
        $_GET    = isset($request->get) ? $request->get : [];
        $_POST   = isset($request->post) ? $request->post : [];
        $_SERVER = array_change_key_case($request->server, CASE_UPPER);
        $_FILES  = isset($request->files) ? $request->files : [];
        $_COOKIE = isset($request->cookie) ? $request->cookie : [];
        if (isset($request->header)) {
            foreach ($request->header as $key => $value) {
                $key           = 'HTTP_' . strtoupper(str_replace('-', '_', $key));
                $_SERVER[$key] = $value;
            }
        }
        // swoole fix
        $_SERVER['PHP_SELF']        = '/index.php';
        $_SERVER['SCRIPT_NAME']     = '/index.php';
        $_SERVER['SCRIPT_FILENAME'] = WEB_PATH . '/index.php';
        $_SERVER['SERVER_NAME']     = 'qiye.jiedaibao.com';

        $this->logTraceId            = StringHelper::uuid();
        $this->currentSwooleRequest  = $request;
        $this->currentSwooleResponse = $response;
        // if request uri exist, just send it to client
        if ($this->processStatic()) {
            $this->clearRequestAndResponse();
            return;
        }

        $this->currentSwooleResponse->header('Access-Control-Allow-Origin', '*');
        $this->currentSwooleResponse->header('Access-Control-Allow-Credentials', 'true');
        $this->currentSwooleResponse->header('Conent-Type', 'application/json; charset=utf-8');

        try {
            Yii::$app->getRequest()->setSwooleRequest($request);
            Yii::$app->getResponse()->setSwooleResponse($response);

            Yii::$app->run();
            // force flush the log
            Yii::getLogger()->flush();
            Yii::getLogger()->flush(true);
            $this->clearRequestAndResponse();
        } catch (\Throwable $e) {
            if ($e instanceof ExitException) {
                // add log to track where throw this exception
                Trace::addLog('catch_exit_exception', 'info',
                    [
                        'msg'     => $e->getMessage(),
                        'line'    => $e->getLine(),
                        'file'    => $e->getFile(),
                        'request' => get_object_vars($request),
                        'trace'   => $e->getTraceAsString(),
                        'linelog' => __LINE__,
                    ]);
            } elseif ($e instanceof EndException) {
                // if you called Swoole::sendfile or manually end the response, throw this exception to end the request
            } else {
                // other exceptions
                Trace::addLog('Exception_when_request', 'error', [
                    'msg'     => $e->getMessage(),
                    'line'    => $e->getLine(),
                    'file'    => $e->getFile(),
                    'trace'   => $e->getTraceAsString(),
                    'SERVER'  => $_SERVER,
                    'request' => get_object_vars($request),
                    'linelog' => __LINE__,
                ]);
                $data = ModelConst::getResult(ModelConst::G_SYS_ERR);
                $this->currentSwooleResponse->header('Content-Type', 'application/json; charset=utf-8');
                $response->end(json_encode($data));
                unset($data);
            }
            $this->clearRequestAndResponse();
            Yii::getLogger()->flush();
            Yii::getLogger()->flush(true);
        }
    }
```

把  } catch (\Throwable $e) { 改成  } catch (\Exception $e) {就不会core

**Comment by matyhtf** [comment]
无法重现。单独throw一个exception没有问题。

**Comment by lscgzwd** [comment]
写了一个单例，也无法重现，但是在线上基于YII2的代码 中必现，待后续挖掘原因吧，这个需要费时去调试
